// skills/tdesign-mobile-react/references/examples/link/underline.tsx
/**
 * TDesign TDesign Mobile React 示例：link - underline
 * 覆盖组件：Link
 * 来源：组件库源码 src/link/_example/underline.tsx
 */

import React from 'react';
import { Link } from 'tdesign-mobile-react';

export default function Underline() {
  return (
    <div className="demo-content">
      <Link size="small" theme="primary" underline>
        跳转链接
      </Link>
      <Link size="small" underline hover>
        跳转链接
      </Link>
    </div>
  );
}

// skills/tdesign-vue2/references/examples/link/underline.vue
<!--
  TDesign TDesign Vue 2 示例：link - underline
  覆盖组件：Link
  来源：组件库源码 src/link/_example/underline.vue
-->

<template>
  <t-space>
    <t-link theme="default" underline> 跳转链接 </t-link>
    <t-link theme="primary" underline> 跳转链接 </t-link>
    <t-link theme="danger" underline> 跳转链接 </t-link>
    <t-link theme="warning" underline> 跳转链接 </t-link>
    <t-link theme="success" underline> 跳转链接 </t-link>
  </t-space>
</template>
