// skills/tdesign-vue-next/references/examples/collapse/other.vue
<!--
  TDesign TDesign Vue Next 示例：collapse - other
  覆盖组件：Collapse
  来源：组件库源码 packages/components/collapse/_example/other.vue
-->

<template>
  <t-space direction="vertical">
    <t-collapse :expand-icon="showArrow" :disabled="disabled" :borderless="borderless" @change="handlePanelChange">
      <t-collapse-panel value="0" header="这是一个折叠标题">
        这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
      </t-collapse-panel>

      <t-collapse-panel value="1">
        <template #header>这是一个折叠标题</template>
        <template #default
          >这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。</template
        >
      </t-collapse-panel>

      <t-collapse-panel value="2">
        <template #header>这是一个折叠标题</template>
        这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
      </t-collapse-panel>
      <t-collapse-panel value="3" header="这是一个折叠标题">
        这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
      </t-collapse-panel>
    </t-collapse>

    <t-space align="center">
      <t-checkbox v-model="disabled">全部禁用</t-checkbox>
      <t-checkbox v-model="borderless">无边框模式</t-checkbox>
      <t-checkbox v-model="showArrow">显示箭头</t-checkbox>
    </t-space>
  </t-space>
</template>

<script lang="tsx" setup>
import { ref } from 'vue';
import type { CollapseProps } from 'tdesign-vue-next';

const disabled = ref(false);
const borderless = ref(false);
const showArrow = ref<CollapseProps['expandIcon']>(true);
const handlePanelChange: CollapseProps['onChange'] = (val) => {
  console.log('panel', val);
};
</script>

// skills/tdesign-react/references/examples/collapse/other.tsx
/**
 * TDesign TDesign React 示例：collapse - other
 * 覆盖组件：Collapse
 * 来源：组件库源码 packages/components/collapse/_example/other.tsx
 */

import React, { useState } from 'react';
import { Checkbox, Collapse, Space, TagInput } from 'tdesign-react';

const { Panel } = Collapse;
export default function CollapseExample() {
  const [collapseValue, setCollapseValue] = useState([]);
  const [disabledAll, setDisabledAll] = useState(false);
  const [borderless, setBorderless] = useState(false);
  const [showIcon, setShowIcon] = useState(true);
  return (
    <Space direction="vertical">
      <Collapse
        expandIcon={showIcon}
        value={collapseValue}
        borderless={borderless}
        disabled={disabledAll}
        onChange={setCollapseValue}
      >
        <Panel header="这是一个折叠标题">
          这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
        </Panel>
        <Panel destroyOnCollapse header="折叠后自动销毁">
          这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
        </Panel>
        <Panel header="自定义折叠面板内容">
          <div className="tdesign-demo-block-column" style={{ width: '80%' }}>
            <TagInput defaultValue={['Vue', 'React']} clearable />
          </div>
        </Panel>
      </Collapse>
      <Space direction="vertical">
        <Checkbox
          checked={disabledAll}
          onChange={() => {
            setDisabledAll(!disabledAll);
          }}
        >
          禁止全部
        </Checkbox>
        <Checkbox
          checked={borderless}
          onChange={() => {
            setBorderless(!borderless);
          }}
        >
          无边框模式
        </Checkbox>
        <Checkbox
          checked={showIcon}
          onChange={() => {
            setShowIcon(!showIcon);
          }}
        >
          显示icon
        </Checkbox>
        <div style={{ marginTop: 10 }}>当前展开的Collapse Panel: {collapseValue.map((item) => `${item} `)}</div>
      </Space>
    </Space>
  );
}
