// skills/tdesign-vue2/references/examples/dropdown/split.vue
<!--
  TDesign TDesign Vue 2 示例：dropdown - split
  覆盖组件：Dropdown
  来源：组件库源码 src/dropdown/_example/split.vue
-->

<template>
  <div>
    <t-dropdown :options="options">
      <t-button theme="default" variant="outline">下拉菜单</t-button>
    </t-dropdown>
  </div>
</template>
<script>
export default {
  data() {
    return {
      options: [
        {
          content: '操作一',
          value: 1,
        },
        {
          content: '操作二',
          value: 2,
        },
        {
          content: '操作三',
          value: 3,
          divider: true,
        },
        {
          content: '操作四',
          value: 4,
        },
      ],
    };
  },
};
</script>
<style scoped>
.t-button {
  margin-right: 20px;
}
</style>

// skills/tdesign-react/references/examples/dropdown/split.tsx
/**
 * TDesign TDesign React 示例：dropdown - split
 * 覆盖组件：Dropdown
 * 来源：组件库源码 packages/components/dropdown/_example/split.tsx
 */

import React from 'react';
import { Icon } from 'tdesign-icons-react';
import { Button, Dropdown, MessagePlugin } from 'tdesign-react';

import type { DropdownProps } from 'tdesign-react';

export default function BasicDropdown() {
  const getContent = () => <div>操作四</div>;
  const options = [
    {
      content: '操作一',
      value: 1,
    },
    {
      content: '操作二',
      value: 2,
    },
    {
      content: '操作三',
      value: 3,
      divider: true,
    },
    {
      content: getContent(),
      value: 4,
    },
  ];
  const clickHandler: DropdownProps['onClick'] = (data) => {
    MessagePlugin.success(`选中【${data.value}】`);
  };
  return (
    <Dropdown options={options} onClick={clickHandler}>
      <Button variant="text" suffix={<Icon name="chevron-down" size="16" />}>
        更多
      </Button>
    </Dropdown>
  );
}
