// skills/tdesign-mobile-vue/references/examples/navbar/img.vue
<!--
  TDesign TDesign Mobile Vue 示例：navbar - img
  覆盖组件：Navbar
  来源：组件库源码 src/navbar/demos/img.vue
-->

<template>
  <t-navbar :fixed="false">
    <template #left>
      <t-image src="https://tdesign.gtimg.com/mobile/demos/logo1.png" class="logo" />
    </template>
    <template #right>
      <t-icon name="home" size="24px" />
      <t-icon name="ellipsis" size="24px" />
    </template>
  </t-navbar>
</template>

<script lang="ts" setup>
import { Icon as TIcon } from 'tdesign-icons-vue-next';
</script>

<style lang="less" scoped>
.logo {
  width: 102px;
  height: 24px;
}

.t-icon-home {
  margin-right: 8px;
}
</style>

// skills/tdesign-mobile-react/references/examples/navbar/img.tsx
/**
 * TDesign TDesign Mobile React 示例：navbar - img
 * 覆盖组件：Navbar
 * 来源：组件库源码 src/navbar/_example/img.tsx
 */

import React from 'react';
import { Navbar } from 'tdesign-mobile-react';
import { EllipsisIcon, HomeIcon } from 'tdesign-icons-react';

const ImgDemo = () => (
  <>
    <Navbar
      left={<img src="https://tdesign.gtimg.com/mobile/demos/logo1.png" className="logo" />}
      right={
        <>
          <HomeIcon size={24} />
          <EllipsisIcon size={24} />
        </>
      }
      fixed={false}
    />
  </>
);

export default ImgDemo;
