// skills/tdesign-vue-next/references/examples/guide/no-mask.vue
<!--
  TDesign TDesign Vue Next 示例：guide - no-mask
  覆盖组件：Guide
  来源：组件库源码 packages/components/guide/_example/no-mask.vue
-->

<template>
  <t-row justify="center">
    <t-button @click="handleClick">新手引导</t-button>
    <t-drawer v-model:visible="visible" header="演示新手引导" size="60%" :show-overlay="false" destroy-on-close>
      <template #footer>
        <t-button @click="visible = false"> 关闭抽屉 </t-button>
      </template>
      <div class="guide-container">
        <div class="main-title">
          <div class="title-major">Guide 用户引导</div>
          <div class="title-sub">按钮用于开启一个闭环的操作任务，如“删除”对象、“购买”商品等。</div>
        </div>
        <div class="field label-field">
          <div class="label">Label</div>
          <t-input placeholder="请输入内容" />
        </div>
        <div class="field">
          <div class="label">Label</div>
          <t-input placeholder="请输入内容" />
        </div>
        <t-row class="action">
          <t-button>确定</t-button>
          <t-button theme="default" variant="base">取消</t-button>
        </t-row>
      </div>

      <t-guide
        v-model="current"
        :steps="steps"
        :show-overlay="false"
        @change="handleChange"
        @prev-step-click="handlePrevStepClick"
        @next-step-click="handleNextStepClick"
        @finish="handleFinish"
        @skip="handleSkip"
      />
    </t-drawer>
  </t-row>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import type { GuideProps, ButtonProps } from 'tdesign-vue-next';

const visible = ref(false);
const current = ref(-1);
const steps: GuideProps['steps'] = [
  {
    element: '.main-title',
    title: '新手引导标题',
    body: '新手引导的说明文案',
    placement: 'bottom-right',
  },
  {
    element: '.label-field',
    title: '新手引导标题',
    body: '新手引导的说明文案',
    placement: 'bottom',
  },
  {
    element: '.action',
    title: '新手引导标题',
    body: '新手引导的说明文案',
    placement: 'right',
  },
];
const handleClick: ButtonProps['onClick'] = () => {
  visible.value = true;
  setTimeout(() => {
    current.value = 0;
  }, 800);
};
const handleChange: GuideProps['onChange'] = (current, { e, total }) => {
  console.log(current, e, total);
};
const handlePrevStepClick: GuideProps['onPrevStepClick'] = ({ e, prev, current, total }) => {
  console.log(e, prev, current, total);
};
const handleNextStepClick: GuideProps['onNextStepClick'] = ({ e, next, current, total }) => {
  console.log(e, next, current, total);
};
const handleFinish: GuideProps['onFinish'] = ({ e, current, total }) => {
  visible.value = false;
  console.log(e, current, total);
};
const handleSkip: GuideProps['onSkip'] = ({ e, current, total }) => {
  visible.value = false;
  console.log(e, current, total);
};
</script>

<style scoped>
.guide-container {
  max-width: 600px;
  padding: 40px;
}

.title-major {
  color: var(--td-text-color-primary);
  font-size: 36px;
  font-weight: 700;
  line-height: 44px;
}

.title-sub {
  margin-top: 8px;
  color: var(--td-text-color-secondary);
  font-size: 14px;
  font-weight: 400;
  line-height: 22px;
}

.field {
  margin-top: 50px;
}

.label {
  margin-bottom: 8px;
  color: var(--td-text-color-primary);
  font-size: 14px;
  font-weight: 400;
  line-height: 22px;
}

.action {
  display: inline-flex;
  margin-top: 50px;
}

.action button:first-child {
  margin-right: 10px;
}
</style>

// skills/tdesign-react/references/examples/guide/no-mask.tsx
/**
 * TDesign TDesign React 示例：guide - no-mask
 * 覆盖组件：Guide
 * 来源：组件库源码 packages/components/guide/_example/no-mask.tsx
 */

import React, { useEffect } from 'react';
import { Button, Drawer, Guide, Input, Row } from 'tdesign-react';

import type { GuideProps, GuideStep } from 'tdesign-react';

const classStyles = `
<style>
.guide-container {
  max-width: 600px;
  padding: 40px;
}

.title-major {
  color: var(--td-text-color-primary);
  font-size: 36px;
  font-weight: 700;
  line-height: 44px;
}

.title-sub {
  margin-top: 8px;
  color: var(--td-text-color-secondary);
  font-size: 14px;
  font-weight: 400;
  line-height: 22px;
}

.field {
  margin-top: 50px;
}

.label {
  margin-bottom: 8px;
  color: var(--td-text-color-primary);
  font-size: 14px;
  font-weight: 400;
  line-height: 22px;
}

.action {
  display: inline-flex;
  margin-top: 50px;
}

.action button:first-child {
  margin-right: 10px;
}

</style>
`;

export default function NoMaskGuide() {
  useEffect(() => {
    // 添加示例代码所需样式
    document.head.insertAdjacentHTML('beforeend', classStyles);
  }, []);

  const steps: GuideStep[] = [
    {
      element: '.main-title-no-mask',
      title: '新手引导标题',
      body: '新手引导的说明文案',
      placement: 'bottom-right',
    },
    {
      element: '.label-field-no-mask',
      title: '新手引导标题',
      body: '新手引导的说明文案',
      placement: 'bottom',
    },
    {
      element: '.action-no-mask',
      title: '新手引导标题',
      body: '新手引导的说明文案',
      placement: 'right',
    },
  ];

  const [visible, setVisible] = React.useState(false);
  const [current, setCurrent] = React.useState(-1);

  const handleClick = () => {
    setVisible(true);
    setTimeout(() => {
      setCurrent(0);
    }, 800);
  };

  const handleChange: GuideProps['onChange'] = (current: number, { e, total }) => {
    setCurrent(current);
    console.log(current, e, total);
  };

  const handlePrevStepClick: GuideProps['onPrevStepClick'] = ({ e, prev, current, total }) => {
    console.log(e, prev, current, total);
  };

  const handleNextStepClick: GuideProps['onNextStepClick'] = ({ e, next, current, total }) => {
    console.log(e, next, current, total);
  };

  const handleFinish: GuideProps['onFinish'] = ({ e, current, total }) => {
    setVisible(false);
    console.log(e, current, total);
  };

  const handleSkip: GuideProps['onSkip'] = ({ e, current, total }) => {
    console.log('skip');
    setVisible(false);
    console.log(e, current, total);
  };

  return (
    <Row justify="center">
      <Button onClick={handleClick}>新手引导</Button>
      <Drawer
        footer={<Button onClick={() => setVisible(false)}> 关闭抽屉 </Button>}
        visible={visible}
        header="演示新手引导"
        size="60%"
        showOverlay={false}
        destroyOnClose={true}
      >
        <div className="guide-container">
          <div className="main-title-no-mask">
            <div className="title-major">Guide 用户引导</div>
            <div className="title-sub">按钮用于开启一个闭环的操作任务，如“删除”对象、“购买”商品等。</div>
          </div>
          <div className="field label-field-no-mask">
            <div className="label">Label</div>
            <Input placeholder="请输入内容" />
          </div>
          <div className="field">
            <div className="label">Label</div>
            <Input placeholder="请输入内容" />
          </div>
          <Row className="action action-no-mask">
            <Button>确定</Button>
            <Button theme="default" variant="base">
              取消
            </Button>
          </Row>
        </div>

        <Guide
          current={current}
          steps={steps}
          showOverlay={false}
          onChange={handleChange}
          onPrevStepClick={handlePrevStepClick}
          onNextStepClick={handleNextStepClick}
          onFinish={handleFinish}
          onSkip={handleSkip}
        />
      </Drawer>
    </Row>
  );
}
