// skills/tdesign-vue-next/references/examples/time-picker/hide-clear-button.vue
<!--
  TDesign TDesign Vue Next 示例：time-picker - hide-clear-button
  覆盖组件：Time-picker
  来源：组件库源码 packages/components/time-picker/_example/hide-clear-button.vue
-->

<template>
  <t-space direction="vertical">
    <h3>具备清空按钮</h3>
    <t-time-picker v-model="time1" clearable />
    <h3>禁止清空按钮</h3>
    <t-time-picker :clearable="false" />
  </t-space>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

const time1 = ref('11:12:10');
</script>
<style lang="less" scoped>
.tdesign-demo-block {
  h3 {
    margin-bottom: 20px;
    font-weight: bold;
  }
  h3:nth-child(3) {
    margin-top: 30px;
  }
}
</style>

// skills/tdesign-react/references/examples/time-picker/hide-clear-button.tsx
/**
 * TDesign TDesign React 示例：time-picker - hide-clear-button
 * 覆盖组件：Time-picker
 * 来源：组件库源码 packages/components/time-picker/_example/hide-clear-button.tsx
 */

import React from 'react';
import { Space, TimePicker } from 'tdesign-react';

export default function HmTimePicker() {
  return (
    <Space direction="vertical">
      <h3>禁止清空</h3>
      <TimePicker defaultValue="12:00:00" />
      <h3>允许清空</h3>
      <TimePicker defaultValue="12:00:00" clearable={true} />
    </Space>
  );
}
