// skills/tdesign-vue2/references/examples/time-picker/hms.vue
<!--
  TDesign TDesign Vue 2 示例：time-picker - hms
  覆盖组件：Time-picker
  来源：组件库源码 src/time-picker/_example/hms.vue
-->

<template>
  <t-time-picker v-model="value" @change="timechange" @open="open" @close="close" @pick="pick" />
</template>

<script>
export default {
  name: 'hms',
  data() {
    return {
      value: '12:20:30',
    };
  },
  methods: {
    timechange(time) {
      console.log(time);
    },
    open() {
      console.log('open');
    },
    close() {
      console.log('close');
    },
    pick(v) {
      console.log(v);
    },
  },
};
</script>

// skills/tdesign-react/references/examples/time-picker/hms.tsx
/**
 * TDesign TDesign React 示例：time-picker - hms
 * 覆盖组件：Time-picker
 * 来源：组件库源码 packages/components/time-picker/_example/hms.tsx
 */

import React, { useState } from 'react';
import { TimePicker } from 'tdesign-react';

import type { TimePickerProps } from 'tdesign-react';

export default function BasicTimePicker() {
  const [value, setValue] = useState('12:00:00');

  const handleValueChange = (v: string) => {
    console.log('change', v);
    setValue(v);
  };

  const handleOnPick: TimePickerProps['onPick'] = (v, context) => {
    console.log('onPick', v, context);
  };

  const handleClose = () => {
    console.log('close');
  };

  const handleOpen = () => {
    console.log('open');
  };

  return (
    <TimePicker
      value={value}
      onChange={handleValueChange}
      onPick={handleOnPick}
      onClose={handleClose}
      onOpen={handleOpen}
      popupProps={{
        overlayInnerStyle: { fontWeight: 'normal' },
        overlayStyle: { fontWeight: 'normal' },
        overlayClassName: 'time-picker-custom-overlay-class',
        overlayInnerClassName: 'time-picker-custom-overlay-inner-class',
      }}
    />
  );
}
