// skills/tdesign-mobile-vue/references/examples/toast/theme.vue
<!--
  TDesign TDesign Mobile Vue 示例：toast - theme
  覆盖组件：Toast
  来源：组件库源码 src/toast/demos/theme.vue
-->

<template>
  <div class="toast-demo">
    <t-button block size="large" theme="primary" variant="outline" @click="showSuccessToast()">成功提示</t-button>
    <t-button block size="large" theme="primary" variant="outline" @click="showWarningToast()">警告提示</t-button>
    <t-button block size="large" theme="primary" variant="outline" @click="showErrorToast()">错误提示</t-button>
  </div>
</template>

<script setup lang="ts">
import { Toast } from 'tdesign-mobile-vue';

const showSuccessToast = () => {
  Toast({
    className: 'toast-root--success',
    duration: 50000,
    theme: 'success',
    direction: 'column',
    message: '轻提示文字内容',
  });
};
const showWarningToast = () => {
  Toast({
    theme: 'warning',
    direction: 'column',
    message: '轻提示文字内容',
  });
};
const showErrorToast = () => {
  Toast({
    theme: 'error',
    direction: 'column',
    message: '轻提示文字内容',
  });
};
</script>

// skills/tdesign-mobile-react/references/examples/popover/theme.tsx
/**
 * TDesign TDesign Mobile React 示例：popover - theme
 * 覆盖组件：Popover
 * 来源：组件库源码 src/popover/_example/theme.tsx
 */

import React from 'react';
import { Popover, Button } from 'tdesign-mobile-react';

const PopoverExample = () => (
  <div>
    <div className="popover-theme-example">
      <div className="popover-theme-example__content">
        <Popover
          placement="top"
          theme="dark"
          content="弹出气泡内容"
          triggerElement={
            <Button className="button-width--small" theme="primary" variant="outline" size="large">
              深色
            </Button>
          }
        />
      </div>
      <div className="popover-theme-example__content">
        <Popover
          placement="top"
          theme="light"
          content="弹出气泡内容"
          triggerElement={
            <Button className="button-width--small" theme="primary" variant="outline" size="large">
              浅色
            </Button>
          }
        />
      </div>
      <div className="popover-theme-example__content">
        <Popover
          placement="top"
          theme="brand"
          content="弹出气泡内容"
          triggerElement={
            <Button className="button-width--small" theme="primary" variant="outline" size="large">
              品牌色
            </Button>
          }
        />
      </div>
    </div>

    <div className="popover-theme-example">
      <div className="popover-theme-example__content">
        <Popover
          placement="top"
          theme="success"
          content="弹出气泡内容"
          triggerElement={
            <Button className="button-width--small" theme="primary" variant="outline" size="large">
              成功色
            </Button>
          }
        />
      </div>
      <div className="popover-theme-example__content">
        <Popover
          placement="top"
          theme="warning"
          content="弹出气泡内容"
          triggerElement={
            <Button className="button-width--small" theme="primary" variant="outline" size="large">
              警告色
            </Button>
          }
        />
      </div>
      <div className="popover-theme-example__content">
        <Popover
          placement="top"
          theme="error"
          content="弹出气泡内容"
          triggerElement={
            <Button className="button-width--small" theme="primary" variant="outline" size="large">
              错误色
            </Button>
          }
        />
      </div>
    </div>
  </div>
);

export default PopoverExample;
