// skills/tdesign-vue-next/references/examples/table/multiple-sort.vue
<!--
  TDesign TDesign Vue Next 示例：table - multiple-sort
  覆盖组件：Table
  来源：组件库源码 packages/components/table/_example/multiple-sort.vue
-->

<template>
  <div class="demo-container">
    <div class="item">
      <div style="margin: 16px">排序方式：{{ JSON.stringify(sort) }}</div>
      <!-- 支持受控用法 ，也支持非受控用法 -->
      <t-table
        row-key="index"
        :columns="columns"
        :data="data"
        :sort="sort"
        multiple-sort
        lazy-load
        @sort-change="sortChange"
      >
      </t-table>
    </div>
  </div>
</template>

<script lang="tsx" setup>
import { ref } from 'vue';
import { ErrorCircleFilledIcon, CheckCircleFilledIcon, CloseCircleFilledIcon } from 'tdesign-icons-vue-next';
import type { TableProps } from 'tdesign-vue-next';

const statusNameListMap = {
  0: {
    label: '审批通过',
    theme: 'success',
    icon: <CheckCircleFilledIcon />,
  },
  1: {
    label: '审批失败',
    theme: 'danger',
    icon: <CloseCircleFilledIcon />,
  },
  2: {
    label: '审批过期',
    theme: 'warning',
    icon: <ErrorCircleFilledIcon />,
  },
};
const initialData = [];
for (let i = 0; i < 5; i++) {
  initialData.push({
    index: i + 1,
    applicant: ['贾明', '张三', '王芳'][i % 3],
    status: i % 3,
    channel: ['电子签署', '纸质签署', '纸质签署'][i % 3],
    detail: {
      email: ['w.cezkdudy@lhll.au', 'r.nmgw@peurezgn.sl', 'p.cumx@rampblpa.ru'][i % 3],
    },
    matters: ['宣传物料制作费用', 'algolia 服务报销', '相关周边制作费', '激励奖品快递费'][i % 4],
    time: [2, 3, 1, 4][i % 4],
    createTime: ['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01', '2022-05-01'][i % 4],
  });
}
const columns = ref<TableProps['columns']>([
  {
    colKey: 'applicant',
    title: '申请人',
    width: '100',
  },
  {
    colKey: 'status',
    title: '申请状态',
    width: '150',
    sortType: 'all',
    sorter: true,
    cell: (h, { row }) => {
      return (
        <t-tag shape="round" theme={statusNameListMap[row.status].theme} variant="light-outline">
          {statusNameListMap[row.status].icon}
          {statusNameListMap[row.status].label}
        </t-tag>
      );
    },
  },
  {
    colKey: 'time',
    title: '申请耗时(天)',
    align: 'center',
    width: '140',
    sortType: 'all',
    sorter: true,
  },
  {
    colKey: 'channel',
    title: '签署方式',
    width: '120',
  },
  {
    colKey: 'detail.email',
    title: '邮箱地址',
    ellipsis: true,
  },
  {
    colKey: 'createTime',
    title: '申请时间',
  },
]);
const data = ref<TableProps['data']>([...initialData]);
const sort = ref<TableProps['sort']>([
  {
    sortBy: 'status',
    descending: true,
  },
  {
    sortBy: 'time',
    descending: false,
  },
]);
const sortChange: TableProps['onSortChange'] = (val) => {
  sort.value = val;
  // Request: 发起远程请求进行排序
  console.log('发起远程请求进行排序（未模拟请求数据）');
};
</script>
<style lang="less">
:deep([class*='t-table-expandable-icon-cell']) .t-icon {
  background-color: transparent;
}
</style>

// skills/tdesign-react/references/examples/table/multiple-sort.tsx
/**
 * TDesign TDesign React 示例：table - multiple-sort
 * 覆盖组件：Table
 * 来源：组件库源码 packages/components/table/_example/multiple-sort.tsx
 */

import React, { useState } from 'react';
import { CheckCircleFilledIcon, CloseCircleFilledIcon, ErrorCircleFilledIcon } from 'tdesign-icons-react';
import { Space, Table, Tag } from 'tdesign-react';

import type { TableProps } from 'tdesign-react';

const statusNameListMap = {
  0: { label: '审批通过', theme: 'success', icon: <CheckCircleFilledIcon /> },
  1: { label: '审批失败', theme: 'danger', icon: <CloseCircleFilledIcon /> },
  2: { label: '审批过期', theme: 'warning', icon: <ErrorCircleFilledIcon /> },
};
const columns: TableProps['columns'] = [
  { colKey: 'applicant', title: '申请人', width: '100' },
  {
    colKey: 'status',
    title: '申请状态',
    width: '150',
    sortType: 'all',
    sorter: true,
    cell: ({ rowIndex }) => {
      const status = rowIndex % 3;
      return (
        <Tag
          shape="round"
          theme={statusNameListMap[status].theme}
          variant="light-outline"
          icon={statusNameListMap[status].icon}
        >
          {statusNameListMap[status].label}
        </Tag>
      );
    },
  },
  {
    colKey: 'time',
    title: '申请耗时(天)',
    align: 'center',
    width: '140',
    sortType: 'all',
    sorter: true,
  },
  { colKey: 'channel', title: '签署方式', width: '120' },
  { colKey: 'detail.email', title: '邮箱地址', ellipsis: true },
  { colKey: 'createTime', title: '申请时间' },
];

const initialData = [];
for (let i = 0; i < 5; i++) {
  initialData.push({
    index: i + 1,
    applicant: ['贾明', '张三', '王芳'][i % 3],
    status: i % 3,
    channel: ['电子签署', '纸质签署', '纸质签署'][i % 3],
    detail: {
      email: ['w.cezkdudy@lhll.au', 'r.nmgw@peurezgn.sl', 'p.cumx@rampblpa.ru'][i % 3],
    },
    matters: ['宣传物料制作费用', 'algolia 服务报销', '相关周边制作费', '激励奖品快递费'][i % 4],
    time: [2, 3, 1, 4][i % 4],
    createTime: ['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01', '2022-05-01'][i % 4],
  });
}

export default function TableSingleSort() {
  const [sort, setSort] = useState([
    {
      sortBy: 'status',
      descending: true,
    },
    {
      sortBy: 'survivalTime',
      descending: false,
    },
  ]);

  function onSortChange(sort) {
    setSort(sort);
    // Request: 发起远程请求进行排序
    console.log('发起远程请求进行排序（未模拟请求数据）');
  }

  return (
    <Space direction="vertical">
      <div>排序方式：{JSON.stringify(sort)}</div>
      <Table
        rowKey="index"
        data={initialData}
        columns={columns}
        sort={sort}
        multipleSort
        onSortChange={onSortChange}
        lazyLoad
      />
    </Space>
  );
}
