// skills/tdesign-mobile-react/references/examples/sticky/container.tsx
/**
 * TDesign TDesign Mobile React 示例：sticky - container
 * 覆盖组件：Sticky
 * 来源：组件库源码 src/sticky/_example/container.tsx
 */

import React from 'react';
import { Sticky, Button } from 'tdesign-mobile-react';
import './style/index.less';

export default function Base() {
  return (
    <div className="tdesign-demo-block-3" id="container">
      <Sticky container="#container">
        <Button className="custom-button custom-common-button">指定容器</Button>
      </Sticky>
    </div>
  );
}

// skills/tdesign-mobile-vue/references/examples/sticky/container.vue
<!--
  TDesign TDesign Mobile Vue 示例：sticky - container
  覆盖组件：Sticky
  来源：组件库源码 src/sticky/demos/container.vue
-->

<template>
  <div id="container" class="sticky-demo">
    <t-sticky container="#container" @scroll="onScroll">
      <t-button size="large" class="common-button green-button">指定容器</t-button>
    </t-sticky>
  </div>
</template>
<script setup lang="ts">
const onScroll = (context: { scrollTop: number; isFixed: boolean }) => {
  console.log(context);
};
</script>

<style lang="less" scoped>
.sticky-demo {
  width: 100%;
  height: 150px;
  background-color: var(--bg-color-demo-secondary, rgba(255, 255, 255, 1));
}
.common-button {
  color: #fff;
  width: 104px;
  margin-left: 256px;
}
.green-button {
  background-color: rgba(0, 168, 112, 1);
  color: #fff;
}
</style>
