// skills/tdesign-react/references/examples/swiper/placement.tsx
/**
 * TDesign TDesign React 示例：swiper - placement
 * 覆盖组件：Swiper
 * 来源：组件库源码 packages/components/swiper/_example/placement.tsx
 */

import React from 'react';
import { Swiper } from 'tdesign-react';

const { SwiperItem } = Swiper;

export default function BasicSwiper() {
  return (
    <div className="tdesign-demo-block--swiper">
      <Swiper navigation={{ placement: 'outside' }}>
        <SwiperItem>
          <div className="demo-item">1</div>
        </SwiperItem>
        <SwiperItem>
          <div className="demo-item">2</div>
        </SwiperItem>
        <SwiperItem>
          <div className="demo-item">3</div>
        </SwiperItem>
        <SwiperItem>
          <div className="demo-item">4</div>
        </SwiperItem>
        <SwiperItem>
          <div className="demo-item">5</div>
        </SwiperItem>
        <SwiperItem>
          <div className="demo-item">6</div>
        </SwiperItem>
      </Swiper>
    </div>
  );
}

// skills/tdesign-vue2/references/examples/swiper/placement.vue
<!--
  TDesign TDesign Vue 2 示例：swiper - placement
  覆盖组件：Swiper
  来源：组件库源码 src/swiper/_example/placement.vue
-->

<template>
  <div class="tdesign-demo-block--swiper">
    <t-swiper :navigation="{ placement: 'outside' }">
      <t-swiper-item>
        <div class="demo-item">1</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">2</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">3</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">4</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">5</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">6</div>
      </t-swiper-item>
    </t-swiper>
  </div>
</template>
