// skills/tdesign-mobile-react/references/examples/calendar/range.tsx
/**
 * TDesign TDesign Mobile React 示例：calendar - range
 * 覆盖组件：Calendar
 * 来源：组件库源码 src/calendar/_example/range.tsx
 */

import React, { useState } from 'react';
import { Calendar, TCalendarValue } from 'tdesign-mobile-react';
import { SwapRightIcon } from 'tdesign-icons-react';

export default function () {
  const minDate = new Date(2022, 1, 1);
  const maxDate = new Date(2022, 2, 15);
  const today = new Date(2022, 1, 19);
  const tomorrow = new Date(2022, 1, 21);

  const [visible, setVisible] = useState(false);
  const [value, setValue] = useState<TCalendarValue[]>([today, tomorrow]);
  const handleConfirm = (val: TCalendarValue[]) => {
    setValue(JSON.parse(JSON.stringify(val)));

    setVisible(false);
  };
  const handleSelect = (val: Date) => {
    console.log(val);
  };
  const onClose = (trigger: string) => {
    setVisible(false);
    console.log('closed by', trigger);
  };

  const getDateByTimestamp = (val) => {
    const date = new Date(val);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };

  const formatTimestamp = (val) => {
    if (!val) return '';
    if (Array.isArray(val)) {
      return val.map((date) => getDateByTimestamp(date)).join('、');
    }
    return getDateByTimestamp(val);
  };

  return (
    <div className="example-calendar">
      <Calendar
        visible={visible}
        type="range"
        value={value}
        minDate={minDate}
        maxDate={maxDate}
        onConfirm={handleConfirm}
        onSelect={handleSelect}
        onClose={onClose}
      />

      <div className="wrapper" onClick={() => setVisible(true)}>
        <div className="wrapper__left">{formatTimestamp(value[0])}</div>
        <SwapRightIcon className="wrapper__center" size={'20px'} />
        <div className="wrapper__right">{formatTimestamp(value[1])}</div>
      </div>
    </div>
  );
}

// skills/tdesign-mobile-vue/references/examples/calendar/range.vue
<!--
  TDesign TDesign Mobile Vue 示例：calendar - range
  覆盖组件：Calendar
  来源：组件库源码 src/calendar/demos/range.vue
-->

<template>
  <div>
    <t-calendar
      v-model:visible="visible"
      :min-date="minDate"
      :max-date="maxDate"
      :value="value"
      type="range"
      @confirm="handleConfirm"
    ></t-calendar>
    <t-cell arrow @click="visible = true">
      <template #title>
        <div class="date-range-container">
          <span class="start-date">{{ formatDate(value[0]) }}</span>
          <swap-right-icon :fill-color="'transparent'" :stroke-color="'rgba(0, 0, 0, 0.4)'" :stroke-width="2" />
          <span class="end-date">{{ formatDate(value[1]) }}</span>
        </div>
      </template>
    </t-cell>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { SwapRightIcon } from 'tdesign-icons-vue-next';

const visible = ref(false);

const handleConfirm = (val: any) => {
  console.log(val);
  if (Array.isArray(val)) {
    value.value = val;
  }
};
const minDate = new Date(2022, 1, 1);
const maxDate = new Date(2022, 2, 15);
const today = new Date(2022, 1, 19);
const tomorrow = new Date(2022, 1, 21);
const value = ref([today, tomorrow]);

const formatDate = (date: Date) => {
  if (!date) return '';
  const year = date.getFullYear();
  const month = (date.getMonth() + 1).toString().padStart(2, '0');
  const day = date.getDate().toString().padStart(2, '0');
  return `${year}-${month}-${day}`;
};
</script>

<style scoped>
.date-range-container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
}

.start-date,
.end-date {
  font-size: 14px;
  font-weight: bold;
}

.arrow-icon {
  margin: 0 8px;
  color: #999;
}
</style>
