// skills/tdesign-mobile-react/references/examples/calendar/switch-mode.tsx
/**
 * TDesign TDesign Mobile React 示例：calendar - switch-mode
 * 覆盖组件：Calendar
 * 来源：组件库源码 src/calendar/_example/switch-mode.tsx
 */

import React, { useState } from 'react';
import { Calendar, Cell } from 'tdesign-mobile-react';

export default function () {
  const minDate = new Date(2012, 0, 0);
  const maxDate = new Date(2032, 0, 0);
  const defaultDate = new Date(2022, 1, 18);
  const [value, setValue] = useState(defaultDate);
  const [visible, setVisible] = useState(false);

  const formatDate = (val: Date) => {
    const date = new Date(val);
    return `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
  };

  const handleConfirm = (val: Date) => {
    console.log('confirm: ', val);
    setValue(val);
    setVisible(false);
  };
  const handleSelect = (val: Date) => {
    console.log('select: ', val);
  };
  const onClose = (trigger: string) => {
    setVisible(false);
    console.log('closed by: ', trigger);
  };
  const onPanelChange = ({ year, month }: { year: number; month: number }) => {
    console.log('panel change: ', year, month);
  };
  const onScroll = ({ e }: { e: React.UIEvent }) => {
    console.log('scroll: ', e);
  };

  return (
    <div>
      <Calendar
        visible={visible}
        switchMode="year-month"
        value={value}
        minDate={minDate}
        maxDate={maxDate}
        onConfirm={handleConfirm}
        onSelect={handleSelect}
        onClose={onClose}
        onPanelChange={onPanelChange}
        onScroll={onScroll}
      ></Calendar>
      <Cell title="带翻页功能" arrow note={formatDate(value)} onClick={() => setVisible(true)}></Cell>
    </div>
  );
}

// skills/tdesign-mobile-vue/references/examples/calendar/switch-mode.vue
<!--
  TDesign TDesign Mobile Vue 示例：calendar - switch-mode
  覆盖组件：Calendar
  来源：组件库源码 src/calendar/demos/switch-mode.vue
-->

<template>
  <div>
    <t-calendar
      v-model:visible="visible"
      switch-mode="year-month"
      :min-date="minDate"
      :max-date="maxDate"
      :value="defaultDate"
      @scroll="onScroll"
      @confirm="handleConfirm"
      @select="handleSelect"
      @panel-change="onPanelChange"
    />
    <t-cell title="带翻页功能的日历" arrow :note="dateNote" @click="visible = true" />
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import type { CalendarValue } from 'tdesign-mobile-vue';

const visible = ref(false);
const dateNote = ref('');
const minDate = new Date(2012, 0, 0);
const maxDate = new Date(2032, 0, 0);
const defaultDate = new Date(2022, 1, 18);

const format = (val: Date) => {
  const date = new Date(val);
  const year = date.getFullYear();
  const month = (date.getMonth() + 1).toString().padStart(2, '0');
  const day = date.getDate().toString().padStart(2, '0');
  return `${year}-${month}-${day}`;
};

dateNote.value = format(defaultDate);

const handleConfirm = (val: CalendarValue) => {
  console.log(val);
  dateNote.value = format(val as Date);
};

const handleSelect = (val: Date) => {
  console.log('selected:', val);
};

const onPanelChange = (context: { year: number; month: number }) => {
  console.log('panel change: ', context.year, context.month);
};

const onScroll = (context: { e: Event }) => {
  console.log('scroll: ', context.e);
};
</script>
