// skills/tdesign-react/references/examples/card/bordered-none.tsx
/**
 * TDesign TDesign React 示例：card - bordered-none
 * 覆盖组件：Card
 * 来源：组件库源码 packages/components/card/_example/bordered-none.tsx
 */

import React from 'react';
import { Card, MessagePlugin } from 'tdesign-react';

const clickHandler = () => {
  MessagePlugin.success('操作');
};

export default function BorderedNoneCard() {
  return (
    <div style={{ padding: '16px', backgroundColor: 'var(--td-bg-color-container-hover)' }}>
      <Card
        title="标题"
        actions={
          <a href={null} onClick={clickHandler} style={{ cursor: 'pointer' }}>
            操作
          </a>
        }
        hoverShadow
        style={{ width: '400px' }}
      >
        仅有内容区域的卡片形式。卡片内容区域可以是文字、图片、表单、表格等形式信息内容。可使用大中小不同的卡片尺寸，按业务需求进行呈现。
      </Card>
    </div>
  );
}

// skills/tdesign-vue2/references/examples/card/bordered-none.vue
<!--
  TDesign TDesign Vue 2 示例：card - bordered-none
  覆盖组件：Card
  来源：组件库源码 src/card/_example/bordered-none.vue
-->

<template>
  <div class="demo-card">
    <t-card :title="title" :bordered="false" hover-shadow :style="{ width: '400px' }">
      {{ infoMessage }}
      <template #actions>
        <a href="javascript:void(0)" @click="clickHandler" style="line-height: 24px">操作</a>
      </template>
    </t-card>
  </div>
</template>
<script>
import { MessagePlugin } from 'tdesign-vue';

export default {
  data() {
    return {
      title: '标题',
      infoMessage:
        '仅有内容区域的卡片形式。卡片内容区域可以是文字、图片、表单、表格等形式信息内容。可使用大中小不同的卡片尺寸，按业务需求进行呈现。',
    };
  },
  methods: {
    clickHandler() {
      MessagePlugin.success('操作');
    },
  },
};
</script>
<style lang="less" scoped>
.demo-card {
  padding: 16px;
  background-color: var(--td-bg-color-container-hover);
}
</style>
