// skills/tdesign-vue-next/references/examples/typography/copyable.vue
<!--
  TDesign TDesign Vue Next 示例：typography - copyable
  覆盖组件：Typography
  来源：组件库源码 packages/components/typography/_example/copyable.vue
-->

<template>
  <div style="width: 100%">
    <t-typography-text copyable>This is a copyable text.</t-typography-text>
    <br />
    <t-typography-text
      :copyable="{
        tooltipProps: {
          content: 'click to copy the text',
        },
      }"
      >This is a copyable text.</t-typography-text
    >
    <br />
    <t-typography-text :copyable="copyableConfig">This is a copyable text.</t-typography-text>
  </div>
</template>

<script setup lang="tsx">
import { SmileIcon } from 'tdesign-icons-vue-next';

const copyableConfig = {
  suffix: <SmileIcon />,
  tooltipProps: {
    content: 'click to copy the text',
  },
};
</script>

<style scoped></style>

// skills/tdesign-react/references/examples/typography/copyable.tsx
/**
 * TDesign TDesign React 示例：typography - copyable
 * 覆盖组件：Typography
 * 来源：组件库源码 packages/components/typography/_example/copyable.tsx
 */

import React from 'react';
import { AngryIcon, SmileIcon } from 'tdesign-icons-react';
import { Typography } from 'tdesign-react';

const { Text } = Typography;

const textString = `TDesign was founded with the principles of open-source collaboration from the beginning. The collaboration scheme discussion, component design, and API design, including source code, are fully open within the company, garnering widespread attention from internal developers and designers. TDesign follows an equal, open, and strict policy, regardless of the participants' roles.`;

export default function CopyableExample() {
  return (
    <>
      <Text copyable>This is a copyable text.</Text>
      <br />
      <Text
        ellipsis
        copyable={{
          text: textString,
          tooltipProps: {
            content: 'click to copy',
          },
        }}
        style={{ display: 'inline-block', width: '50%' }}
      >
        This is a copyable long text. {textString}
      </Text>
      <br />
      <Text
        copyable={{
          suffix: ({ copied }) => (copied ? <SmileIcon /> : <AngryIcon />),
        }}
      >
        This is a copyable long text with custom suffix.
      </Text>
    </>
  );
}
