// skills/tdesign-mobile-react/references/examples/rate/show-text.tsx
/**
 * TDesign TDesign Mobile React 示例：rate - show-text
 * 覆盖组件：Rate
 * 来源：组件库源码 src/rate/_example/show-text.tsx
 */

import React from 'react';
import { Cell, CellGroup, Rate } from 'tdesign-mobile-react';

export default function ShowText() {
  return (
    <CellGroup className="rate-demo__show-text">
      <Cell title="带描述评分" style={{ overflow: 'initial' }}>
        <Rate defaultValue={1} showText={true} texts={['很差', '差', '一般', '好评', '优秀']} />
      </Cell>
      <Cell title="带描述评分" style={{ overflow: 'initial' }}>
        <Rate defaultValue={5} showText={true} />
      </Cell>
      <Cell title="带描述评分" style={{ overflow: 'initial' }}>
        <Rate defaultValue={0} showText={true} />
      </Cell>
    </CellGroup>
  );
}

// skills/tdesign-mobile-vue/references/examples/rate/show-text.vue
<!--
  TDesign TDesign Mobile Vue 示例：rate - show-text
  覆盖组件：Rate
  来源：组件库源码 src/rate/demos/show-text.vue
-->

<template>
  <div class="rate-demo-cell rate-demo-cell--space">
    <div class="rate-demo-cell__label">带描述评分</div>
    <t-rate v-model="value1" show-text :texts="texts" variant="filled" />
  </div>
  <div class="rate-demo-cell rate-demo-cell--space">
    <div class="rate-demo-cell__label">带描述评分</div>
    <t-rate v-model="value2" show-text variant="filled" />
  </div>
  <div class="rate-demo-cell rate-demo-cell--space">
    <div class="rate-demo-cell__label">带描述评分</div>
    <t-rate v-model="value3" show-text variant="filled" />
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

const value1 = ref(3);
const value2 = ref(5);
const value3 = ref(0);
const texts = ref(['很差', '差', '一般', '好评', '优秀']);
</script>

<style lang="less" scoped>
.rate-demo-cell {
  background-color: var(--bg-color-demo, #fff);
  padding: 12px 16px;
  line-height: 1;
  display: flex;
  align-items: center;
  justify-content: space-between;
  &__label {
    font-size: 16px;
    margin-right: 16px;
    min-width: 80px;
    color: var(--td-text-color-primary, rgba(0, 0, 0, 0.9));
  }

  &--space {
    margin-bottom: 16px;
  }
}
</style>
