// skills/tdesign-react/references/examples/tag/custom-color.tsx
/**
 * TDesign TDesign React 示例：tag - custom-color
 * 覆盖组件：Tag
 * 来源：组件库源码 packages/components/tag/_example/custom-color.tsx
 */

import React, { useState } from 'react';
import { ColorPicker, Space, Tag } from 'tdesign-react';

export default function CustomColor() {
  const [selfDefinedColor, changeSelfDefinedColor] = useState('#0052D9');
  return (
    <Space direction="vertical">
      <Space>
        <ColorPicker colorModes={['monochrome']} value={selfDefinedColor} onChange={(v) => changeSelfDefinedColor(v)} />
      </Space>
      <Space>
        <Tag theme="primary" color={selfDefinedColor}>
          default
        </Tag>
        <Tag color={selfDefinedColor} variant="light">
          light
        </Tag>
        <Tag color={selfDefinedColor} variant="outline">
          outline
        </Tag>
        <Tag color={selfDefinedColor} variant="light-outline">
          light-outline
        </Tag>
      </Space>
    </Space>
  );
}

// skills/tdesign-vue2/references/examples/tag/custom-color.vue
<!--
  TDesign TDesign Vue 2 示例：tag - custom-color
  覆盖组件：Tag
  来源：组件库源码 src/tag/_example/custom-color.vue
-->

<template>
  <div>
    <p class="color-picker">
      <t-space align="center">
        <label>调整颜色查看效果</label>
        <t-color-picker :color-modes="['monochrome']" v-model="color"></t-color-picker>
      </t-space>
    </p>
    <t-space direction="horizontal">
      <t-space>
        <t-tag theme="primary" :color="color">默认</t-tag>
      </t-space>
      <t-space>
        <t-tag :color="color" variant="light">浅色</t-tag>
      </t-space>
      <t-space>
        <t-tag :color="color" variant="outline">outline</t-tag>
      </t-space>
      <t-space>
        <t-tag :color="color" variant="light-outline">light-outline</t-tag>
      </t-space>
    </t-space>
  </div>
</template>
<script>
export default {
  data() {
    return {
      color: 'rgb(0, 82, 217)',
    };
  },
};
</script>

<style lang="less" scoped>
.color-picker {
  margin-bottom: 20px;
}
</style>
