// skills/tdesign-vue2/references/examples/notification/operation.vue
<!--
  TDesign TDesign Vue 2 示例：notification - operation
  覆盖组件：Notification
  来源：组件库源码 src/notification/_example/operation.vue
-->

<template>
  <t-space direction="vertical" :size="24">
    <t-notification theme="info" title="超出的文本省略号显示" :content="content" :footer="footer" />
    <t-notification theme="info" title="带关闭按钮" content="这是一条消息通知" :close-btn="true" />
    <t-notification theme="info" title="消息通知标题" content="使用 function 自定义底部内容" :footer="footer2" />
    <t-notification v-if="visible" theme="info" content="1. 使用插槽自定义标题 2. 使用插槽自定义底部内容">
      <template #title>
        <div>消息通知标题 <small>消息通知副标题</small></div>
      </template>
      <template #footer>
        <div class="t-notification__detail">
          <t-button class="t-notification__detail-item" theme="default" variant="text">取消</t-button>
          <t-button class="t-notification__detail-item" theme="primary" variant="text" @click="remind">
            稍后提醒我(10s)
          </t-button>
        </div>
      </template>
    </t-notification>
  </t-space>
</template>

<script lang="jsx">
export default {
  data() {
    return {
      visible: true,
    };
  },
  methods: {
    footer() {
      return (
        <div slot="footer" class="t-notification__detail">
          <t-button class="t-notification__detail-item" theme="primary" variant="text">
            查看详情
          </t-button>
        </div>
      );
    },
    footer2() {
      return (
        <div slot="footer" class="t-notification__detail">
          <t-button class="t-notification__detail-item" theme="primary" variant="text">
            查看详情
          </t-button>
        </div>
      );
    },
    content() {
      return '文案不限长度，但在实际使用时建议文案显示内容不易过多，建议最大展示行数数量以三行为宜，最后一行折行末尾处超出文本建议会变为省略号显示。';
    },
    // title() {
    //   return (
    //     <div>
    //       自定义标题 <small>我是副标题</small>
    //     </div>
    //   );
    // },
    remind() {
      this.visible = false;
      setTimeout(() => {
        this.visible = true;
      }, 10000);
    },
  },
};
</script>

// skills/tdesign-react/references/examples/notification/operation.tsx
/**
 * TDesign TDesign React 示例：notification - operation
 * 覆盖组件：Notification
 * 来源：组件库源码 packages/components/notification/_example/operation.tsx
 */

import React from 'react';
import { Button, Notification, Space } from 'tdesign-react';

export default function NotificationExample() {
  return (
    <Space direction="vertical">
      <Notification
        theme="info"
        title="超出的文本省略号显示"
        content="文案不限长度，但是展示最大显示三行折行的末尾显示折行末尾显示折行末尾显示折行末尾显示折行末尾显示折行折行末尾显示折行折行末尾显示折行末尾显示折行折行末尾"
        footer={
          <div>
            <Button theme="primary" variant="text">
              查看详情
            </Button>
          </div>
        }
      />
      <Notification
        theme="info"
        title="自定义底部"
        content="使用 props function 自定义底部内容"
        footer={
          <div>
            <Button theme="primary" variant="text">
              查看详情
            </Button>
          </div>
        }
      />
      <Notification
        theme="info"
        content="1. 使用 props function 自定义标题；2. 使用插槽自定义底部内容"
        title={
          <div>
            自定义标题 <small>我是副标题</small>
          </div>
        }
        footer={
          <div slot="footer">
            <Button theme="default" variant="text">
              知道了
            </Button>
          </div>
        }
      />
      <Notification
        theme="info"
        content="1. 使用插槽自定义标题 2. 使用插槽自定义底部内容"
        title={
          <div>
            自定义标题 <small>我是副标题</small>
          </div>
        }
        footer={
          <div>
            <Button theme="default" variant="text">
              重启
            </Button>
            <Button theme="primary" variant="text">
              稍后提醒我(10s)
            </Button>
          </div>
        }
      />
      <Notification
        theme="info"
        title="自定义内容"
        content="使用插槽自定义内容"
        footer={
          <div>
            <Button theme="default" variant="text">
              重启
            </Button>
            <Button theme="primary" variant="text">
              更多
            </Button>
          </div>
        }
      ></Notification>
    </Space>
  );
}
