// skills/tdesign-vue2/references/examples/notification/toggle.vue
<!--
  TDesign TDesign Vue 2 示例：notification - toggle
  覆盖组件：Notification
  来源：组件库源码 src/notification/_example/toggle.vue
-->

<template>
  <t-space>
    <t-button variant="outline" @click="toggle">自由控制关闭时机（{{ notification ? '关闭' : '打开' }}）</t-button>
  </t-space>
</template>

<script>
export default {
  data() {
    return {
      notification: null,
    };
  },
  methods: {
    toggle() {
      if (!this.notification) {
        this.notification = this.$notify.info({
          title: '标题名称',
          content: '这是一条需要手动关闭的消息通知',
          duration: 0,
        });
      } else {
        // this.notification.then(ins => ins.close()); // 另一种关闭方法
        this.$notify.close(this.notification);
        this.notification = null;
      }
    },
  },
};
</script>

<style scoped>
.t-button + .t-button {
  margin-left: 16px;
}
</style>

// skills/tdesign-react/references/examples/notification/toggle.tsx
/**
 * TDesign TDesign React 示例：notification - toggle
 * 覆盖组件：Notification
 * 来源：组件库源码 packages/components/notification/_example/toggle.tsx
 */

import React from 'react';
import { Button, NotificationPlugin } from 'tdesign-react';

export default function NotificationExample() {
  const openNotification = () => {
    const notification = NotificationPlugin.info({
      title: '信息',
      content: '这是一条不会自动关闭的消息通知',
      closeBtn: true,
      duration: 0,
      onCloseBtnClick: () => {
        NotificationPlugin.close(notification);
      },
    });
  };

  return <Button onClick={openNotification}>自由控制关闭时机</Button>;
}
