// skills/tdesign-react/references/examples/pagination/mini.tsx
/**
 * TDesign TDesign React 示例：pagination - mini
 * 覆盖组件：Pagination
 * 来源：组件库源码 packages/components/pagination/_example/mini.tsx
 */

import React from 'react';
import { Pagination } from 'tdesign-react';

export default function PaginationExample() {
  return <Pagination size="small" total={100} defaultPageSize={5} />;
}

// skills/tdesign-vue-next/references/examples/pagination/mini.vue
<!--
  TDesign TDesign Vue Next 示例：pagination - mini
  覆盖组件：Pagination
  来源：组件库源码 packages/components/pagination/_example/mini.vue
-->

<template>
  <t-pagination
    v-model:pageSize="pageSize"
    :total="100"
    size="small"
    @change="onChange"
    @page-size-change="onPageSizeChange"
    @current-change="onCurrentChange"
  />
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { MessagePlugin } from 'tdesign-vue-next';
import type { PaginationProps } from 'tdesign-vue-next';

const pageSize = ref(5);
const onPageSizeChange: PaginationProps['onPageSizeChange'] = (size) => {
  console.log('page-size:', size);
  MessagePlugin.success(`pageSize变化为${size}`);
};
const onCurrentChange: PaginationProps['onCurrentChange'] = (index, pageInfo) => {
  MessagePlugin.success(`转到第${index}页`);
  console.log(pageInfo);
};
const onChange: PaginationProps['onChange'] = (pageInfo) => {
  console.log(pageInfo);
};
</script>
