// skills/tdesign-react/references/examples/pagination/pagination-mini.tsx
/**
 * TDesign TDesign React 示例：pagination - pagination-mini
 * 覆盖组件：Pagination
 * 来源：组件库源码 packages/components/pagination/_example/pagination-mini.tsx
 */

import React, { useState } from 'react';
import { PaginationMini, Radio, Space } from 'tdesign-react';

import type { PaginationMiniProps } from 'tdesign-react';

type LayoutType = PaginationMiniProps['layout'];
type SizeType = PaginationMiniProps['size'];

export default function DemoPaginationMini() {
  const [layout, setLayout] = useState<LayoutType>('vertical');
  const [size, setSize] = useState<SizeType>('medium');

  const tips = { prev: '前尘忆梦', current: '回到现在', next: '展望未来' };

  return (
    <Space direction="vertical" size={16}>
      <Space align="center">
        <span>layout:</span>
        <Radio.Group value={layout} onChange={(val: LayoutType) => setLayout(val)} variant="default-filled">
          <Radio.Button value="vertical">vertical</Radio.Button>
          <Radio.Button value="horizontal">horizontal</Radio.Button>
        </Radio.Group>
      </Space>
      <Space align="center">
        <span>size:</span>
        <Radio.Group value={size} onChange={(val: SizeType) => setSize(val)} variant="default-filled">
          <Radio.Button value="small">small</Radio.Button>
          <Radio.Button value="medium">medium</Radio.Button>
          <Radio.Button value="large">large</Radio.Button>
        </Radio.Group>
      </Space>
      <PaginationMini layout={layout} size={size} tips={tips} />
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/pagination/pagination-mini.vue
<!--
  TDesign TDesign Vue Next 示例：pagination - pagination-mini
  覆盖组件：Pagination
  来源：组件库源码 packages/components/pagination/_example/pagination-mini.vue
-->

<template>
  <t-space direction="vertical" :size="16">
    <t-space align="center">
      <span>layout:</span>
      <t-radio-group v-model="layout" variant="default-filled">
        <t-radio-button value="vertical">vertical</t-radio-button>
        <t-radio-button value="horizontal">horizontal</t-radio-button>
      </t-radio-group>
    </t-space>
    <t-space align="center">
      <span>size:</span>
      <t-radio-group v-model="size" variant="default-filled">
        <t-radio-button value="small">small</t-radio-button>
        <t-radio-button value="medium">medium</t-radio-button>
        <t-radio-button value="large">large</t-radio-button>
      </t-radio-group>
    </t-space>
    <t-pagination-mini :layout="layout" :size="size" :tips="tips" />
  </t-space>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import type { PaginationMiniProps } from 'tdesign-vue-next';

const layout = ref<PaginationMiniProps['layout']>('vertical');
const size = ref<PaginationMiniProps['size']>('medium');
const tips = ref<PaginationMiniProps['tips']>({
  prev: '前尘忆梦',
  current: '回到现在',
  next: '展望未来',
});
</script>
