// skills/tdesign-vue2/references/examples/color-picker/recent-color.vue
<!--
  TDesign TDesign Vue 2 示例：color-picker - recent-color
  覆盖组件：Color-picker
  来源：组件库源码 src/color-picker/_example/recent-color.vue
-->

<template>
  <t-space>
    <t-space direction="vertical" size="10px">
      <h6>预设最近使用色</h6>
      <t-color-picker-panel
        v-model="color"
        :recent-colors="[
          'red',
          'green',
          'yellow',
          'blue',
          'purple',
          'linear-gradient(to right, #fa709a 0%, #fee140 100%)',
          'linear-gradient(45deg, #eea2a2 0%, #bbc1bf 19%, #57c6e1 42%, #b49fda 79%, #7ac5d8 100%)',
          'linear-gradient(120deg, #fcc5e4 0%, #fda34b 15%, #ff7882 35%, #c8699e 52%, #7046aa 71%, #0c1db8 87%, #020f75 100%)',
        ]"
      />
    </t-space>
    <t-space direction="vertical" size="10px">
      <h6>完全不显示最近使用色</h6>
      <t-color-picker-panel v-model="color" :recent-colors="null" />
    </t-space>
  </t-space>
</template>
<script>
export default {
  data() {
    return {
      color: 'red',
    };
  },
};
</script>

// skills/tdesign-react/references/examples/color-picker/recent-color.tsx
/**
 * TDesign TDesign React 示例：color-picker - recent-color
 * 覆盖组件：Color-picker
 * 来源：组件库源码 packages/components/color-picker/_example/recent-color.tsx
 */

import React, { useState } from 'react';
import { ColorPickerPanel, Space } from 'tdesign-react';

export default function RecentColor() {
  const color = '#0052d9';
  const [recentColors, setRecentColors] = useState([
    '#f00',
    '#008000',
    '#ffff00',
    '#0000ff',
    '#800080',
    'linear-gradient(to right, #fa709a 0%, #fee140 100%)',
    'linear-gradient(45deg, #eea2a2 0%, #bbc1bf 19%, #57c6e1 42%, #b49fda 79%, #7ac5d8 100%)',
    'linear-gradient(120deg, #fcc5e4 0%, #fda34b 15%, #ff7882 35%, #c8699e 52%, #7046aa 71%, #0c1db8 87%, #020f75 100%)',
  ]);

  return (
    <Space>
      <div>
        <h6 style={{ marginBottom: 10 }}>预设最近使用色</h6>
        <ColorPickerPanel defaultValue={color} recentColors={recentColors} onRecentColorsChange={setRecentColors} />
      </div>
      <div>
        <h6 style={{ marginBottom: 10 }}>完全不显示最近使用色</h6>
        <ColorPickerPanel defaultValue={color} recentColors={null} />
      </div>
    </Space>
  );
}
