// skills/tdesign-vue-next/references/examples/select-input/autowidth.vue
<!--
  TDesign TDesign Vue Next 示例：select-input - autowidth
  覆盖组件：Select-input
  来源：组件库源码 packages/components/select-input/_example/autowidth.vue
-->

<template>
  <!-- :popup-props="{ trigger: 'hover' }" -->
  <t-select-input
    :value="selectValue"
    :popup-visible="popupVisible"
    placeholder="Please Select"
    clearable
    auto-width
    allow-input
    @popup-visible-change="onPopupVisibleChange"
    @clear="onClear"
    @input-change="onInputChange"
  >
    <template #panel>
      <ul class="tdesign-demo__select-input-ul-auto-width">
        <li v-for="item in options" :key="item.value" @click="() => onOptionClick(item)">
          {{ item.label }}
        </li>
      </ul>
    </template>
    <template #suffixIcon>
      <chevron-down-icon />
    </template>
  </t-select-input>
</template>
<script lang="ts" setup>
import { ref } from 'vue';
import { ChevronDownIcon } from 'tdesign-icons-vue-next';
import type { SelectInputProps } from 'tdesign-vue-next';

const options = [
  {
    label: 'tdesign',
    value: 1,
  },
  {
    label: 'tdesign-react',
    value: 2,
  },
  {
    label: 'tdesign-vue',
    value: 3,
  },
  // { label: 'tdesign-angular', value: 4 },
  // { label: 'tdesign-mobile-vue', value: 5 },
  // { label: 'tdesign-mobile-react', value: 6 },
];

// const selectValue = ref('tdesign-vue');
const selectValue = ref<{
  label: string;
  value: number;
}>({
  label: 'tdesign-vue',
  value: 1,
});
// const selectValue = ref([{ label: 'tdesign-vue', value: 1 }]);
const popupVisible = ref(false);
const onOptionClick = (item: { label: string; value: number }) => {
  selectValue.value = item;
  // 选中后立即关闭浮层
  popupVisible.value = false;
};
const onClear: SelectInputProps['onClear'] = () => {
  selectValue.value = undefined;
};
const onPopupVisibleChange: SelectInputProps['onPopupVisibleChange'] = (val, context) => {
  console.log(context);
  popupVisible.value = val;
};
const onInputChange: SelectInputProps['onInputChange'] = (val, context) => {
  // 过滤功能
  console.log(val, context);
};
</script>
<style>
.tdesign-demo__select-input-ul-auto-width {
  padding: 2px 0;
  margin: 0 -2px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.tdesign-demo__select-input-ul-auto-width > li {
  display: block;
  border-radius: 3px;
  line-height: 22px;
  cursor: pointer;
  padding: 3px 8px;
  color: var(--td-text-color-primary);
  transition: background-color 0.2s linear;
  white-space: nowrap;
  word-wrap: normal;
  overflow: hidden;
  text-overflow: ellipsis;
}

.tdesign-demo__select-input-ul-auto-width > li:hover {
  background-color: var(--td-bg-color-container-hover);
}
</style>

// skills/tdesign-react/references/examples/select-input/autowidth.tsx
/**
 * TDesign TDesign React 示例：select-input - autowidth
 * 覆盖组件：Select-input
 * 来源：组件库源码 packages/components/select-input/_example/autowidth.tsx
 */

import React, { useEffect, useState } from 'react';
import { ChevronDownIcon } from 'tdesign-icons-react';
import { SelectInput } from 'tdesign-react';

import type { SelectInputValueChangeContext } from 'tdesign-react';

const classStyles = `
<style>
.tdesign-demo__select-input-ul-auto-width {
  padding: 2px 0;
  margin: 0 -2px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.tdesign-demo__select-input-ul-auto-width > li {
  display: block;
  border-radius: 3px;
  line-height: 22px;
  cursor: pointer;
  padding: 3px 8px;
  color: var(--td-text-color-primary);
  transition: background-color 0.2s linear;
  white-space: nowrap;
  word-wrap: normal;
  overflow: hidden;
  text-overflow: ellipsis;
}

.tdesign-demo__select-input-ul-auto-width > li:hover {
  background-color: var(--td-bg-color-container-hover);
}
</style>
`;

const OPTIONS = [
  { label: 'tdesign-vue', value: 1 },
  { label: 'tdesign-react', value: 2 },
  { label: 'tdesign-miniprogram', value: 3 },
  { label: 'tdesign-angular', value: 4 },
  { label: 'tdesign-mobile-vue', value: 5 },
  { label: 'tdesign-mobile-react', value: 6 },
];

export default function SelectInputAutocomplete() {
  const [popupVisible, setPopupVisible] = useState(false);
  const [selectValue, setSelectValue] = useState({ label: 'tdesign-vue', value: 1 });

  const onOptionClick = (item: { label: string; value: number }) => {
    setSelectValue(item);
    setPopupVisible(false);
  };

  const onClear = () => {
    setSelectValue(undefined);
  };

  const onPopupVisibleChange = (val: boolean) => {
    setPopupVisible(val);
  };

  const onInputChange = (val: string, context: SelectInputValueChangeContext) => {
    // 过滤功能
    console.log(val, context);
  };

  useEffect(() => {
    // 添加示例代码所需样式
    document.head.insertAdjacentHTML('beforeend', classStyles);
  }, []);

  // 如果需要输入框宽度自适应，可以使用 autoWidth
  return (
    <SelectInput
      value={selectValue}
      popupVisible={popupVisible}
      placeholder="Please Select"
      clearable
      autoWidth
      allowInput
      onPopupVisibleChange={onPopupVisibleChange}
      onClear={onClear}
      onInputChange={onInputChange}
      suffixIcon={<ChevronDownIcon />}
      panel={
        <ul className="tdesign-demo__select-input-ul-auto-width">
          {OPTIONS.map((item) => (
            <li key={item.value} onClick={() => onOptionClick(item)}>
              {item.label}
            </li>
          ))}
        </ul>
      }
    />
  );
}
