// skills/tdesign-vue-next/references/examples/select-input/multiple.vue
<!--
  TDesign TDesign Vue Next 示例：select-input - multiple
  覆盖组件：Select-input
  来源：组件库源码 packages/components/select-input/_example/multiple.vue
-->

<template>
  <t-space direction="vertical" class="tdesign-demo__select-input-multiple" style="width: 100%">
    <div>
      <t-checkbox v-model="allowInput">是否允许输入</t-checkbox>
      <t-checkbox v-model="creatable">允许创建新选项（Enter 创建）</t-checkbox>
    </div>
    <div>
      <t-radio-group
        v-model="excessTagsDisplayType"
        :options="[
          { label: '选中项过多横向滚动', value: 'scroll' },
          { label: '选中项过多换行显示', value: 'break-line' },
        ]"
      />
    </div>

    <!-- :popup-props="{ trigger: 'hover' }" -->
    <t-select-input
      v-model:inputValue="inputValue"
      :value="value"
      :allow-input="allowInput"
      :placeholder="allowInput ? '请选择或输入' : '请选择'"
      :tag-input-props="{ excessTagsDisplayType }"
      :popup-props="popupProps"
      clearable
      multiple
      @tag-change="onTagChange"
      @input-change="onInputChange"
    >
      <template #panel>
        <t-checkbox-group
          v-if="options.length"
          :value="checkboxValue"
          :options="options"
          class="tdesign-demo__panel-options-multiple"
          @change="onCheckedChange"
        />
        <div v-else class="tdesign-demo__select-empty-multiple">暂无数据</div>
      </template>
      <template #suffixIcon>
        <chevron-down-icon />
      </template>
    </t-select-input>
  </t-space>
</template>
<script lang="ts" setup>
import { computed, ref } from 'vue';
import { ChevronDownIcon } from 'tdesign-icons-vue-next';
import type { SelectInputProps, CheckboxGroupProps } from 'tdesign-vue-next';

interface CustomOptionInfo {
  label: string;
  value?: number;
  checkAll?: boolean;
}
const OPTIONS: CustomOptionInfo[] = [
  // 全选
  {
    label: 'Check All',
    checkAll: true,
  },
  {
    label: 'tdesign-vue',
    value: 1,
  },
  {
    label: 'tdesign-react',
    value: 2,
  },
  {
    label: 'tdesign-miniprogram',
    value: 3,
  },
  {
    label: 'tdesign-angular',
    value: 4,
  },
  {
    label: 'tdesign-mobile-vue',
    value: 5,
  },
  {
    label: 'tdesign-mobile-react',
    value: 6,
  },
];
const excessTagsDisplayType = ref('break-line');
const allowInput = ref(true);
const creatable = ref(true);
const inputValue = ref('');
// 全量数据
const options = ref<CustomOptionInfo[]>([...OPTIONS]);
const value = ref<CustomOptionInfo[]>([
  {
    label: 'Vue',
    value: 1,
  },
  {
    label: 'React',
    value: 2,
  },
  {
    label: 'Miniprogram',
    value: 3,
  },
]);
const popupProps = ref<SelectInputProps['popupProps']>({
  overlayInnerClassName: ['narrow-scrollbar'],
  overlayInnerStyle: {
    maxHeight: '280px',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    padding: '6px',
  },
});
const checkboxValue = computed<CheckboxGroupProps['value']>(() => {
  const arr = [];
  const list = value.value;
  // 此处不使用 forEach，减少函数迭代
  for (let i = 0, len = list.length; i < len; i++) {
    list[i].value && arr.push(list[i].value);
  }
  return arr;
});

// 直接 checkboxgroup 组件渲染输出下拉选项
const onCheckedChange: CheckboxGroupProps['onChange'] = (val, { current, type }) => {
  console.log(current);
  // current 不存在，则表示操作全选
  if (!current) {
    value.value =
      type === 'check'
        ? options.value.slice(1).map((option) => ({
            ...option,
            value: option?.value || 0,
          }))
        : [];
    return;
  }
  // 普通操作
  if (type === 'check') {
    const option = options.value.find((t) => t.value === current);
    value.value.push(option);
  } else {
    value.value = value.value.filter((v) => v.value !== current);
  }
};

// 可以根据触发来源，自由定制标签变化时的筛选器行为
const onTagChange: SelectInputProps['onTagChange'] = (currentTags, context) => {
  console.log(currentTags, context);
  const { trigger, index, item } = context;
  if (trigger === 'clear') {
    value.value = [];
  }
  if (['tag-remove', 'backspace'].includes(trigger)) {
    value.value.splice(index, 1);
  }
  // 如果允许创建新条目
  if (creatable.value && trigger === 'enter') {
    const current = {
      label: item.toString(),
      value: Number(item) || index,
    };
    value.value.push(current);
    const newOptions = options.value.concat(current);
    options.value = newOptions;
    inputValue.value = '';
  }
};
const onInputChange: SelectInputProps['onInputChange'] = (val, context) => {
  console.log(val, context);
};
</script>
<style>
.tdesign-demo__panel-options-multiple {
  width: 100%;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.tdesign-demo__panel-options-multiple .t-checkbox {
  display: flex;
  border-radius: 3px;
  line-height: 22px;
  cursor: pointer;
  padding: 3px 8px;
  color: var(--td-text-color-primary);
  transition: background-color 0.2s linear;
  white-space: nowrap;
  word-wrap: normal;
  overflow: hidden;
  text-overflow: ellipsis;
  margin: 0;
}
.tdesign-demo__panel-options-multiple .t-checkbox:hover {
  background-color: var(--td-bg-color-container-hover);
}
</style>

// skills/tdesign-react/references/examples/select-input/multiple.tsx
/**
 * TDesign TDesign React 示例：select-input - multiple
 * 覆盖组件：Select-input
 * 来源：组件库源码 packages/components/select-input/_example/multiple.tsx
 */

import React, { useEffect, useState } from 'react';
import { ChevronDownIcon } from 'tdesign-icons-react';
import { Checkbox, Radio, SelectInput } from 'tdesign-react';

import type { CheckboxGroupProps, CheckboxOptionObj, SelectInputProps } from 'tdesign-react';

const classStyles = `
<style>
.tdesign-demo__panel-options-multiple {
  width: 100%;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.tdesign-demo__panel-options-multiple .t-checkbox {
  display: flex;
  border-radius: 3px;
  line-height: 22px;
  cursor: pointer;
  padding: 3px 8px;
  color: var(--td-text-color-primary);
  transition: background-color 0.2s linear;
  white-space: nowrap;
  word-wrap: normal;
  overflow: hidden;
  text-overflow: ellipsis;
  margin: 0;
}
.tdesign-demo__panel-options-multiple .t-checkbox:hover {
  background-color: var(--td-bg-color-container-hover);
}
</style>
`;

const OPTIONS: CheckboxOptionObj[] = [
  // 全选
  { label: 'Check All', checkAll: true },
  { label: 'tdesign-vue', value: 1 },
  { label: 'tdesign-react', value: 2 },
  { label: 'tdesign-miniprogram', value: 3 },
  { label: 'tdesign-angular', value: 4 },
  { label: 'tdesign-mobile-vue', value: 5 },
  { label: 'tdesign-mobile-react', value: 6 },
];

type ExcessTagsDisplayType = SelectInputProps['tagInputProps']['excessTagsDisplayType'];

export default function SelectInputMultiple() {
  const [excessTagsDisplayType, setExcessTagsDisplayType] = useState<ExcessTagsDisplayType>('break-line');
  const [allowInput, setAllowInput] = useState(true);
  const [creatable, setCreatable] = useState(true);
  const [inputValue, setInputValue] = useState('');
  // 全量数据
  const [options, setOptions] = useState([...OPTIONS]);
  // 仅用作展示的数据（过滤功能需要使用）
  const [displayOptions, setDisplayOptions] = useState([...OPTIONS]);
  const [value, setValue] = useState<Array<any>>([
    { label: 'Vue', value: 1 },
    { label: 'React', value: 2 },
    { label: 'Miniprogram', value: 3 },
  ]);

  const getCheckboxValue = () => {
    const arr = [];
    const list = value;
    // 此处不使用 forEach，减少函数迭代
    for (let i = 0, len = list.length; i < len; i++) {
      list[i].value && arr.push(list[i].value);
    }
    return arr;
  };

  const checkboxValue = getCheckboxValue();

  // 直接 checkboxgroup 组件渲染输出下拉选项，自定义处理可以避免顺序和 tagChange 冲突
  const onCheckedChange: CheckboxGroupProps['onChange'] = (val, { current, type }) => {
    // current 不存在，则表示操作全选
    if (!current) {
      const newValue = type === 'check' ? options.slice(1) : [];
      setValue(newValue);
      return;
    }
    // 普通操作
    if (type === 'check') {
      const option = options.find((t) => t.value === current);
      setValue(value.concat(option));
    } else {
      const newValue = value.filter((v) => v.value !== current);
      setValue(newValue);
    }
  };

  // 可以根据触发来源，自由定制标签变化时的筛选器行为
  const onTagChange: SelectInputProps['onTagChange'] = (currentTags, context) => {
    const { trigger, index } = context;
    if (trigger === 'clear') {
      setValue([]);
    }
    if (['tag-remove', 'backspace'].includes(trigger)) {
      const newValue = [...value];
      newValue.splice(index, 1);
      setValue(newValue);
    }
  };

  const onInputChange: SelectInputProps['onInputChange'] = (val, context) => {
    setInputValue(val);
    // 过滤功能
    console.log(val, context);
  };

  useEffect(() => {
    // 添加示例代码所需样式
    document.head.insertAdjacentHTML('beforeend', classStyles);
  }, []);

  const onInputEnter: SelectInputProps['onEnter'] = (_, { inputValue }) => {
    // 如果允许创建新条目
    if (creatable) {
      const current = { label: inputValue, value: inputValue };
      const newValue = [...value];
      setValue(newValue.concat(current));
      const newOptions = options.concat(current);
      setOptions(newOptions);
      setDisplayOptions(newOptions);
      setInputValue('');
    }
  };

  return (
    <div className="tdesign-demo__select-input-multiple" style={{ width: '100%' }}>
      <div>
        <Checkbox checked={allowInput} onChange={setAllowInput}>
          是否允许输入
        </Checkbox>
        <Checkbox checked={creatable} onChange={setCreatable}>
          允许创建新选项（Enter 创建）
        </Checkbox>
      </div>
      <br />
      <div>
        <Radio.Group
          value={excessTagsDisplayType}
          onChange={(val: ExcessTagsDisplayType) => setExcessTagsDisplayType(val)}
          options={[
            { label: '选中项过多横向滚动', value: 'scroll' },
            { label: '选中项过多换行显示', value: 'break-line' },
          ]}
        />
      </div>
      <br />
      <br />

      {/* <!-- :popup-props="{ trigger: 'hover' }" --> */}
      <SelectInput
        value={value}
        allowInput={allowInput}
        inputValue={inputValue}
        placeholder={allowInput ? '请选择或输入' : '请选择'}
        tagInputProps={{ excessTagsDisplayType }}
        popupProps={{ overlayStyle: { maxHeight: '280px', overflow: 'auto' } }}
        // label={<span>多选：</span>}
        panel={
          displayOptions.length ? (
            <Checkbox.Group
              value={checkboxValue}
              options={displayOptions}
              className="tdesign-demo__panel-options-multiple"
              onChange={onCheckedChange}
            />
          ) : (
            <div className="tdesign-demo__select-empty-multiple">暂无数据</div>
          )
        }
        suffixIcon={<ChevronDownIcon />}
        clearable
        multiple
        onTagChange={onTagChange}
        onInputChange={onInputChange}
        onEnter={onInputEnter}
      />
    </div>
  );
}
