// skills/tdesign-vue-next/references/examples/select-input/status.vue
<!--
  TDesign TDesign Vue Next 示例：select-input - status
  覆盖组件：Select-input
  来源：组件库源码 packages/components/select-input/_example/status.vue
-->

<template>
  <t-space direction="vertical" class="tdesign-demo-select-input-status" style="width: 100%">
    <t-space align="center">
      <span>禁用状态：</span>
      <t-select-input :value="selectValue" disabled tips="这是禁用状态文本提示" placeholder="Please Select">
        <template #panel>
          <div class="tdesign-demo__select-empty-status">暂无数据</div>
        </template>
      </t-select-input>
    </t-space>

    <t-space align="center">
      <span>只读状态：</span>
      <t-select-input :value="selectValue" readonly tips="这是普通状态的文本提示" placeholder="Please Select">
        <template #panel>
          <div class="tdesign-demo__select-empty-status">暂无数据</div>
        </template>
      </t-select-input>
    </t-space>

    <t-space align="center">
      <span>成功状态：</span>
      <t-select-input :value="selectValue" status="success" tips="校验通过文本提示" placeholder="Please Select">
        <template #panel>
          <div class="tdesign-demo__select-empty-status">暂无数据</div>
        </template>
      </t-select-input>
    </t-space>

    <t-space align="center">
      <span>警告状态：</span>
      <t-select-input :value="selectValue" status="warning" tips="校验不通过文本提示" placeholder="Please Select">
        <template #panel>
          <div class="tdesign-demo__select-empty-status">暂无数据</div>
        </template>
      </t-select-input>
    </t-space>

    <t-space align="center">
      <span>错误状态：</span>
      <t-select-input :value="selectValue" status="error" tips="校验存在严重问题文本提示" placeholder="Please Select">
        <template #panel>
          <div class="tdesign-demo__select-empty-status">暂无数据</div>
        </template>
      </t-select-input>
    </t-space>
  </t-space>
</template>
<script lang="ts" setup>
import type { SelectInputProps } from 'tdesign-vue-next';

const selectValue: SelectInputProps['value'] = 'TDesign';
</script>
<style>
.tdesign-demo__select-empty-status {
  text-align: center;
  color: var(--td-text-color-disabled);
  line-height: 32px;
}
.tdesign-demo-select-input-status > div {
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}

.tdesign-demo-select-input-status .t-select-input__wrap {
  width: 300px;
  height: 32px;
}
</style>

// skills/tdesign-react/references/examples/select-input/status.tsx
/**
 * TDesign TDesign React 示例：select-input - status
 * 覆盖组件：Select-input
 * 来源：组件库源码 packages/components/select-input/_example/status.tsx
 */

import React, { useEffect } from 'react';
import { SelectInput, Space } from 'tdesign-react';

const classStyles = `
<style>
.tdesign-demo__select-empty-status {
  text-align: center;
  color: var(--td-text-color-disabled);
  line-height: 32px;
}
.tdesign-demo-select-input-status > div {
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}

.tdesign-demo-select-input-status .t-select-input__wrap {
  width: 300px;
  height: 32px;
}
</style>
`;

const SelectInputStatus = () => {
  const selectValue = 'TDesign';

  useEffect(() => {
    // 添加示例代码所需样式
    document.head.insertAdjacentHTML('beforeend', classStyles);
  }, []);

  return (
    <Space direction="vertical" size={32}>
      <Space>
        <span>禁用状态：</span>
        <SelectInput
          value={selectValue}
          disabled
          placeholder="Please Select"
          tips="这是禁用状态的文本"
          panel={<div className="tdesign-demo__select-empty">暂无数据</div>}
        />
      </Space>

      <Space>
        <span>只读状态：</span>
        <SelectInput
          value={selectValue}
          readonly
          placeholder="Please Select"
          tips="这是只读状态的文本提示"
          panel={<div className="tdesign-demo__select-empty-status">暂无数据</div>}
        />
      </Space>

      <Space>
        <span>成功状态：</span>
        <SelectInput
          value={selectValue}
          status="success"
          tips="校验通过文本提示"
          placeholder="Please Select"
          panel={<div className="tdesign-demo__select-empty-status">暂无数据</div>}
        />
      </Space>

      <Space>
        <span>警告状态：</span>
        <SelectInput
          value={selectValue}
          status="warning"
          tips="校验不通过文本提示"
          placeholder="Please Select"
          panel={<div className="tdesign-demo__select-empty-status">暂无数据</div>}
        />
      </Space>

      <Space>
        <span>错误状态：</span>
        <SelectInput
          value={selectValue}
          status="error"
          tips="校验存在严重问题文本提示"
          placeholder="Please Select"
          panel={<div className="tdesign-demo__select-empty-status">暂无数据</div>}
        />
      </Space>

      <Space>
        <span>加载状态：</span>
        <SelectInput
          loading={true}
          tips="处于加载状态的文本提示"
          placeholder="Please Select"
          panel={<div className="tdesign-demo__select-empty-status">加载中...</div>}
        />
      </Space>
    </Space>
  );
};

SelectInputStatus.displayName = 'SelectInputStatus';

export default SelectInputStatus;
