// skills/tdesign-react/references/examples/select-input/label-suffix.tsx
/**
 * TDesign TDesign React 示例：select-input - label-suffix
 * 覆盖组件：Select-input
 * 来源：组件库源码 packages/components/select-input/_example/label-suffix.tsx
 */

import React, { useEffect, useState } from 'react';
import { ChevronDownIcon } from 'tdesign-icons-react';
import { SelectInput } from 'tdesign-react';

import type { PopupVisibleChangeContext } from 'tdesign-react';

const classStyles = `

<style>
.tdesign-demo__select-input-ul-label-suffix {
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.tdesign-demo__select-input-ul-label-suffix > li {
  display: block;
  border-radius: 3px;
  line-height: 22px;
  cursor: pointer;
  padding: 3px 8px;
  color: var(--td-text-color-primary);
  transition: background-color 0.2s linear;
  white-space: nowrap;
  word-wrap: normal;
  overflow: hidden;
  text-overflow: ellipsis;
}

.tdesign-demo__select-input-ul-label-suffix > li:hover {
  background-color: var(--td-bg-color-container-hover);
}
</style>
`;

const OPTIONS = [
  { label: 'tdesign-vue', value: 1 },
  { label: 'tdesign-react', value: 2 },
  { label: 'tdesign-miniprogram', value: 3 },
  { label: 'tdesign-angular', value: 4 },
  { label: 'tdesign-mobile-vue', value: 5 },
  { label: 'tdesign-mobile-react', value: 6 },
];

export default function SelectInputSingle() {
  // const selectValue = useState('tdesign-vue');
  const [selectValue, setSelectValue] = useState({ label: 'tdesign-vue', value: 1 });
  // const selectValue = useState([{ label: 'tdesign-vue', value: 1 }]);

  const [popupVisible, setPopupVisible] = useState(false);
  const [popupVisible2, setPopupVisible2] = useState(false);

  const onOptionClick = (item: { label: string; value: number }) => {
    setSelectValue(item);
    // 选中后立即关闭浮层
    setPopupVisible(false);
    setPopupVisible2(false);
  };

  const onClear = () => {
    setSelectValue(undefined);
  };

  const onPopupVisibleChange = (val: boolean, context: PopupVisibleChangeContext) => {
    console.log(context);
    setPopupVisible(val);
  };

  const onPopupVisibleChange2 = (val: boolean) => {
    setPopupVisible2(val);
  };

  useEffect(() => {
    // 添加示例代码所需样式
    document.head.insertAdjacentHTML('beforeend', classStyles);
  }, []);

  return (
    <div>
      {/* <!-- :popup-props="{ trigger: 'hover' }" --> */}
      <SelectInput
        value={selectValue}
        popupVisible={popupVisible}
        style={{ width: '300px' }}
        label={<span>前置内容：</span>}
        placeholder="Please Select"
        clearable
        popupProps={{ overlayInnerStyle: { padding: 6 } }}
        onPopupVisibleChange={onPopupVisibleChange}
        onClear={onClear}
        panel={
          <ul className="tdesign-demo__select-input-ul-label-suffix">
            {OPTIONS.map((item) => (
              <li key={item.value} onClick={() => onOptionClick(item)}>
                {item.label}
              </li>
            ))}
          </ul>
        }
        suffixIcon={<ChevronDownIcon />}
      />
      <br /> <br />
      <SelectInput
        value={selectValue}
        popupVisible={popupVisible2}
        style={{ width: '300px' }}
        suffix={<span>单位：元</span>}
        placeholder="Please Select"
        clearable
        popupProps={{ overlayInnerStyle: { padding: 6 } }}
        onPopupVisibleChange={onPopupVisibleChange2}
        onClear={onClear}
        panel={
          <ul className="tdesign-demo__select-input-ul-label-suffix">
            {OPTIONS.map((item) => (
              <li key={item.value} onClick={() => onOptionClick(item)}>
                {item.label}
              </li>
            ))}
          </ul>
        }
        suffixIcon={<ChevronDownIcon />}
      />
    </div>
  );
}

// skills/tdesign-vue2/references/examples/select-input/label-suffix.vue
<!--
  TDesign TDesign Vue 2 示例：select-input - label-suffix
  覆盖组件：Select-input
  来源：组件库源码 src/select-input/_example/label-suffix.vue
-->

<template>
  <t-space direction="vertical">
    <!-- :popup-props="{ trigger: 'hover' }" -->
    <!-- 前置内容使用 label 自定义，支持同名插槽 label -->
    <t-select-input
      :value="selectValue"
      :popup-visible="popupVisible"
      :popup-props="{ overlayInnerStyle: { padding: '6px' } }"
      label="前置内容："
      style="width: 300px"
      placeholder="Please Select"
      clearable
      @popup-visible-change="onPopupVisibleChange"
      @clear="onClear"
    >
      <template #panel>
        <ul class="tdesign-demo__select-input-ul-label-suffix">
          <li v-for="item in options" :key="item.value" @click="() => onOptionClick(item)">
            {{ item.label }}
          </li>
        </ul>
      </template>
      <!-- 后置图标 -->
      <template #suffixIcon>
        <chevron-down-icon />
      </template>
    </t-select-input>
    <br /><br />

    <!-- 后置内容使用 suffix 自定义，支持同名插槽 suffix -->
    <t-select-input
      :value="selectValue"
      :popup-visible="popupVisible2"
      :popup-props="{ overlayInnerStyle: { padding: '6px' } }"
      suffix="单位：元"
      style="width: 300px"
      placeholder="Please Select"
      clearable
      @popup-visible-change="onPopupVisibleChange2"
      @clear="onClear"
    >
      <template #panel>
        <ul class="tdesign-demo__select-input-ul-label-suffix">
          <li v-for="item in options" :key="item.value" @click="() => onOptionClick(item)">
            {{ item.label }}
          </li>
        </ul>
      </template>
      <template #suffixIcon>
        <chevron-down-icon />
      </template>
    </t-select-input>
  </t-space>
</template>
<script>
import { ChevronDownIcon } from 'tdesign-icons-vue';

const initialOptions = [
  // 全选
  { label: 'Check All', checkAll: true },
  { label: 'tdesign-vue', value: 1 },
  { label: 'tdesign-react', value: 2 },
  { label: 'tdesign-miniprogram', value: 3 },
  { label: 'tdesign-angular', value: 4 },
  { label: 'tdesign-mobile-vue', value: 5 },
  { label: 'tdesign-mobile-react', value: 6 },
];

export default {
  components: {
    ChevronDownIcon,
  },
  data() {
    return {
      options: initialOptions,
      selectValue: { label: 'tdesign-vue', value: 1 },
      popupVisible: false,
      popupVisible2: false,
    };
  },
  methods: {
    onOptionClick(item) {
      this.selectValue = item;
      // 选中后立即关闭浮层
      this.popupVisible = false;
      this.popupVisible2 = false;
    },
    onClear() {
      this.selectValue = undefined;
    },
    onPopupVisibleChange(val, context) {
      console.log(context);
      this.popupVisible = val;
    },
    onPopupVisibleChange2(val) {
      this.popupVisible2 = val;
    },
  },
};
</script>
<style lang="less" scoped>
.tdesign-demo__select-input-ul-label-suffix {
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.tdesign-demo__select-input-ul-label-suffix > li {
  display: block;
  border-radius: 3px;
  line-height: 22px;
  cursor: pointer;
  padding: 3px 8px;
  color: var(--td-text-color-primary);
  transition: background-color 0.2s linear;
  white-space: nowrap;
  word-wrap: normal;
  overflow: hidden;
  text-overflow: ellipsis;
}

.tdesign-demo__select-input-ul-label-suffix > li:hover {
  background-color: var(--td-bg-color-container-hover);
}
</style>
