// skills/tdesign-react/references/examples/button/theme.tsx
/**
 * TDesign TDesign React 示例：button - theme
 * 覆盖组件：Button
 * 来源：组件库源码 packages/components/button/_example/theme.tsx
 */

import React from 'react';
import { Button, Space } from 'tdesign-react';

export default function ButtonExample() {
  return (
    <Space direction="vertical">
      <Space>
        <Button theme="default">填充按钮</Button>
        <Button variant="outline" theme="default">
          描边按钮
        </Button>
        <Button variant="dashed" theme="default">
          虚框按钮
        </Button>
        <Button variant="text" theme="default">
          文字按钮
        </Button>
      </Space>
      <Space>
        <Button theme="primary" variant="base">
          填充按钮
        </Button>
        <Button theme="primary" variant="outline">
          描边按钮
        </Button>
        <Button theme="primary" variant="dashed">
          虚框按钮
        </Button>
        <Button theme="primary" variant="text">
          文字按钮
        </Button>
      </Space>
      <Space>
        <Button theme="danger" variant="base">
          填充按钮
        </Button>
        <Button theme="danger" variant="outline">
          描边按钮
        </Button>
        <Button theme="danger" variant="dashed">
          虚框按钮
        </Button>
        <Button theme="danger" variant="text">
          文字按钮
        </Button>
      </Space>
      <Space>
        <Button theme="warning" variant="base">
          填充按钮
        </Button>
        <Button theme="warning" variant="outline">
          描边按钮
        </Button>
        <Button theme="warning" variant="dashed">
          虚框按钮
        </Button>
        <Button theme="warning" variant="text">
          文字按钮
        </Button>
      </Space>
      <Space>
        <Button theme="success" variant="base">
          填充按钮
        </Button>
        <Button theme="success" variant="outline">
          描边按钮
        </Button>
        <Button theme="success" variant="dashed">
          虚框按钮
        </Button>
        <Button theme="success" variant="text">
          文字按钮
        </Button>
      </Space>
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/link/theme.vue
<!--
  TDesign TDesign Vue Next 示例：link - theme
  覆盖组件：Link
  来源：组件库源码 packages/components/link/_example/theme.vue
-->

<template>
  <t-space>
    <t-link theme="default"> 跳转链接 </t-link>
    <t-link theme="primary"> 跳转链接 </t-link>
    <t-link theme="danger"> 跳转链接 </t-link>
    <t-link theme="warning"> 跳转链接 </t-link>
    <t-link theme="success"> 跳转链接 </t-link>
  </t-space>
</template>
