// skills/tdesign-react/references/examples/pagination/simple-mini.tsx
/**
 * TDesign TDesign React 示例：pagination - simple-mini
 * 覆盖组件：Pagination
 * 来源：组件库源码 packages/components/pagination/_example/simple-mini.tsx
 */

import React from 'react';
import { Pagination } from 'tdesign-react';

import type { PaginationProps } from 'tdesign-react';

export default function PaginationExample() {
  const onChange: PaginationProps['onChange'] = (pageInfo) => {
    console.log(pageInfo);
  };

  return <Pagination total={100} defaultPageSize={5} size="small" theme="simple" onChange={onChange} />;
}

// skills/tdesign-vue2/references/examples/pagination/simple-mini.vue
<!--
  TDesign TDesign Vue 2 示例：pagination - simple-mini
  覆盖组件：Pagination
  来源：组件库源码 src/pagination/_example/simple-mini.vue
-->

<template>
  <t-pagination theme="simple" size="small" :total="100" :page-size.sync="pageSize" />
</template>

<script>
export default {
  data() {
    return {
      pageSize: 5,
    };
  },
};
</script>
