// skills/tdesign-react/references/examples/select/remote-search.tsx
/**
 * TDesign TDesign React 示例：select - remote-search
 * 覆盖组件：Select
 * 来源：组件库源码 packages/components/select/_example/remote-search.tsx
 */

import React, { useEffect, useState } from 'react';
import { Select, Space } from 'tdesign-react';

const OPTIONS = Array.from({ length: 20 }).map((_, i) => ({
  value: `t${i + 1}`,
  label: `Tencent_${i + 1}`,
}));

const RemoteSearchSelect = () => {
  const [singleLoading, setSingleLoading] = useState(false);
  const [singleOptions, setSingleOptions] = useState([]);
  const [singleValue, setSingleValue] = useState('');

  const [multipleLoading, setMultipleLoading] = useState(false);
  const [multipleOptions, setMultipleOptions] = useState([]);
  const [multipleValue, setMultipleValue] = useState([]);

  useEffect(() => {
    setSingleLoading(true);
    setMultipleLoading(true);

    setTimeout(() => {
      setSingleOptions(OPTIONS);
      setSingleLoading(false);
      setSingleValue(OPTIONS[0].value);
      setMultipleOptions(OPTIONS);
      setMultipleLoading(false);
      setMultipleValue([OPTIONS[0].value, OPTIONS[1].value]);
    }, 500);
  }, []);

  const handleSingle = (search: string) => {
    setSingleLoading(true);
    setTimeout(() => {
      const filtered = OPTIONS.filter((item) => item.label.includes(search));
      setSingleOptions(filtered);
      setSingleLoading(false);
    }, 500);
  };

  const handleMultiple = (search: string) => {
    setMultipleLoading(true);
    setTimeout(() => {
      const filtered = OPTIONS.filter((item) => item.label.includes(search));
      setMultipleOptions(filtered);
      setMultipleLoading(false);
    }, 500);
  };

  return (
    <Space direction="vertical">
      <Select
        filterable
        options={singleOptions}
        value={singleValue}
        loading={singleLoading}
        onChange={setSingleValue}
        onSearch={handleSingle}
      />
      <Select
        multiple
        filterable
        options={multipleOptions}
        value={multipleValue}
        loading={multipleLoading}
        onChange={setMultipleValue}
        onSearch={handleMultiple}
        style={{ width: '400px' }}
      />
    </Space>
  );
};

export default RemoteSearchSelect;

// skills/tdesign-vue2/references/examples/select/remote-search.vue
<!--
  TDesign TDesign Vue 2 示例：select - remote-search
  覆盖组件：Select
  来源：组件库源码 src/select/_example/remote-search.vue
-->

<template>
  <!-- 远程搜索场景会改变 options 数组，导致无法检索历史选项，可通过将 valueType 改为 `object` 以从 value 中读取 `label`，解决无法回显的问题 -->

  <t-space>
    <t-select
      v-model="value"
      value-type="object"
      filterable
      placeholder="请选择"
      :onSearch="remoteMethod"
      :loading="loading"
      :options="options"
      style="width: 200px; display: inline-block; margin: 0 20px 20px 0"
    />
  </t-space>
</template>

<script>
export default {
  data() {
    return {
      options: [],
      value: {},
      loading: false,
    };
  },
  methods: {
    remoteMethod(search) {
      console.log('search', search);
      this.loading = true;
      setTimeout(() => {
        this.loading = false;
        this.options = [
          {
            value: '腾讯_test1',
            label: '腾讯_test1',
          },
          {
            value: '腾讯_test2',
            label: '腾讯_test2',
          },
          {
            value: '腾讯_test3',
            label: '腾讯_test3',
          },
        ].filter((item) => item.label.includes(search));
      }, 500);
    },
  },
};
</script>
