// skills/tdesign-vue2/references/examples/tag/selectable.vue
<!--
  TDesign TDesign Vue 2 示例：tag - selectable
  覆盖组件：Tag
  来源：组件库源码 src/tag/_example/selectable.vue
-->

<template>
  <t-space direction="vertical">
    <t-space align="center">
      <label>StyleA</label>

      <t-check-tag v-model="checked1" style="margin-right: 32px">选中/未选态</t-check-tag>

      <t-check-tag :checked="true">选中态</t-check-tag>
      <t-check-tag :checked="false">未选态</t-check-tag>
      <t-check-tag :checked="true" disabled>选中禁用</t-check-tag>
      <t-check-tag :checked="false" disabled>未选禁用</t-check-tag>
    </t-space>

    <t-space align="center">
      <label>StyleB</label>

      <t-check-tag v-model="checked2" :unchecked-props="STYLE_B_UNCHECKED_PROPS" style="margin-right: 32px"
      >选中/未选态</t-check-tag
      >

      <t-check-tag :checked="true">选中态</t-check-tag>
      <t-check-tag :checked="false" :unchecked-props="STYLE_B_UNCHECKED_PROPS">未选态</t-check-tag>
      <t-check-tag :checked="true" disabled>选中禁用</t-check-tag>
      <t-check-tag :checked="false" disabled :unchecked-props="STYLE_B_UNCHECKED_PROPS">未选禁用</t-check-tag>
    </t-space>

    <t-space align="center">
      <label>StyleC</label>

      <t-check-tag
        v-model="checked3"
        :checked-props="STYLE_C_CHECKED_PROPS"
        :unchecked-props="STYLE_B_UNCHECKED_PROPS"
        style="margin-right: 32px"
      >Outline Tag</t-check-tag
      >

      <t-check-tag :checked="true" :checked-props="STYLE_C_CHECKED_PROPS">Checked</t-check-tag>
      <t-check-tag :checked="false" :unchecked-props="STYLE_B_UNCHECKED_PROPS">Unchecked</t-check-tag>
      <t-check-tag :checked="true" disabled :checked-props="STYLE_C_CHECKED_PROPS">Disabled</t-check-tag>
      <t-check-tag :checked="false" disabled :unchecked-props="STYLE_B_UNCHECKED_PROPS">Disabled</t-check-tag>
    </t-space>
  </t-space>
</template>

<script>
const STYLE_B_UNCHECKED_PROPS = {
  theme: 'default',
  variant: 'outline',
};

const STYLE_C_CHECKED_PROPS = {
  theme: 'primary',
  variant: 'outline',
};

export default {
  data() {
    return {
      checked1: false,
      checked2: false,
      checked3: false,
      STYLE_B_UNCHECKED_PROPS,
      STYLE_C_CHECKED_PROPS,
    };
  },
};
</script>

// skills/tdesign-react/references/examples/tag/selectable.tsx
/**
 * TDesign TDesign React 示例：tag - selectable
 * 覆盖组件：Tag
 * 来源：组件库源码 packages/components/tag/_example/selectable.tsx
 */

import React, { useState } from 'react';
import { Space, Tag } from 'tdesign-react';

const { CheckTag } = Tag;

const STYLE_B_UNCHECKED_PROPS = {
  theme: 'default',
  variant: 'outline',
} as const;

const STYLE_C_CHECKED_PROPS = {
  theme: 'primary',
  variant: 'outline',
} as const;

export default function CheckTagExample() {
  const [checked1, setChecked1] = useState(false);
  const [checked2, setChecked2] = useState(false);
  const [checked3, setChecked3] = useState(false);

  return (
    <Space direction="vertical">
      <Space align="center">
        <label>StyleA</label>
        <CheckTag checked={checked1} onChange={setChecked1} style={{ marginRight: '32px' }}>
          选中/未选态
        </CheckTag>
        <CheckTag checked={true}>选中态</CheckTag>
        <CheckTag checked={false}>未选态</CheckTag>
        <CheckTag checked={true} disabled>
          选中禁用
        </CheckTag>
        <CheckTag checked={false} disabled>
          未选禁用
        </CheckTag>
      </Space>

      <Space align="center">
        <label>StyleB</label>
        <CheckTag
          checked={checked2}
          onChange={setChecked2}
          uncheckedProps={STYLE_B_UNCHECKED_PROPS}
          style={{ marginRight: '32px' }}
        >
          选中/未选态
        </CheckTag>

        <CheckTag checked={true}>选中态</CheckTag>
        <CheckTag checked={false} uncheckedProps={STYLE_B_UNCHECKED_PROPS}>
          未选态
        </CheckTag>
        <CheckTag checked={true} disabled>
          选中禁用
        </CheckTag>
        <CheckTag checked={false} disabled uncheckedProps={STYLE_B_UNCHECKED_PROPS}>
          未选禁用
        </CheckTag>
      </Space>

      <Space align="center">
        <label>StyleC</label>
        <CheckTag
          checked={checked3}
          onChange={setChecked3}
          checkedProps={STYLE_C_CHECKED_PROPS}
          uncheckedProps={STYLE_B_UNCHECKED_PROPS}
          style={{ marginRight: '32px' }}
        >
          Outline Tag
        </CheckTag>

        <CheckTag checked={true} checkedProps={STYLE_C_CHECKED_PROPS}>
          Checked
        </CheckTag>
        <CheckTag checked={false} uncheckedProps={STYLE_B_UNCHECKED_PROPS}>
          Unchecked
        </CheckTag>
        <CheckTag checked={true} disabled checkedProps={STYLE_C_CHECKED_PROPS}>
          Disabled
        </CheckTag>
        <CheckTag checked={false} disabled uncheckedProps={STYLE_B_UNCHECKED_PROPS}>
          Disabled
        </CheckTag>
      </Space>
    </Space>
  );
}
