// skills/tdesign-vue-next/references/examples/tag/shape.vue
<!--
  TDesign TDesign Vue Next 示例：tag - shape
  覆盖组件：Tag
  来源：组件库源码 packages/components/tag/_example/shape.vue
-->

<template>
  <t-space direction="vertical">
    <t-space class="tag-demo">
      <t-tag>标签一</t-tag>
      <t-tag theme="primary">标签一</t-tag>
    </t-space>
    <t-space class="tag-demo">
      <t-tag shape="round">标签一</t-tag>
      <t-tag shape="round" theme="primary">标签一</t-tag>
    </t-space>
    <t-space class="tag-demo">
      <t-tag shape="mark">标签一</t-tag>
      <t-tag shape="mark" theme="primary">标签一</t-tag>
    </t-space>
  </t-space>
</template>

// skills/tdesign-react/references/examples/tag/shape.tsx
/**
 * TDesign TDesign React 示例：tag - shape
 * 覆盖组件：Tag
 * 来源：组件库源码 packages/components/tag/_example/shape.tsx
 */

import React from 'react';
import { Space, Tag } from 'tdesign-react';

export default function ShapeTagExample() {
  const style = { marginRight: 5 };
  return (
    <Space direction="vertical">
      <Space>
        <Tag>标签一</Tag>
        <Tag theme="primary">标签一</Tag>
      </Space>
      <Space>
        <Tag shape="round" style={style}>
          标签一
        </Tag>
        <Tag shape="round" theme="primary">
          标签一
        </Tag>
      </Space>
      <Space>
        <Tag shape="mark">标签一</Tag>
        <Tag shape="mark" theme="primary">
          标签一
        </Tag>
      </Space>
    </Space>
  );
}
