// skills/tdesign-react/references/examples/form/layout.tsx
/**
 * TDesign TDesign React 示例：form - layout
 * 覆盖组件：Form
 * 来源：组件库源码 packages/components/form/_example/layout.tsx
 */

import React, { useState } from 'react';
import { Form, Input, Radio, Space } from 'tdesign-react';

const { FormItem } = Form;

type Layout = 'vertical' | 'inline';

export default function LayoutForm() {
  const [layout, setLayout] = useState<Layout>('inline');
  return (
    <Space direction="vertical">
      <div>
        <Radio.Group value={layout} onChange={(value: Layout) => setLayout(value)} variant="default-filled">
          <Radio.Button value="vertical">纵向布局</Radio.Button>
          <Radio.Button value="inline">行内布局</Radio.Button>
        </Radio.Group>
      </div>
      <Form layout={layout} labelWidth={60}>
        <FormItem label="名字" name="name">
          <Input />
        </FormItem>
        <FormItem label="密码" name="password">
          <Input />
        </FormItem>
      </Form>
    </Space>
  );
}

// skills/tdesign-vue2/references/examples/form/layout.vue
<!--
  TDesign TDesign Vue 2 示例：form - layout
  覆盖组件：Form
  来源：组件库源码 src/form/_example/layout.vue
-->

<template>
  <t-space direction="vertical" size="32px">
    <t-radio-group v-model="formData.layout" variant="default-filled">
      <t-radio-button value="vertical">纵向布局</t-radio-button>
      <t-radio-button value="inline">行内布局</t-radio-button>
    </t-radio-group>

    <t-form
      :data="formData"
      labelWidth="calc(2em + 24px)"
      :layout="formData.layout"
      ref="form"
      @reset="onReset"
      @submit="onSubmit"
      scrollToFirstError="smooth"
    >
      <t-form-item label="姓名" name="name">
        <t-input v-model="formData.name" placeholder="请输入姓名"></t-input>
      </t-form-item>
      <t-form-item label="密码" name="password">
        <t-input v-model="formData.password" type="password" placeholder="请输入密码"></t-input>
      </t-form-item>
    </t-form>
  </t-space>
</template>
<script>
const INITIAL_DATA = {
  layout: 'inline',
  name: '',
  password: '',
};
export default {
  data() {
    return {
      formData: { ...INITIAL_DATA },
    };
  },
  methods: {
    onReset() {
      this.$message.success('重置成功');
    },
    onSubmit({ validateResult, firstError }) {
      if (validateResult === true) {
        this.$message.success('提交成功');
      } else {
        console.log('Errors: ', validateResult);
        this.$message.warning(firstError);
      }
    },
  },
};
</script>
