// skills/tdesign-mobile-vue/references/examples/tabs/isometric.vue
<!--
  TDesign TDesign Mobile Vue 示例：tabs - isometric
  覆盖组件：Tabs
  来源：组件库源码 src/tabs/demos/isometric.vue
-->

<template>
  <div class="demo-tab-bar">
    <t-tabs :value="currentValue" :list="list" :space-evenly="false" @change="onChange" />
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

const currentValue = ref('1');
const list = [
  {
    value: '1',
    label: '选项',
  },
  {
    value: '2',
    label: '选项',
  },
  {
    value: '3',
    label: '选项',
  },
  {
    value: '4',
    label: '选项',
  },
  {
    value: '5',
    label: '选项',
  },
  {
    value: '6',
    label: '选项',
  },

  {
    value: '7',
    label: '选项',
  },
  {
    value: '8',
    label: '选项',
  },
  {
    value: '9',
    label: '选项',
  },
];

const onChange = (value: string) => {
  currentValue.value = value;
  console.log(`change to ${value}`);
};
</script>

<style lang="less" scoped>
.t-tabs {
  margin-bottom: 16px;
}
</style>

// skills/tdesign-mobile-react/references/examples/tabs/isometric.tsx
/**
 * TDesign TDesign Mobile React 示例：tabs - isometric
 * 覆盖组件：Tabs
 * 来源：组件库源码 src/tabs/_example/isometric.tsx
 */

import React, { useState } from 'react';
import { Tabs } from 'tdesign-mobile-react';

export default () => {
  const list = [
    {
      value: '1',
      label: '选项',
    },
    {
      value: '2',
      label: '选项',
    },
    {
      value: '3',
      label: '选项',
    },
    {
      value: '4',
      label: '选项',
    },
    {
      value: '5',
      label: '选项',
    },
    {
      value: '6',
      label: '选项',
    },

    {
      value: '7',
      label: '选项',
    },
    {
      value: '8',
      label: '选项',
    },
    {
      value: '9',
      label: '选项',
    },
  ];

  const [currentValue, setCurrentValue] = useState('9');
  const onChange = (value: string) => {
    setCurrentValue(value);
    console.log(value);
  };
  return (
    <div>
      <Tabs value={currentValue} list={list} spaceEvenly={false} onChange={onChange}></Tabs>
    </div>
  );
};
