// skills/tdesign-mobile-react/references/examples/cell/multiple.tsx
/**
 * TDesign TDesign Mobile React 示例：cell - multiple
 * 覆盖组件：Cell
 * 来源：组件库源码 src/cell/_example/multiple.tsx
 */

import React from 'react';
import { CellGroup, Cell, Badge, Switch, Avatar } from 'tdesign-mobile-react';
import { ChevronRightIcon, AppIcon } from 'tdesign-icons-react';

export default function Multiple() {
  const chevronRightIcon = <ChevronRightIcon />;
  const avatarUrl = 'https://tdesign.gtimg.com/mobile/demos/avatar1.png';
  const imgUrl = 'https://tdesign.gtimg.com/mobile/demos/example4.png';

  return (
    <CellGroup>
      <Cell title="单行标题" description="一段很长很长的内容文字" arrow />
      <Cell title="单行标题" description="一段很长很长的内容文字" arrow required />
      <Cell title="单行标题" description="一段很长很长的内容文字" arrow note={<Badge count={16} />} />
      <Cell title="单行标题" description="一段很长很长的内容文字" note={<Switch defaultValue={true} />} />
      <Cell title="单行标题" description="一段很长很长的内容文字" note="辅助信息" arrow />
      <Cell title="单行标题" description="一段很长很长的内容文字" arrow leftIcon={<AppIcon />} />
      <Cell title="单行标题" description="一段很长很长的内容文字，长文本自动换行，该选项的描述是一段很长的内容" />
      <Cell
        title="多行高度不定，长文本自动换行，该选项的描述是一段很长的内容"
        description="一段很长很长的内容文字，长文本自动换行，该选项的描述是一段很长的内容"
      />
      <Cell
        title="单行标题"
        description="一段很长很长的内容文字"
        leftIcon={<Avatar shape="circle" image={avatarUrl} />}
        rightIcon={chevronRightIcon}
      />
      <Cell title="单行标题" description="一段很长很长的内容文字" image={imgUrl} />
    </CellGroup>
  );
}

// skills/tdesign-mobile-vue/references/examples/grid/multiple.vue
<!--
  TDesign TDesign Mobile Vue 示例：grid - multiple
  覆盖组件：Grid
  来源：组件库源码 src/grid/demos/multiple.vue
-->

<template>
  <t-grid :column="4" class="grid-demo">
    <t-grid-item :image="imgUrl" text="标题文字" />
    <t-grid-item :image="imgUrl" text="标题文字" />
    <t-grid-item :image="imgUrl" text="标题文字" />
    <t-grid-item :image="imgUrl" text="最多五个字" />
    <t-grid-item :image="imgUrl" text="标题文字" />
    <t-grid-item :image="imgUrl" text="标题文字" />
    <t-grid-item :image="imgUrl" text="标题文字" />
    <t-grid-item :image="imgUrl" text="最多五个字" />
  </t-grid>
</template>
<script lang="ts" setup>
const imgUrl = 'https://tdesign.gtimg.com/mobile/demos/example1.png';
</script>
<style lang="less" scoped>
.grid-demo {
  margin-bottom: 16px;
}
</style>
