// skills/tdesign-vue2/references/examples/progress/plump.vue
<!--
  TDesign TDesign Vue 2 示例：progress - plump
  覆盖组件：Progress
  来源：组件库源码 src/progress/_example/plump.vue
-->

<template>
  <div>
    <div>
      <div class="t-progress-domo-margin">默认样式</div>
      <t-progress theme="plump" :percentage="30" />
      <div class="t-progress-domo-margin">进度0-10%时数字数字位置出现在目前进度的右边区域</div>
      <t-progress theme="plump" :percentage="5" />
      <div class="t-progress-domo-margin">100%</div>
      <t-progress theme="plump" :percentage="100" />
      <div class="t-progress-domo-margin">进度完成</div>
      <t-progress theme="plump" :status="'success'" :percentage="30" />
      <div class="t-progress-domo-margin">进度状态发生重大错误</div>
      <t-progress theme="plump" :status="'error'" :percentage="30" />
      <div class="t-progress-domo-margin">进度被中断</div>
      <t-progress theme="plump" :status="'warning'" :percentage="30" />
      <div class="t-progress-domo-margin">渐变色</div>
      <t-progress theme="plump" :color="{ from: '#0052D9', to: '#00A870' }" :percentage="30" :status="'active'" />
    </div>
  </div>
</template>
<style scoped>
div > .t-progress-domo-margin:first-child {
  margin-top: 0;
}

.t-progress-domo-margin {
  margin: 15px 0 10px;
}
</style>

// skills/tdesign-mobile-react/references/examples/progress/plump.tsx
/**
 * TDesign TDesign Mobile React 示例：progress - plump
 * 覆盖组件：Progress
 * 来源：组件库源码 src/progress/_example/plump.tsx
 */

import React from 'react';
import { Progress } from 'tdesign-mobile-react';

import './style/index.less';

export default function Plump() {
  return (
    <div className="example-progress">
      <div className="example-progress__item">
        <Progress theme="plump" percentage={80} />
      </div>
      <div className="example-progress__item">
        <Progress theme="plump" percentage={100} />
      </div>
      <div className="example-progress__item">
        <Progress theme="plump" percentage={80} status="warning" />
      </div>
      <div className="example-progress__item">
        <Progress theme="plump" percentage={80} status="error" />
      </div>
      <div className="example-progress__item">
        <Progress theme="plump" percentage={80} color={['#0052D9', '#2BA471']} status="active" />
      </div>
    </div>
  );
}
