// skills/tdesign-react/references/examples/popconfirm/placement.tsx
/**
 * TDesign TDesign React 示例：popconfirm - placement
 * 覆盖组件：Popconfirm
 * 来源：组件库源码 packages/components/popconfirm/_example/placement.tsx
 */

import React from 'react';
import { Button, Popconfirm, Space } from 'tdesign-react';

export default function PlacementExample() {
  const $content = '请确认您要进行此操作';
  return (
    <Space>
      <Popconfirm content={$content} placement="left">
        <Button theme="primary">Left</Button>
      </Popconfirm>

      <Popconfirm content={$content} placement="top">
        <Button>Top</Button>
      </Popconfirm>

      <Popconfirm content={$content} placement="bottom">
        <Button>Bottom</Button>
      </Popconfirm>
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/swiper/placement.vue
<!--
  TDesign TDesign Vue Next 示例：swiper - placement
  覆盖组件：Swiper
  来源：组件库源码 packages/components/swiper/_example/placement.vue
-->

<template>
  <t-swiper class="tdesign-demo-block--swiper" :navigation="{ placement: 'outside' }">
    <t-swiper-item v-for="item in 6" :key="item">
      <div class="demo-item">{{ item }}</div>
    </t-swiper-item>
  </t-swiper>
</template>
