// skills/tdesign-react/references/examples/timeline/layout.tsx
/**
 * TDesign TDesign React 示例：timeline - layout
 * 覆盖组件：Timeline
 * 来源：组件库源码 packages/components/timeline/_example/layout.tsx
 */

import React, { useState } from 'react';
import { Radio, Space, Timeline } from 'tdesign-react';

export default function LayoutTimeLine() {
  const [direction, setDirection] = useState<'left' | 'right' | 'alternate'>('left');
  const [mode, setMode] = useState<'same' | 'alternate'>('same');
  const [layout, setLayout] = useState<'vertical' | 'horizontal'>('vertical');

  return (
    <Space direction="vertical">
      <Space>
        <h4>时间轴方向</h4>
        <Radio.Group variant="default-filled" value={layout} onChange={(v) => setLayout(v as any)}>
          <Radio.Button value="vertical">垂直时间轴</Radio.Button>
          <Radio.Button value="horizontal">水平时间轴</Radio.Button>
        </Radio.Group>
      </Space>
      <Space>
        <h4>对齐方式</h4>
        <Radio.Group variant="default-filled" value={direction} onChange={(v) => setDirection(v as any)}>
          <Radio.Button value="left">左对齐</Radio.Button>
          <Radio.Button value="alternate">交错对齐</Radio.Button>
          <Radio.Button value="right">右对齐</Radio.Button>
        </Radio.Group>
      </Space>
      <Space>
        <h4>label对齐方式</h4>
        <Radio.Group variant="default-filled" value={mode} onChange={(v) => setMode(v as any)}>
          <Radio.Button value="same">同侧</Radio.Button>
          <Radio.Button value="alternate">交错</Radio.Button>
        </Radio.Group>
      </Space>
      <Timeline layout={layout} labelAlign={direction} mode={mode}>
        <Timeline.Item label="2022-01-01">事件一</Timeline.Item>
        <Timeline.Item label="2022-02-01">事件二</Timeline.Item>
        <Timeline.Item label="2022-03-01">事件三</Timeline.Item>
        <Timeline.Item label="2022-04-01">事件四</Timeline.Item>
      </Timeline>
    </Space>
  );
}

// skills/tdesign-vue2/references/examples/timeline/layout.vue
<!--
  TDesign TDesign Vue 2 示例：timeline - layout
  覆盖组件：Timeline
  来源：组件库源码 src/timeline/_example/layout.vue
-->

<template>
  <div>
    <t-space direction="vertical">
      <t-space>
        <h4>时间轴方向</h4>
        <t-radio-group default-value="vertical" @change="handleLayoutChange">
          <t-radio-button value="vertical">垂直时间轴</t-radio-button>
          <t-radio-button value="horizontal">水平时间轴</t-radio-button>
        </t-radio-group>
      </t-space>
      <t-space>
        <h4>对齐方式</h4>
        <t-radio-group default-value="left" @change="handleDirectionChange">
          <t-radio-button value="left">左对齐</t-radio-button>
          <t-radio-button value="alternate">交错对齐</t-radio-button>
          <t-radio-button value="right">右对齐</t-radio-button>
        </t-radio-group>
      </t-space>
      <t-space>
        <h4>label对齐方式</h4>
        <t-radio-group default-value="same" @change="handleModeChange">
          <t-radio-button value="same">同侧</t-radio-button>
          <t-radio-button value="alternate">交错</t-radio-button>
        </t-radio-group>
      </t-space>
    </t-space>
    <t-timeline :layout="layout" :labelAlign="direction" :mode="mode">
      <t-timeline-item label="2022-01-01">事件一</t-timeline-item>
      <t-timeline-item label="2022-02-01">事件二</t-timeline-item>
      <t-timeline-item label="2022-03-01">事件三</t-timeline-item>
      <t-timeline-item label="2022-04-01">事件四</t-timeline-item>
    </t-timeline>
  </div>
</template>
<script>
export default {
  data() {
    return {
      layout: 'vertical',
      direction: 'left',
      mode: 'same',
    };
  },
  methods: {
    handleLayoutChange(checkedValue) {
      this.layout = checkedValue;
    },
    handleDirectionChange(checkedValue) {
      this.direction = checkedValue;
    },
    handleModeChange(checkedValue) {
      this.mode = checkedValue;
    },
  },
};
</script>
