// skills/tdesign-react/references/examples/loading/delay.tsx
/**
 * TDesign TDesign React 示例：loading - delay
 * 覆盖组件：Loading
 * 来源：组件库源码 packages/components/loading/_example/delay.tsx
 */

import React, { useEffect, useState } from 'react';
import { Button, Loading, Space } from 'tdesign-react';

export default function LoadingDelay() {
  const [data, setData] = useState('');
  const [loading, setLoading] = useState(false);

  const loadingData = (time?: number) => {
    setLoading(true);
    setData('');
    const timer = setTimeout(() => {
      setLoading(false);
      setData('数据加载完成，短时间的数据加载并未出现 loading');
      clearTimeout(timer);
    }, time || 100);
  };

  useEffect(() => {
    loadingData();
  }, []);

  return (
    <Space direction="vertical">
      <div>
        <Loading delay={500} size="small" loading={loading}></Loading>
        {data ? <div>{`loading 作为独立元素：${data}`}</div> : null}
      </div>

      <div>
        <Loading loading={loading} delay={500} size="small" showOverlay>
          <div>{data ? `loading 作为包裹元素：${data}` : ''}</div>
        </Loading>
      </div>

      <div className="tdesign-demo-block-row">
        <Button onClick={() => loadingData()} size="small">
          快速重新加载数据（无loading）
        </Button>
        <Button onClick={() => loadingData(1000)} size="small">
          慢速重新加载数据
        </Button>
      </div>
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/loading/delay.vue
<!--
  TDesign TDesign Vue Next 示例：loading - delay
  覆盖组件：Loading
  来源：组件库源码 packages/components/loading/_example/delay.vue
-->

<template>
  <t-space direction="vertical">
    <div>
      <t-loading v-if="loading" :delay="delay" size="small"></t-loading>
      <div v-if="data">loading 作为独立元素：{{ data }}</div>
    </div>

    <t-loading :loading="loading" :delay="delay" size="small">
      <div class="wrap">{{ data ? `loading 作为包裹元素：${data}` : '' }}</div>
    </t-loading>

    <t-space>
      <t-button size="small" @click="loadingData">快速重新加载数据（无loading）</t-button>
      <t-button size="small" @click="() => loadingData(1000)">慢速重新加载数据</t-button>
    </t-space>
  </t-space>
</template>
<script lang="ts" setup>
import { ref, onMounted } from 'vue';

const loading = ref(true);
const data = ref('');
const delay = ref(500);
const loadingData = (time = 100) => {
  loading.value = true;
  data.value = '';
  const timer = setTimeout(() => {
    loading.value = false;
    data.value = '数据加载完成，短时间的数据加载并未出现 loading';
    clearTimeout(timer);
  }, time || 100);
};
onMounted(() => {
  loadingData();
});
</script>
