// skills/tdesign-react/references/examples/progress/circle.tsx
/**
 * TDesign TDesign React 示例：progress - circle
 * 覆盖组件：Progress
 * 来源：组件库源码 packages/components/progress/_example/circle.tsx
 */

import React, { useEffect, useState } from 'react';
import { Progress, Space } from 'tdesign-react';

export default function CircleProgress() {
  const [percent, setPercent] = useState(10);

  useEffect(() => {
    const timer = setInterval(() => setPercent((v) => (v % 100) + 10), 1000);
    return () => clearInterval(timer);
  }, []);

  return (
    <Space direction="vertical">
      <div>默认</div>
      {/* 重要：strokeWidth 大小不能超过 size 的一半，否则无法渲染出环形 */}
      <Space size="large" style={{ margin: '20px 0 10px' }}>
        <Space align="center" direction="vertical" size="small" style={{ margin: 15, minWidth: 160 }}>
          <div style={{ marginBottom: 10 }}>默认样式</div>
          <Progress theme="circle" percentage={percent} />
        </Space>
        <Space align="center" direction="vertical" size="small" style={{ margin: 15, minWidth: 160 }}>
          <div style={{ marginBottom: 10 }}>不显示数字</div>
          <Progress theme="circle" label={false} percentage={percent} />
        </Space>
        <Space align="center" direction="vertical" size="small" style={{ margin: 15, minWidth: 160 }}>
          <div style={{ marginBottom: 10 }}>自定义内容</div>
          <Progress theme="circle" label={<div>{percent}day</div>} percentage={percent} />
        </Space>
      </Space>

      <Space size="large" style={{ margin: '20px 0 10px' }}>
        <Space align="center" direction="vertical" size="small" style={{ margin: 15, minWidth: 160 }}>
          <div style={{ marginBottom: 10 }}>进度状态完成</div>
          <Progress theme="circle" percentage={100} status="success" />
        </Space>
        <Space align="center" direction="vertical" size="small" style={{ margin: 15, minWidth: 160 }}>
          <div style={{ marginBottom: 10 }}>进度状态发生重大错误</div>
          <Progress theme="circle" percentage={75} status="error" />
        </Space>
        <Space align="center" direction="vertical" size="small" style={{ margin: 15, minWidth: 160 }}>
          <div style={{ marginBottom: 10 }}>进度状态被中断</div>
          <Progress theme="circle" percentage={50} status="warning" />
        </Space>
      </Space>

      <div>默认不同尺寸</div>
      <Space size="large" style={{ margin: '20px 0 10px' }}>
        <Space align="center" direction="vertical" size="small" style={{ margin: 15, minWidth: 160 }}>
          <div style={{ marginBottom: 10 }}>小尺寸</div>
          <Progress theme="circle" percentage={30} size="small" />
        </Space>
        <Space align="center" direction="vertical" size="small" style={{ margin: 15, minWidth: 160 }}>
          <div style={{ marginBottom: 10 }}>默认尺寸</div>
          <Progress theme="circle" percentage={30} size="medium" />
        </Space>
        <Space align="center" direction="vertical" size="small" style={{ margin: 15, minWidth: 160, marginLeft: 60 }}>
          <div style={{ marginBottom: 10 }}>大尺寸</div>
          <Progress theme="circle" percentage={75} size="large" />
        </Space>
      </Space>
    </Space>
  );
}

// skills/tdesign-vue2/references/examples/progress/circle.vue
<!--
  TDesign TDesign Vue 2 示例：progress - circle
  覆盖组件：Progress
  来源：组件库源码 src/progress/_example/circle.vue
-->

<template>
  <t-space direction="vertical" :size="36">
    <div>默认</div>
    <!-- 重要：strokeWidth 大小不能超过 size 的一半，否则无法渲染出环形 -->
    <t-space :size="78" class="ml-36px">
      <t-space direction="vertical" align="center" :size="10">
        <div>默认样式</div>
        <t-progress theme="circle" :percentage="30"></t-progress>
      </t-space>
      <t-space direction="vertical" align="center" :size="10">
        <div>不显示数字</div>
        <t-progress theme="circle" :label="false" :percentage="100" :status="'success'"></t-progress>
      </t-space>
      <t-space direction="vertical" align="center" :size="10">
        <div>自定义内容</div>
        <t-progress theme="circle" :label="'75day'" :percentage="50" :status="'success'"></t-progress>
      </t-space>
    </t-space>

    <t-space :size="78" class="ml-36px">
      <t-space direction="vertical" align="center" :size="10">
        <div>进度完成</div>
        <t-progress theme="circle" :percentage="100" :status="'success'"></t-progress>
      </t-space>
      <t-space direction="vertical" align="center" :size="10">
        <div>进度状态发生错误</div>
        <t-progress theme="circle" :percentage="75" :status="'error'"></t-progress>
      </t-space>
      <t-space direction="vertical" align="center" :size="10">
        <div>进度被中断</div>
        <t-progress theme="circle" :percentage="50" :status="'warning'"></t-progress>
      </t-space>
    </t-space>

    <div>默认不同尺寸</div>
    <t-space :size="110" class="ml-44px">
      <t-space direction="vertical" align="center" :size="10">
        <div>小尺寸</div>
        <t-progress theme="circle" :percentage="30" :size="'small'"></t-progress>
      </t-space>
      <t-space direction="vertical" align="center" :size="10">
        <div>默认尺寸</div>
        <t-progress theme="circle" :percentage="30" :size="'medium'"></t-progress>
      </t-space>
      <t-space direction="vertical" align="center" :size="10">
        <div>大尺寸</div>
        <t-progress theme="circle" :percentage="75" :size="'large'"></t-progress>
      </t-space>
    </t-space>
  </t-space>
</template>

<style lang="less" scoped>
.ml-36px {
  margin-left: 36px;
}
.ml-44px {
  margin-left: 44px;
}
</style>
