// skills/tdesign-react/references/examples/empty/descriptions.tsx
/**
 * TDesign TDesign React 示例：empty - descriptions
 * 覆盖组件：Empty
 * 来源：组件库源码 packages/components/empty/_example/descriptions.tsx
 */

import React from 'react';
import { Button, Empty } from 'tdesign-react';

export default function Operation() {
  function goToIndex() {
    console.log('go to index');
    location.href = '/';
  }
  return <Empty action={<Button onClick={goToIndex}>返回首页</Button>} description="description" />;
}

// skills/tdesign-vue2/references/examples/empty/descriptions.vue
<!--
  TDesign TDesign Vue 2 示例：empty - descriptions
  覆盖组件：Empty
  来源：组件库源码 src/empty/_example/descriptions.vue
-->

<template>
  <t-empty :description="description" :title="title"> </t-empty>
</template>
<script>
export default {
  data() {
    return {
      title: 'Empty',
      description: 'Description',
    };
  },
  methods: {
    goToIndex() {
      console.log('go to index');
      location.href = '/';
    },
  },
};
</script>
