// skills/tdesign-react/references/examples/tree-select/filterable.tsx
/**
 * TDesign TDesign React 示例：tree-select - filterable
 * 覆盖组件：Tree-select
 * 来源：组件库源码 packages/components/tree-select/_example/filterable.tsx
 */

import React, { useState } from 'react';
import { Radio, Space, TreeSelect } from 'tdesign-react';

import type { TreeSelectProps } from 'tdesign-react';

const options: TreeSelectProps['data'] = [
  {
    label: '广东省',
    value: 'guangdong',
    children: [
      {
        label: '广州市',
        value: 'guangzhou',
      },
      {
        label: '深圳市',
        value: 'shenzhen',
      },
    ],
  },
  {
    label: '江苏省',
    value: 'jiangsu',
    children: [
      {
        label: '南京市',
        value: 'nanjing',
      },
      {
        label: '苏州市',
        value: 'suzhou',
      },
    ],
  },
];

type TreeSelectType = 'default' | 'function';

export default function Example() {
  const [type, setType] = useState<TreeSelectType>('default');

  const handleEnter: TreeSelectProps['onEnter'] = (ctx) => {
    console.log('onEnter api:', ctx);
  };

  const filterFunction: TreeSelectProps['filter'] = (searchText, node) => node.data.label.indexOf(searchText) >= 0;

  return (
    <Space direction="vertical" style={{ width: 300 }}>
      <Radio.Group value={type} onChange={(v: TreeSelectType) => setType(v)} variant="default-filled">
        <Radio.Button value="default">默认</Radio.Button>
        <Radio.Button value="function">自定义方法</Radio.Button>
      </Radio.Group>
      {type === 'default' ? (
        <>
          <TreeSelect data={options} clearable filterable placeholder="请选择" onEnter={handleEnter} />
          <TreeSelect data={options} multiple clearable filterable placeholder="请选择" />
        </>
      ) : (
        <>
          <TreeSelect data={options} clearable filter={filterFunction} placeholder="请选择" />
          <TreeSelect data={options} multiple clearable filter={filterFunction} placeholder="请选择" />
        </>
      )}
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/tree-select/filterable.vue
<!--
  TDesign TDesign Vue Next 示例：tree-select - filterable
  覆盖组件：Tree-select
  来源：组件库源码 packages/components/tree-select/_example/filterable.vue
-->

<template>
  <t-space direction="vertical">
    <t-radio-group v-model="type" variant="default-filled">
      <t-radio-button value="default"> 默认 </t-radio-button>
      <t-radio-button value="function"> 自定义方法 </t-radio-button>
    </t-radio-group>
    <t-tree-select
      v-if="type === 'default'"
      v-model="value"
      :data="options"
      clearable
      filterable
      placeholder="请选择"
    />
    <t-tree-select v-else v-model="value" :data="options" clearable :filter="filterFunction" placeholder="请选择" />
  </t-space>
</template>
<script lang="ts" setup>
import { ref } from 'vue';
import type { TreeSelectProps } from 'tdesign-vue-next';

const options: TreeSelectProps['data'] = [
  {
    label: '广东省',
    value: 'guangdong',
    children: [
      {
        label: '广州市',
        value: 'guangzhou',
      },
      {
        label: '深圳市',
        value: 'shenzhen',
      },
    ],
  },
  {
    label: '江苏省',
    value: 'jiangsu',
    children: [
      {
        label: '南京市',
        value: 'nanjing',
      },
      {
        label: '苏州市',
        value: 'suzhou',
      },
    ],
  },
];
const value = ref('shenzhen');
const type = ref('default');
const filterFunction: TreeSelectProps['filter'] = (searchText, node) => {
  return node.data.label.indexOf(searchText) >= 0;
};
</script>
