// skills/tdesign-react/references/examples/tree-select/valuedisplay.tsx
/**
 * TDesign TDesign React 示例：tree-select - valuedisplay
 * 覆盖组件：Tree-select
 * 来源：组件库源码 packages/components/tree-select/_example/valuedisplay.tsx
 */

import React, { useState } from 'react';
import { Space, Tag, TreeSelect } from 'tdesign-react';

import type { TreeSelectProps } from 'tdesign-react';

const options: TreeSelectProps['data'] = [
  {
    label: '广东省',
    value: 'guangdong',
    children: [
      {
        label: '广州市',
        value: 'guangzhou',
      },
      {
        label: '深圳市',
        value: 'shenzhen',
      },
    ],
  },
  {
    label: '江苏省',
    value: 'jiangsu',
    children: [
      {
        label: '南京市',
        value: 'nanjing',
      },
      {
        label: '苏州市',
        value: 'suzhou',
      },
    ],
  },
];

export default function Example() {
  const [value, setValue] = useState('guangzhou');
  const [mulValue, setMulValue] = useState(['guangzhou', 'shenzhen']);
  return (
    <Space direction="vertical" style={{ width: 300 }}>
      <TreeSelect
        data={options}
        clearable
        placeholder="请选择"
        value={value}
        onChange={(val: string) => setValue(val)}
        valueDisplay={({ value }: { value }) => `${value.label}(${value.value})`}
      />
      <TreeSelect
        data={options}
        multiple
        clearable
        placeholder="请选择"
        value={mulValue}
        valueDisplay={({ onClose, value }) =>
          value.map(({ label, value }, index: number) => (
            <Tag key={value} closable onClose={() => onClose(index)}>
              {label}({value})
            </Tag>
          ))
        }
        onChange={(val: string[]) => setMulValue(val)}
      />
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/tree-select/valuedisplay.vue
<!--
  TDesign TDesign Vue Next 示例：tree-select - valuedisplay
  覆盖组件：Tree-select
  来源：组件库源码 packages/components/tree-select/_example/valuedisplay.vue
-->

<template>
  <t-space>
    <t-tree-select v-model="value" :data="options" clearable placeholder="请选择" filterable>
      <template #valueDisplay="{ value: valueDisplay }"> {{ valueDisplay.label }}({{ valueDisplay.value }}) </template>
    </t-tree-select>
    <t-tree-select v-model="mulValue" :data="options" multiple clearable filterable placeholder="请选择">
      <template #valueDisplay="{ value: valueDisplay, onClose }">
        <t-tag v-for="(item, index) in valueDisplay" :key="index" closable :on-close="() => onClose(index)">
          {{ item.label }}({{ item.value }})
        </t-tag>
      </template>
    </t-tree-select>
  </t-space>
</template>
<script lang="ts" setup>
import { ref } from 'vue';
import type { TreeSelectProps } from 'tdesign-vue-next';

const value = ref('shenzhen');
const mulValue = ref(['shenzhen', 'guangzhou']);
const options: TreeSelectProps['data'] = [
  {
    label: '广东省',
    value: 'guangdong',
    children: [
      {
        label: '广州市',
        value: 'guangzhou',
      },
      {
        label: '深圳市',
        value: 'shenzhen',
        children: [
          {
            label: '深圳市南山区海天二路33号腾讯滨海大厦',
            value: 'Tencent',
          },
        ],
      },
    ],
  },
  {
    label: '江苏省',
    value: 'jiangsu',
    children: [
      {
        label: '南京市',
        value: 'nanjing',
      },
      {
        label: '苏州市',
        value: 'suzhou',
      },
    ],
  },
];
</script>
