// skills/tdesign-react/references/examples/collapse/mutex.tsx
/**
 * TDesign TDesign React 示例：collapse - mutex
 * 覆盖组件：Collapse
 * 来源：组件库源码 packages/components/collapse/_example/mutex.tsx
 */

import React from 'react';
import { Collapse, TagInput } from 'tdesign-react';

export default function CollapseExample() {
  const { Panel } = Collapse;
  return (
    <Collapse expandMutex>
      <Panel header="这是一个折叠标题">
        这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
      </Panel>
      <Panel destroyOnCollapse header="折叠后自动销毁">
        这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
      </Panel>
      <Panel header="自定义折叠面板内容">
        <div className="tdesign-demo-block-column" style={{ width: '80%' }}>
          <TagInput defaultValue={['Vue', 'React']} clearable />
        </div>
      </Panel>
    </Collapse>
  );
}

// skills/tdesign-vue-next/references/examples/collapse/mutex.vue
<!--
  TDesign TDesign Vue Next 示例：collapse - mutex
  覆盖组件：Collapse
  来源：组件库源码 packages/components/collapse/_example/mutex.vue
-->

<template>
  <t-space direction="vertical">
    <t-collapse v-model="currentItem" expand-mutex @change="handlePanelChange">
      <t-collapse-panel value="0" header="这是一个折叠标题">
        这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
      </t-collapse-panel>

      <t-collapse-panel value="1">
        <template #header>这是一个折叠标题</template>
        <template #default>
          这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
        </template>
      </t-collapse-panel>

      <t-collapse-panel value="2">
        <template #header>这是一个折叠标题</template>
        这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
      </t-collapse-panel>

      <t-collapse-panel value="3" header="这是一个折叠标题">
        这部分是每个折叠面板折叠或展开的内容，可根据不同业务或用户的使用诉求，进行自定义填充。可以是纯文本、图文、子列表等内容形式。
      </t-collapse-panel>
    </t-collapse>

    <p>当前展开项：{{ currentItem }}</p>
  </t-space>
</template>

<script lang="tsx" setup>
import { ref } from 'vue';
import type { CollapseProps } from 'tdesign-vue-next';

const currentItem = ref<CollapseProps['modelValue']>([]);
const handlePanelChange: CollapseProps['onChange'] = (val) => {
  console.log(val);
};
</script>
