// skills/tdesign-react/references/examples/tooltip/arrow.tsx
/**
 * TDesign TDesign React 示例：tooltip - arrow
 * 覆盖组件：Tooltip
 * 来源：组件库源码 packages/components/tooltip/_example/arrow.tsx
 */

import React from 'react';
import { Button, Tooltip } from 'tdesign-react';

export default function BasicUsage() {
  return (
    <Tooltip
      content="文字提示仅展示文本内容"
      overlayStyle={{ padding: 2 }}
      overlayInnerStyle={{ padding: 2 }}
      overlayClassName="tooltip-custom-overlay-class"
      overlayInnerClassName="tooltip-custom-overlay-inner-class"
    >
      <Button variant="outline">默认文字提示</Button>
    </Tooltip>
  );
}

// skills/tdesign-vue2/references/examples/tooltip/arrow.vue
<!--
  TDesign TDesign Vue 2 示例：tooltip - arrow
  覆盖组件：Tooltip
  来源：组件库源码 src/tooltip/_example/arrow.vue
-->

<template>
  <div>
    <t-tooltip :onVisibleChange="onVisibleChange">
      <t-button variant="outline">带箭头文字提示</t-button>
      <div slot="content">这是自定义的带箭头文字内容</div>
    </t-tooltip>
  </div>
</template>
<script>
export default {
  methods: {
    onVisibleChange(val) {
      console.log('visible change triggered: ', val);
    },
  },
};
</script>
