// skills/tdesign-vue-next/references/examples/image-viewer/modeless.vue
<!--
  TDesign TDesign Vue Next 示例：image-viewer - modeless
  覆盖组件：Image-viewer
  来源：组件库源码 packages/components/image-viewer/_example/modeless.vue
-->

<template>
  <div class="tdesign-demo-image-viewer__base">
    <t-image-viewer draggable mode="modeless" :images="[img]" :z-index="10000"> </t-image-viewer>
  </div>
</template>

<script lang="ts" setup>
const img = 'https://tdesign.gtimg.com/demo/demo-image-1.png';
</script>

<style scoped>
.tdesign-demo-image-viewer__base {
  width: 160px;
  height: 160px;
  margin: 10px;
  border: 4px solid var(--td-bg-color-secondarycontainer);
  border-radius: var(--td-radius-medium);
}
</style>

// skills/tdesign-react/references/examples/image-viewer/modeless.tsx
/**
 * TDesign TDesign React 示例：image-viewer - modeless
 * 覆盖组件：Image-viewer
 * 来源：组件库源码 packages/components/image-viewer/_example/modeless.tsx
 */

import React from 'react';
import { ImageViewer, Space } from 'tdesign-react';

const img = 'https://tdesign.gtimg.com/demo/demo-image-1.png';

export default function BasicImageViewer() {
  return (
    <Space
      breakLine
      size={16}
      style={{
        width: 160,
        height: 160,
        border: '4px solid var(--td-bg-color-secondarycontainer)',
        borderRadius: 'var(--td-radius-medium)',
      }}
    >
      <ImageViewer draggable mode="modeless" title="预览单张图片" images={[img]} />
    </Space>
  );
}
