// skills/tdesign-react/references/examples/list/image-text.tsx
/**
 * TDesign TDesign React 示例：list - image-text
 * 覆盖组件：List
 * 来源：组件库源码 packages/components/list/_example/image-text.tsx
 */

import React from 'react';
import { List } from 'tdesign-react';

const { ListItem, ListItemMeta } = List;

export default function BasicList() {
  const avatarUrl = 'https://tdesign.gtimg.com/list-icon.png';
  const listData = [
    { id: 1, content: '列表内容列表内容列表内容' },
    { id: 2, content: '列表内容列表内容列表内容' },
    { id: 3, content: '列表内容列表内容列表内容' },
    { id: 4, content: '列表内容列表内容列表内容' },
  ];
  return (
    <List size="small">
      {listData.map((item) => (
        <ListItem key={item.id}>
          <ListItemMeta image={avatarUrl} title="列表主内容" description="列表内容列表内容列表内容" />
        </ListItem>
      ))}
    </List>
  );
}

// skills/tdesign-vue-next/references/examples/list/image-text.vue
<!--
  TDesign TDesign Vue Next 示例：list - image-text
  覆盖组件：List
  来源：组件库源码 packages/components/list/_example/image-text.vue
-->

<template>
  <t-space direction="vertical" size="large">
    <t-list :split="true">
      <t-list-item>
        <t-list-item-meta :image="imageUrl" title="列表标题" description="列表内容的描述性文字" />
      </t-list-item>
      <t-list-item>
        <t-list-item-meta :image="imageUrl" title="列表标题" description="列表内容的描述性文字" />
      </t-list-item>
      <t-list-item>
        <t-list-item-meta :image="imageUrl" title="列表标题" description="列表内容的描述性文字" />
      </t-list-item>
    </t-list>

    <t-list :split="true">
      <t-list-item>
        <t-list-item-meta :image="imageUrl" title="列表标题">
          <template #description>
            <p>列表内容的描述性文字</p>
          </template>
        </t-list-item-meta>
      </t-list-item>
    </t-list>
  </t-space>
</template>
<script lang="ts" setup>
import type { ListItemMetaProps } from 'tdesign-vue-next';

const imageUrl: ListItemMetaProps['image'] = 'https://tdesign.gtimg.com/site/avatar.jpg';
</script>
