// skills/tdesign-vue2/references/examples/tabs/ban.vue
<!--
  TDesign TDesign Vue 2 示例：tabs - ban
  覆盖组件：Tabs
  来源：组件库源码 src/tabs/_example/ban.vue
-->

<template>
  <t-space direction="vertical" size="36px">
    <t-space>
      <t-radio-group variant="default-filled" v-model="theme">
        <t-radio-button value="normal">常规型</t-radio-button>
        <t-radio-button value="card">卡片型</t-radio-button>
      </t-radio-group>
    </t-space>
    <t-tabs :value="value" :theme="theme" @change="(newValue) => (value = newValue)">
      <t-tab-panel value="first" :label="`选项卡1`">
        <p style="padding: 25px">{{ `选项卡1的内容` }}</p>
      </t-tab-panel>
      <t-tab-panel value="second" :label="`选项卡2`" :disabled="true">
        <p style="padding: 25px">{{ `选项卡2的内容` }}</p>
      </t-tab-panel>
      <t-tab-panel value="third" :label="`选项卡3`">
        <p style="padding: 25px">{{ `选项卡3的内容` }}</p>
      </t-tab-panel>
    </t-tabs>
  </t-space>
</template>

<script>
export default {
  data() {
    return {
      theme: 'normal',
      value: 'first',
    };
  },
};
</script>

// skills/tdesign-react/references/examples/tabs/ban.tsx
/**
 * TDesign TDesign React 示例：tabs - ban
 * 覆盖组件：Tabs
 * 来源：组件库源码 packages/components/tabs/_example/ban.tsx
 */

import React, { useState } from 'react';
import { Radio, Space, Tabs } from 'tdesign-react';

import type { TabsProps } from 'tdesign-react';

const { TabPanel } = Tabs;

type ITabsTheme = TabsProps['theme'];

export default function ThemeTabs() {
  const [theme, setTheme] = useState<ITabsTheme>('normal');

  return (
    <Space direction="vertical" size="large" style={{ width: '100%' }}>
      <Radio.Group variant="default-filled" defaultValue="normal" onChange={(val: ITabsTheme) => setTheme(val)}>
        <Radio.Button value="normal">常规型</Radio.Button>
        <Radio.Button value="card">卡片型</Radio.Button>
      </Radio.Group>
      <Tabs placement={'top'} defaultValue={'1'} theme={theme} size={'medium'} disabled={false}>
        <TabPanel value={'1'} label={'选项卡1'}>
          <div style={{ margin: 20 }}>选项卡1内容区</div>
        </TabPanel>
        <TabPanel value={'2'} label={'选项卡2'} disabled>
          <div style={{ margin: 20 }}>选项卡2内容区</div>
        </TabPanel>
        <TabPanel value={'3'} label={'选项卡3'}>
          <div style={{ margin: 20 }}>选项卡3内容区</div>
        </TabPanel>
      </Tabs>
    </Space>
  );
}
