// skills/tdesign-react/references/examples/grid/halign.tsx
/**
 * TDesign TDesign React 示例：grid - halign
 * 覆盖组件：Grid
 * 来源：组件库源码 packages/components/grid/_example/halign.tsx
 */

import React from 'react';
import { Col, Row } from 'tdesign-react';

export default function OrderGrid() {
  return (
    <>
      <p>align left</p>
      <Row justify="start">
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
      </Row>

      <p>align center</p>
      <Row justify="center">
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
      </Row>

      <p>align right</p>
      <Row justify="end">
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
      </Row>

      <p>space-between</p>
      <Row justify="space-between">
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
      </Row>

      <p>space-around</p>
      <Row justify="space-around">
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
        <Col span={2}>
          <div>col-2</div>
        </Col>
      </Row>
    </>
  );
}

// skills/tdesign-vue-next/references/examples/grid/halign.vue
<!--
  TDesign TDesign Vue Next 示例：grid - halign
  覆盖组件：Grid
  来源：组件库源码 packages/components/grid/_example/halign.vue
-->

<template>
  <t-space direction="vertical">
    <span>align left</span>
    <t-row justify="start">
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
    </t-row>

    <span>align center</span>
    <t-row justify="center">
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
    </t-row>

    <span>align right</span>
    <t-row justify="end">
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
    </t-row>

    <span>space-between</span>
    <t-row justify="space-between">
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
    </t-row>

    <span>space-around</span>
    <t-row justify="space-around">
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
      <t-col :span="2">
        <div>col-2</div>
      </t-col>
    </t-row>
  </t-space>
</template>
