// skills/tdesign-react/references/examples/breadcrumb/href.tsx
/**
 * TDesign TDesign React 示例：breadcrumb - href
 * 覆盖组件：Breadcrumb
 * 来源：组件库源码 packages/components/breadcrumb/_example/href.tsx
 */

import React, { useState } from 'react';
import { Breadcrumb } from 'tdesign-react';

const { BreadcrumbItem } = Breadcrumb;

export default function BreadcrumbExample() {
  const [count, setCount] = useState(0);
  return (
    <div>
      <Breadcrumb maxItemWidth="150">
        <BreadcrumbItem href="/" target="_blank">
          页面1
        </BreadcrumbItem>
        <BreadcrumbItem href="/react/components/button" disabled>
          页面2
        </BreadcrumbItem>
        <BreadcrumbItem maxItemWidth="160" onClick={() => setCount(count + 1)}>
          页面3
        </BreadcrumbItem>
      </Breadcrumb>

      <div style={{ marginTop: 20 }}>点击计数器：{count}</div>
    </div>
  );
}

// skills/tdesign-vue-next/references/examples/breadcrumb/href.vue
<!--
  TDesign TDesign Vue Next 示例：breadcrumb - href
  覆盖组件：Breadcrumb
  来源：组件库源码 packages/components/breadcrumb/_example/href.vue
-->

<template>
  <t-space direction="vertical">
    <t-breadcrumb>
      <t-breadcrumb-item :to="{ path: '/' }">首页</t-breadcrumb-item>
      <t-breadcrumb-item to="/vue/components/menu" :replace="true">页面1(覆盖路由)</t-breadcrumb-item>
      <t-breadcrumb-item href="http://tdesign.tencent.com/" :target="'_blank'">页面2</t-breadcrumb-item>
      <t-breadcrumb-item href="http://tdesign.tencent.com/vue/components/button" :disabled="true"
        >页面3(disabled)</t-breadcrumb-item
      >
      <t-breadcrumb-item @click="onClickItem">页面4自定义点击</t-breadcrumb-item>
    </t-breadcrumb>
    <div style="margin-top: 20px">点击计数器：{{ count }}</div>
  </t-space>
</template>
<script lang="tsx" setup>
import { ref } from 'vue';
import type { BreadcrumbItemProps } from 'tdesign-vue-next';

const count = ref(0);
const onClickItem: BreadcrumbItemProps['onClick'] = () => {
  count.value += 1;
};
</script>
