// skills/tdesign-vue2/references/examples/divider/text.vue
<!--
  TDesign TDesign Vue 2 示例：divider - text
  覆盖组件：Divider
  来源：组件库源码 src/divider/_example/text.vue
-->

<template>
  <t-space direction="vertical">
    <p>分割线对内容有分隔和组织的作用，能帮助用户理解页面层次，提升信息获取或内容操作的效率。</p>
    <t-divider align="left">TDesign</t-divider>
    <p>分割线对内容有分隔和组织的作用，能帮助用户理解页面层次，提升信息获取或内容操作的效率。</p>
    <t-divider align="center" dashed>TDesign</t-divider>
    <p>分割线对内容有分隔和组织的作用，能帮助用户理解页面层次，提升信息获取或内容操作的效率。</p>
    <t-divider align="right" dashed>TDesign</t-divider>
    <p>分割线对内容有分隔和组织的作用，能帮助用户理解页面层次，提升信息获取或内容操作的效率。</p>
  </t-space>
</template>

// skills/tdesign-react/references/examples/divider/text.tsx
/**
 * TDesign TDesign React 示例：divider - text
 * 覆盖组件：Divider
 * 来源：组件库源码 packages/components/divider/_example/text.tsx
 */

import React from 'react';
import { Divider } from 'tdesign-react';

export default function BasicDivider() {
  return (
    <>
      <p>
        通过高效广告平台，协助品牌和市场营销者触达数以亿计的中国消费者通过金融科技及企业服务，促进合作伙伴业务发展，助力实现数字化升级，我们大力投资于人才队伍和推动科技创新，积极参与互联网行业协同发展。
      </p>
      <Divider align="left">TDesign</Divider>
      <p>
        通过高效广告平台，协助品牌和市场营销者触达数以亿计的中国消费者通过金融科技及企业服务，促进合作伙伴业务发展，助力实现数字化升级，我们大力投资于人才队伍和推动科技创新，积极参与互联网行业协同发展。
      </p>
      <Divider align="center">TDesign</Divider>
      <p>
        通过高效广告平台，协助品牌和市场营销者触达数以亿计的中国消费者通过金融科技及企业服务，促进合作伙伴业务发展，助力实现数字化升级，我们大力投资于人才队伍和推动科技创新，积极参与互联网行业协同发展。
      </p>
      <Divider align="right">TDesign</Divider>
      <p>
        通过高效广告平台，协助品牌和市场营销者触达数以亿计的中国消费者通过金融科技及企业服务，促进合作伙伴业务发展，助力实现数字化升级，我们大力投资于人才队伍和推动科技创新，积极参与互联网行业协同发展。
      </p>
    </>
  );
}
