// skills/tdesign-vue-next/references/examples/image/extra-always.vue
<!--
  TDesign TDesign Vue Next 示例：image - extra-always
  覆盖组件：Image
  来源：组件库源码 packages/components/image/_example/extra-always.vue
-->

<template>
  <t-space :size="32">
    <t-space direction="vertical">
      <strong :style="{ fontSize: '20px' }">有遮罩</strong>
      <t-image
        src="https://tdesign.gtimg.com/demo/demo-image-1.png"
        :style="{ width: '284px', height: '160px' }"
        :overlay-content="renderMask"
      />
    </t-space>
    <t-space direction="vertical">
      <strong :style="{ fontSize: '20px' }">无遮罩</strong>
      <t-image
        src="https://tdesign.gtimg.com/demo/demo-image-1.png"
        :style="{ width: '284px', height: '160px' }"
        :overlay-content="renderButton"
      />
    </t-space>

    <t-space direction="vertical">
      <strong :style="{ fontSize: '20px' }">插槽使用</strong>
      <t-image src="https://tdesign.gtimg.com/demo/demo-image-1.png" :style="{ width: '284px', height: '160px' }">
        <template #overlayContent>
          <Tag
            shape="mark"
            theme="primary"
            variant="light"
            :style="{ position: 'absolute', right: '8px', bottom: '8px', borderRadius: '3px' }"
          >
            <PrintIcon size="16" /> 高清
          </Tag>
        </template>
      </t-image>
    </t-space>
  </t-space>
</template>

<script lang="tsx" setup>
import { Tag } from 'tdesign-vue-next';
import { PrintIcon } from 'tdesign-icons-vue-next';
import type { ImageProps } from 'tdesign-vue-next';

const renderMask: ImageProps['overlayContent'] = () => (
  <div
    style={{
      background: 'rgba(0,0,0,.4)',
      height: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '14px',
      lineHeight: '22px',
    }}
  >
    <Tag
      shape="mark"
      theme="warning"
      style={{
        borderRadius: '3px',
        background: 'transparent',
        color: '#fff',
      }}
    >
      <PrintIcon size="16" /> 高清
    </Tag>
  </div>
);
const renderButton: ImageProps['overlayContent'] = () => (
  <Tag
    shape="mark"
    theme="primary"
    variant="light"
    style={{
      position: 'absolute',
      right: '8px',
      bottom: '8px',
      borderRadius: '3px',
    }}
  >
    <PrintIcon size="16" /> 高清
  </Tag>
);
</script>

// skills/tdesign-react/references/examples/image/extra-always.tsx
/**
 * TDesign TDesign React 示例：image - extra-always
 * 覆盖组件：Image
 * 来源：组件库源码 packages/components/image/_example/extra-always.tsx
 */

import React from 'react';
import { PrintIcon } from 'tdesign-icons-react';
import { Image, Space, Tag } from 'tdesign-react';

export default function ExtraAlwaysImage() {
  const mask = (
    <div
      style={{
        background: 'rgba(0,0,0,.4)',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 14,
        lineHeight: 22,
      }}
    >
      <Tag
        shape="mark"
        theme="warning"
        style={{
          borderRadius: 3,
          background: 'transparent',
          color: '#fff',
        }}
      >
        <PrintIcon size={16} /> 高清
      </Tag>
    </div>
  );

  const button = (
    <Tag
      shape="mark"
      theme="warning"
      style={{
        position: 'absolute',
        right: 8,
        bottom: 8,
        borderRadius: 3,
        background: 'rgba(236,242,254,1)',
        color: 'rgba(0,82,217,1)',
      }}
    >
      <PrintIcon size={16} /> 高清
    </Tag>
  );

  return (
    <Space size={32}>
      <Space direction="vertical">
        <strong style={{ fontSize: 20 }}>有遮罩</strong>
        <Image
          src="https://tdesign.gtimg.com/demo/demo-image-1.png"
          style={{ width: 284, height: 160 }}
          overlayContent={mask}
        />
      </Space>
      <Space direction="vertical">
        <strong style={{ fontSize: 20 }}>无遮罩</strong>
        <Image
          src="https://tdesign.gtimg.com/demo/demo-image-1.png"
          style={{ width: 284, height: 160 }}
          overlayContent={button}
        />
      </Space>
    </Space>
  );
}
