// skills/tdesign-mobile-react/references/examples/typography/copyable.tsx
/**
 * TDesign TDesign Mobile React 示例：typography - copyable
 * 覆盖组件：Typography
 * 来源：组件库源码 src/typography/_example/copyable.tsx
 */

import React from 'react';
import { SmileIcon } from 'tdesign-icons-react';
import { TypographyText } from 'tdesign-mobile-react';

import './style/index.less';

export default function CopyableDemo() {
  return (
    <div>
      <div className="tdesign-mobile-typography-demo tdesign-mobile-typography-demo--border">
        <TypographyText copyable>这是一段可复制的文本</TypographyText>
      </div>
      <div className="tdesign-mobile-typography-demo">
        <TypographyText
          copyable={{
            suffix: () => <SmileIcon style={{ color: '#0052D9' }} />,
            onCopy: () => {
              console.log('触发 copy 事件，已复制文本');
            },
          }}
        >
          这是一段带自定义图标的可复制的文本
        </TypographyText>
      </div>
    </div>
  );
}

// skills/tdesign-mobile-vue/references/examples/typography/copyable.vue
<!--
  TDesign TDesign Mobile Vue 示例：typography - copyable
  覆盖组件：Typography
  来源：组件库源码 src/typography/demos/copyable.vue
-->

<template>
  <div>
    <div class="tdesign-mobile-typography-demo">
      <t-typography-text copyable>这是一段可复制的文本</t-typography-text>
    </div>
    <div class="tdesign-mobile-typography-demo">
      <t-typography-text :copyable="copyableWithCustomSuffix"> 这是一段带自定义图标的可复制的文本 </t-typography-text>
    </div>
  </div>
</template>

<script setup lang="ts">
import { SmileIcon } from 'tdesign-icons-vue-next';

const copyableWithCustomSuffix = {
  suffix: (h: typeof import('vue').h) => h(SmileIcon, { color: '#00529D' }),
  onCopy: () => {
    console.log('触发 copy 事件，已复制文本');
  },
};
</script>

<style scoped lang="less">
.tdesign-mobile-typography-demo {
  position: relative;
  display: flex;
  padding: 0 16px;
  background-color: var(--bg-color-demo, #fff);

  &:not(:last-child)::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 16px;
    right: 16px;
    border-bottom: 1px solid var(--td-stroke-color, #e7e7e7);
    transform: scaleY(0.5);
  }
}
</style>
