// skills/tdesign-mobile-vue/references/examples/loading/horz.vue
<!--
  TDesign TDesign Mobile Vue 示例：loading - horz
  覆盖组件：Loading
  来源：组件库源码 src/loading/demos/horz.vue
-->

<template>
  <t-loading text="加载中..." />
  <t-loading theme="spinner" text="加载中..." />
</template>

<script lang="ts" setup></script>

<style scoped>
.t-loading {
  margin-right: 40px;
}
</style>

// skills/tdesign-mobile-react/references/examples/loading/horz.tsx
/**
 * TDesign TDesign Mobile React 示例：loading - horz
 * 覆盖组件：Loading
 * 来源：组件库源码 src/loading/_example/horz.tsx
 */

import React from 'react';
import { Loading } from 'tdesign-mobile-react';

export default function HorzLoading() {
  return (
    <>
      <Loading text="加载中..." />
      <Loading theme="spinner" text="加载中..." />
    </>
  );
}
