// skills/tdesign-react/references/examples/time-picker/keyboard.tsx
/**
 * TDesign TDesign React 示例：time-picker - keyboard
 * 覆盖组件：Time-picker
 * 来源：组件库源码 packages/components/time-picker/_example/keyboard.tsx
 */

import React from 'react';
import { TimePicker } from 'tdesign-react';

import type { TimePickerProps } from 'tdesign-react';

export default function KeyboardTimePicker() {
  const handleBlur: TimePickerProps['onBlur'] = (param) => {
    console.log(param, 'onBlur');
  };

  const handleInput: TimePickerProps['onInput'] = (param) => {
    console.log(param, 'onInput');
  };

  const handleFocus: TimePickerProps['onFocus'] = (param) => {
    console.log(param, 'onFocus');
  };

  return (
    <TimePicker
      defaultValue="12:08:00"
      format="HH:mm:ss"
      onBlur={handleBlur}
      onInput={handleInput}
      onFocus={handleFocus}
      allowInput
      clearable
    />
  );
}

// skills/tdesign-vue2/references/examples/time-picker/keyboard.vue
<!--
  TDesign TDesign Vue 2 示例：time-picker - keyboard
  覆盖组件：Time-picker
  来源：组件库源码 src/time-picker/_example/keyboard.vue
-->

<template>
  <t-space direction="vertical">
    <h3>允许输入</h3>
    <t-time-picker v-model="time1" allowInput @blur="blur" @focus="focus" />
    <h3>禁止输入</h3>
    <t-time-picker v-model="time2" :allowInput="false" />
  </t-space>
</template>

<script>
export default {
  name: 'canInput',
  data() {
    return {
      time1: '20:22:33',
      time2: '22:22:22',
    };
  },
  methods: {
    blur(v) {
      console.log('blur');
      console.log(v);
    },
    focus(v) {
      console.log('focus');
      console.log(v);
    },
  },
};
</script>
