// skills/tdesign-vue2/references/examples/radio/group.vue
<!--
  TDesign TDesign Vue 2 示例：radio - group
  覆盖组件：Radio
  来源：组件库源码 src/radio/_example/group.vue
-->

<template>
  <t-space direction="vertical">
    <t-space>
      <t-radio-group name="city" v-model="value" :options="options" allowUncheck @change="onChange"></t-radio-group>
    </t-space>
    <t-space>
      <t-radio-group v-model="value2" @change="onChange2">
        <t-radio value="1" allow-uncheck>选项一</t-radio>
        <t-radio value="2">选项二</t-radio>
        <t-radio value="3">选项三</t-radio>
        <t-radio value="4" disabled>选项四</t-radio>
      </t-radio-group>
    </t-space>
    <t-space>
      <t-radio-group
        name="city"
        v-model="value1"
        :options="options"
        theme="button"
        allowUncheck
        @change="onChange"
      ></t-radio-group>
    </t-space>
  </t-space>
</template>

<script>
export default {
  data() {
    return {
      value: '',
      value1: '',
      value2: '',
      options: [
        {
          value: 1,
          label: '选项一',
          allowUncheck: true,
        },
        {
          value: 2,
          label: '选项二',
        },
        {
          value: '3',
          label: '选项三',
        },
        {
          value: '4',
          label: () => '选项四',
        },
      ],
    };
  },
  methods: {
    onChange(checkedValues) {
      console.log('checkedValues:', this.value, checkedValues);
    },
    onChange2(checkedValues) {
      console.log('checkedValues:', this.value2, checkedValues);
    },
  },
};
</script>

// skills/tdesign-react/references/examples/radio/group.tsx
/**
 * TDesign TDesign React 示例：radio - group
 * 覆盖组件：Radio
 * 来源：组件库源码 packages/components/radio/_example/group.tsx
 */

import React, { useState } from 'react';
import { Radio, Space } from 'tdesign-react';

import type { RadioOption } from 'tdesign-react';

const objOptions: RadioOption[] = [
  {
    value: 'bj',
    label: '北京',
  },
  {
    value: 'sh',
    label: '上海',
  },
  {
    value: 'gz',
    label: '广州',
    disabled: true,
  },
  {
    value: 'sz',
    label: '深圳',
  },
];
// eslint-disable-next-line prefer-const
let itemOptions = ['北京', '上海', '广州', '深圳'];

type ValueType = '北京' | '上海' | '广州' | '深圳';
type FirstCityType = 'bj' | 'sh' | 'gz' | 'sz';

export default function RadioExample() {
  const [city, setCity] = useState<FirstCityType>('bj');
  const [city2, setCity2] = useState<FirstCityType>('sz');
  const [city3, setCity3] = useState<ValueType>('深圳');

  return (
    <Space direction="vertical">
      <Radio.Group value={city} onChange={(val: FirstCityType) => setCity(val)} allowUncheck>
        <Radio value="bj">北京</Radio>
        <Radio value="sh">上海</Radio>
        <Radio value="gz">广州</Radio>
        <Radio value="sz">深圳</Radio>
      </Radio.Group>

      <Radio.Group value={city2} options={objOptions} allowUncheck onChange={(val: FirstCityType) => setCity2(val)} />
      <Radio.Group
        variant="default-filled"
        theme="button"
        value={city2}
        options={objOptions}
        onChange={(val: FirstCityType) => setCity2(val)}
      />

      <Radio.Group theme="button" value={city3} options={itemOptions} onChange={(val: ValueType) => setCity3(val)} />
      <Radio.Group
        variant="primary-filled"
        theme="button"
        value={city3}
        options={itemOptions}
        onChange={(val: ValueType) => setCity3(val)}
      />
    </Space>
  );
}
