// skills/tdesign-react/references/examples/steps/extra.tsx
/**
 * TDesign TDesign React 示例：steps - extra
 * 覆盖组件：Steps
 * 来源：组件库源码 packages/components/steps/_example/extra.tsx
 */

import React, { useState } from 'react';
import { Button, Steps } from 'tdesign-react';

const { StepItem } = Steps;

export default function HorizontalStepsWithNumbers() {
  const [current, setCurrent] = useState(1);

  const preBtn = (
    <Button
      size={'small'}
      onClick={() => {
        setCurrent(current - 1);
      }}
    >
      pre
    </Button>
  );

  const preTextBtn = (
    <Button
      size={'small'}
      variant="text"
      onClick={() => {
        setCurrent(current - 1);
      }}
    >
      pre
    </Button>
  );

  const nextBtn = (
    <Button
      size={'small'}
      onClick={() => {
        setCurrent(current + 1);
      }}
    >
      Next
    </Button>
  );

  const preNextBtnGroup = (
    <>
      {preTextBtn}
      <div style={{ display: 'inline', marginLeft: 4 }}>{nextBtn}</div>
    </>
  );

  return (
    <Steps layout="vertical" defaultCurrent={current}>
      <StepItem title="步骤1" content="这里是提示文字">
        {current === 0 ? nextBtn : null}
      </StepItem>
      <StepItem title="步骤2" content="这里是提示文字">
        {current === 1 ? preNextBtnGroup : null}
      </StepItem>
      <StepItem title="步骤3" content="这里是提示文字">
        {current === 2 ? preNextBtnGroup : null}
      </StepItem>
      <StepItem title="步骤4" content="这里是提示文字">
        {current === 3 ? preBtn : null}
      </StepItem>
    </Steps>
  );
}

// skills/tdesign-vue2/references/examples/steps/extra.vue
<!--
  TDesign TDesign Vue 2 示例：steps - extra
  覆盖组件：Steps
  来源：组件库源码 src/steps/_example/extra.vue
-->

<template>
  <t-steps layout="vertical" :current="current" :onChange="onCurChanged">
    <t-step-item :title="renderTitle" content="这里是提示文字">
      <template slot="extra" v-if="current === 0">
        <t-button size="small" variant="base" @click.stop="current++">下一步</t-button>
      </template>
    </t-step-item>
    <t-step-item title="步骤2" content="这里是提示文字">
      <template slot="extra" v-if="current === 1">
        <t-space size="small">
          <t-button size="small" variant="text" @click.stop="current--">上一步</t-button>
          <t-button size="small" variant="base" @click.stop="current++">下一步</t-button>
        </t-space>
      </template>
    </t-step-item>
    <t-step-item title="步骤3" content="这里是提示文字">
      <template slot="extra" v-if="current === 2">
        <t-space size="small">
          <t-button size="small" variant="text" @click.stop="current--">上一步</t-button>
          <t-button size="small" variant="base" @click.stop="current++">下一步</t-button>
        </t-space>
      </template>
    </t-step-item>
    <t-step-item title="步骤4" content="这里是提示文字">
      <template slot="extra" v-if="current === 3">
        <t-button size="small" @click.stop="current--">上一步</t-button>
      </template>
    </t-step-item>
  </t-steps>
</template>

<script lang="jsx">
export default {
  data() {
    return {
      current: 1,
    };
  },
  methods: {
    onCurChanged(cur, pre) {
      this.current = cur;
      console.log('TDesign Steps:', `current: ${cur}, previous: ${pre}`);
    },
    renderTitle() {
      return <div class="demo">步骤1</div>;
    },
  },
};
</script>
