// skills/tdesign-react/references/examples/steps/vertical-sequence.tsx
/**
 * TDesign TDesign React 示例：steps - vertical-sequence
 * 覆盖组件：Steps
 * 来源：组件库源码 packages/components/steps/_example/vertical-sequence.tsx
 */

import React from 'react';
import { Steps } from 'tdesign-react';

const { StepItem } = Steps;

export default function HorizontalStepsWithNumbers() {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
      <Steps layout="vertical" defaultCurrent={1}>
        <StepItem title="已完成的步骤" content="这里是提示文字" />
        <StepItem title="进行中的步骤" content="这里是提示文字" />
        <StepItem title="未进行的步骤" content="这里是提示文字" />
        <StepItem title="未进行的步骤" content="这里是提示文字" />
      </Steps>
      <Steps layout="vertical" sequence="reverse" defaultCurrent={1}>
        <StepItem title="已完成的步骤" content="这里是提示文字" />
        <StepItem title="已完成的步骤" content="这里是提示文字" />
        <StepItem title="进行中的步骤" content="这里是提示文字" />
        <StepItem title="未进行的步骤" content="这里是提示文字" />
      </Steps>
    </div>
  );
}

// skills/tdesign-vue2/references/examples/steps/vertical-sequence.vue
<!--
  TDesign TDesign Vue 2 示例：steps - vertical-sequence
  覆盖组件：Steps
  来源：组件库源码 src/steps/_example/vertical-sequence.vue
-->

<template>
  <t-space :size="236" class="justify-around">
    <t-steps layout="vertical" :current="1" readonly>
      <t-step-item title="已完成的步骤" content="这里是提示文字"></t-step-item>
      <t-step-item title="进行中的步骤" content="这里是提示文字"></t-step-item>
      <t-step-item title="未进行的步骤" content="这里是提示文字"></t-step-item>
      <t-step-item title="未进行的步骤" content="这里是提示文字"></t-step-item>
    </t-steps>
    <t-steps layout="vertical" sequence="reverse" :current="1" readonly>
      <t-step-item title="已完成的步骤" content="这里是提示文字"></t-step-item>
      <t-step-item title="已完成的步骤" content="这里是提示文字"></t-step-item>
      <t-step-item title="进行中的步骤" content="这里是提示文字"></t-step-item>
      <t-step-item title="未进行的步骤" content="这里是提示文字"></t-step-item>
    </t-steps>
  </t-space>
</template>

<style scoped>
.justify-around {
  justify-content: space-around;
}
</style>
