// skills/tdesign-vue-next/references/examples/badge/offset.vue
<!--
  TDesign TDesign Vue Next 示例：badge - offset
  覆盖组件：Badge
  来源：组件库源码 packages/components/badge/_example/offset.vue
-->

<template>
  <t-space size="large">
    <t-badge count="2">
      <div class="badge-block" />
    </t-badge>

    <t-badge count="2" :offset="[10, 10]">
      <div class="badge-block" />
    </t-badge>

    <t-badge count="2" :offset="[-10, 10]">
      <div class="badge-block" />
    </t-badge>

    <t-badge count="2" :offset="[-10, -10]">
      <div class="badge-block" />
    </t-badge>

    <t-badge count="2" :offset="[10, -10]">
      <div class="badge-block" />
    </t-badge>
  </t-space>
</template>

<style>
.badge-block {
  width: 40px;
  height: 40px;
  background: #eeeeee;
  border: 1px solid #dcdcdc;
  box-sizing: border-box;
  border-radius: 3px;
}
</style>

// skills/tdesign-react/references/examples/badge/offset.tsx
/**
 * TDesign TDesign React 示例：badge - offset
 * 覆盖组件：Badge
 * 来源：组件库源码 packages/components/badge/_example/offset.tsx
 */

import React from 'react';
import { Badge, Button } from 'tdesign-react';

export default function BadgeExample() {
  return (
    <>
      <Badge count={2}>
        <Button>默认</Button>
      </Badge>
      <Badge count={2} offset={[10, 10]}>
        <Button>[10,10]</Button>
      </Badge>
      <Badge count={2} offset={[-10, 10]}>
        <Button>[-10,10]</Button>
      </Badge>
      <Badge count={2} offset={[-10, -10]}>
        <Button>[-10,-10]</Button>
      </Badge>
      <Badge count={2} offset={[10, -10]}>
        <Button>[10,-10]</Button>
      </Badge>
    </>
  );
}
