// skills/tdesign-vue-next/references/examples/grid/offset.vue
<!--
  TDesign TDesign Vue Next 示例：grid - offset
  覆盖组件：Grid
  来源：组件库源码 packages/components/grid/_example/offset.vue
-->

<template>
  <t-space direction="vertical">
    <t-row>
      <t-col :span="4">
        <div>col-4</div>
      </t-col>
      <t-col :span="4" :offset="4">
        <div>col-4 col-offset-4</div>
      </t-col>
    </t-row>

    <t-row>
      <t-col :span="3" :offset="3">
        <div>col-3 col-offset-3</div>
      </t-col>
      <t-col :span="3" :offset="3">
        <div>col-3 col-offset-3</div>
      </t-col>
    </t-row>

    <t-row>
      <t-col :span="6" :offset="3">
        <div>col-6 col-offset-3</div>
      </t-col>
    </t-row>
  </t-space>
</template>

// skills/tdesign-react/references/examples/badge/offset.tsx
/**
 * TDesign TDesign React 示例：badge - offset
 * 覆盖组件：Badge
 * 来源：组件库源码 packages/components/badge/_example/offset.tsx
 */

import React from 'react';
import { Badge, Button } from 'tdesign-react';

export default function BadgeExample() {
  return (
    <>
      <Badge count={2}>
        <Button>默认</Button>
      </Badge>
      <Badge count={2} offset={[10, 10]}>
        <Button>[10,10]</Button>
      </Badge>
      <Badge count={2} offset={[-10, 10]}>
        <Button>[-10,10]</Button>
      </Badge>
      <Badge count={2} offset={[-10, -10]}>
        <Button>[-10,-10]</Button>
      </Badge>
      <Badge count={2} offset={[10, -10]}>
        <Button>[10,-10]</Button>
      </Badge>
    </>
  );
}
