// skills/tdesign-vue2/references/examples/anchor/customize-highlight.vue
<!--
  TDesign TDesign Vue 2 示例：anchor - customize-highlight
  覆盖组件：Anchor
  来源：组件库源码 src/anchor/_example/customize-highlight.vue
-->

<template>
  <t-space>
    <div class="flex: 1"></div>
    <t-anchor :bounds="150" :getCurrentAnchor="getCurrentAnchor">
      <t-anchor-item href="#基础锚点" title="基础锚点"></t-anchor-item>
      <t-anchor-item href="#多级锚点" title="多级锚点"></t-anchor-item>
      <t-anchor-item href="#指定容器锚点" title="指定容器锚点"></t-anchor-item>
      <t-anchor-item href="#特定交互锚点" title="特定交互锚点"></t-anchor-item>
      <t-anchor-item href="#尺寸" title="尺寸">
        <t-anchor-item href="#size-1" title="尺寸1">
          <div id="default">this is children content</div>
          <div>sdadasas</div>
        </t-anchor-item>
        <t-anchor-item href="#size-2" title="尺寸2">
          <t-anchor-item href="#size-3" title="尺寸1"></t-anchor-item>
        </t-anchor-item>
      </t-anchor-item>
    </t-anchor>
  </t-space>
</template>
<script>
export default {
  data() {
    return {
      getCurrentAnchor(value) {
        console.log('value1', value);
        return value || '#多级锚点';
      },
    };
  },
};
</script>

// skills/tdesign-react/references/examples/anchor/customize-highlight.tsx
/**
 * TDesign TDesign React 示例：anchor - customize-highlight
 * 覆盖组件：Anchor
 * 来源：组件库源码 packages/components/anchor/_example/customize-highlight.tsx
 */

import React from 'react';
import { Anchor } from 'tdesign-react';

const { AnchorItem } = Anchor;

export default function AnchorBase() {
  return (
    <div style={{ display: 'flex' }}>
      <div style={{ flex: '1' }}></div>
      <Anchor getCurrentAnchor={() => '#基础锚点'}>
        <AnchorItem href="#基础锚点" title="基础锚点" />
        <AnchorItem href="#多级锚点" title="多级锚点" />
        <AnchorItem href="#自定义游标锚点" title="自定义游标锚点" />
        <AnchorItem href="#指定容器锚点" title="指定容器锚点" />
        <AnchorItem href="#特定交互锚点" title="特定交互锚点" />
        <AnchorItem href="#不同尺寸的锚点" title="不同尺寸的锚点" />
        <AnchorItem href="#自定义锚点高亮" title="自定义锚点高亮" />
      </Anchor>
    </div>
  );
}
