// skills/tdesign-vue-next/references/examples/steps/no-sequence.vue
<!--
  TDesign TDesign Vue Next 示例：steps - no-sequence
  覆盖组件：Steps
  来源：组件库源码 packages/components/steps/_example/no-sequence.vue
-->

<template>
  <t-steps theme="dot" :current="current" readonly>
    <t-step-item title="已完成的步骤" content="这里是提示文字" />
    <t-step-item title="进行中的步骤" content="这里是提示文字" />
    <t-step-item title="未进行的步骤" content="这里是提示文字" />
    <t-step-item title="未进行的步骤" content="这里是提示文字" />
  </t-steps>
</template>

<script lang="ts" setup>
import type { StepsProps } from 'tdesign-vue-next';

const current: StepsProps['current'] = 1;
</script>

// skills/tdesign-react/references/examples/steps/no-sequence.tsx
/**
 * TDesign TDesign React 示例：steps - no-sequence
 * 覆盖组件：Steps
 * 来源：组件库源码 packages/components/steps/_example/no-sequence.tsx
 */

import React from 'react';
import { Steps } from 'tdesign-react';

const { StepItem } = Steps;

export default function HorizontalStepsWithNumbers() {
  return (
    <Steps theme="dot" defaultCurrent={1}>
      <StepItem title="已完成的步骤" content="这里是提示文字" />
      <StepItem title="进行中的步骤" content="这里是提示文字" />
      <StepItem title="未进行的步骤" content="这里是提示文字" />
      <StepItem title="未进行的步骤" content="这里是提示文字" />
    </Steps>
  );
}
