// skills/tdesign-vue-next/references/examples/menu/custom-header.vue
<!--
  TDesign TDesign Vue Next 示例：menu - custom-header
  覆盖组件：Menu
  来源：组件库源码 packages/components/menu/_example/custom-header.vue
-->

<template>
  <t-head-menu theme="dark" default-value="item2">
    <t-menu-item value="item1"> 菜单内容一 </t-menu-item>
    <t-menu-item value="item2"> 已选内容 </t-menu-item>
    <t-menu-item value="item3"> 菜单内容二 </t-menu-item>
    <t-menu-item value="item4" :disabled="true"> 菜单内容三 </t-menu-item>
    <template #operations>
      <div class="t-demo-menu--dark">
        <t-button variant="text" shape="square">
          <template #icon><t-icon name="search" /></template>
        </t-button>
        <t-button variant="text" shape="square">
          <template #icon><t-icon name="mail" /></template>
        </t-button>
        <t-button variant="text" shape="square">
          <template #icon><t-icon name="user" /></template>
        </t-button>
        <t-button variant="text" shape="square">
          <template #icon><t-icon name="ellipsis" /></template>
        </t-button>
      </div>
    </template>
  </t-head-menu>
</template>

<style lang="less" scoped>
.t-menu__operations {
  .t-button {
    margin-left: 8px;
  }
}
.t-demo-menu--dark {
  .t-button {
    color: #fff;
    &:hover {
      background-color: #4b4b4b;
      border-color: transparent;
      --ripple-color: #383838;
    }
  }
}
</style>

// skills/tdesign-react/references/examples/menu/custom-header.tsx
/**
 * TDesign TDesign React 示例：menu - custom-header
 * 覆盖组件：Menu
 * 来源：组件库源码 packages/components/menu/_example/custom-header.tsx
 */

import React, { Fragment, useState } from 'react';
import { EllipsisIcon, MailIcon, SearchIcon, UserIcon } from 'tdesign-icons-react';
import { Button, Menu } from 'tdesign-react';

import type { MenuValue } from 'tdesign-react';

const { HeadMenu, MenuItem } = Menu;

function Single() {
  const [active, setActive] = useState<MenuValue>('0');
  const [darkActive, setDarkActive] = useState<MenuValue>('1');

  const operations = () => (
    <div className="tdesign-demo-menu__operations">
      <Button variant="text" shape="square" icon={<SearchIcon />} />
      <Button variant="text" shape="square" icon={<MailIcon />} />
      <Button variant="text" shape="square" icon={<UserIcon />} />
      <Button variant="text" shape="square" icon={<EllipsisIcon />} />
    </div>
  );

  const operationsDark = () => (
    <div className="tdesign-demo-menu__operations--dark">
      <Button variant="text" shape="square" icon={<SearchIcon />} />
      <Button variant="text" shape="square" icon={<MailIcon />} />
      <Button variant="text" shape="square" icon={<UserIcon />} />
      <Button variant="text" shape="square" icon={<EllipsisIcon />} />
    </div>
  );

  return (
    <Fragment>
      <HeadMenu
        value={active}
        onChange={(v) => setActive(v)}
        logo={<img src="https://tdesign.gtimg.com/site/baseLogo-light.png" height="28" alt="logo" />}
        operations={operations()}
        style={{ marginBottom: 20 }}
      >
        <MenuItem value={'0'}>
          <span>菜单1</span>
        </MenuItem>
        <MenuItem value={'1'}>
          <span>菜单2</span>
        </MenuItem>
        <MenuItem value={'2'}>
          <span>菜单3</span>
        </MenuItem>
        <MenuItem value={'3'}>
          <span>菜单4</span>
        </MenuItem>
      </HeadMenu>
      {/* 暗黑模式 */}
      <HeadMenu
        theme="dark"
        value={darkActive}
        onChange={(v) => setDarkActive(v)}
        logo={
          <img className="margin_0" src="https://tdesign.gtimg.com/site/baseLogo-dark.png" height="28" alt="logo" />
        }
        operations={operationsDark()}
      >
        <MenuItem value={'0'}>
          <span>菜单1</span>
        </MenuItem>
        <MenuItem value={'1'}>
          <span>菜单2</span>
        </MenuItem>
        <MenuItem value={'2'}>
          <span>菜单3</span>
        </MenuItem>
        <MenuItem value={'3'}>
          <span>菜单4</span>
        </MenuItem>
      </HeadMenu>
    </Fragment>
  );
}

export default Single;
