// skills/tdesign-mobile-vue/references/examples/grid/desc.vue
<!--
  TDesign TDesign Mobile Vue 示例：grid - desc
  覆盖组件：Grid
  来源：组件库源码 src/grid/demos/desc.vue
-->

<template>
  <t-grid :column="3" class="grid-demo">
    <t-grid-item text="标题文字" :image="imgUrl" description="描述文字" />
    <t-grid-item text="标题文字" :image="imgUrl" description="描述文字" />
    <t-grid-item text="标题最多六字" :image="imgUrl" description="描述最多六字" />
  </t-grid>
  <t-grid :column="2" class="grid-demo">
    <t-grid-item text="标题文字" layout="horizontal" :image="imgUrl" description="描述文字" />
    <t-grid-item text="标题文字" layout="horizontal" :image="imgUrl" description="描述文字" />
  </t-grid>
</template>
<script lang="ts" setup>
const imgUrl = 'https://tdesign.gtimg.com/mobile/demos/example1.png';
</script>
<style scoped lang="less">
.grid-demo {
  margin-bottom: 16px;
}
</style>

// skills/tdesign-mobile-react/references/examples/grid/desc.tsx
/**
 * TDesign TDesign Mobile React 示例：grid - desc
 * 覆盖组件：Grid
 * 来源：组件库源码 src/grid/_example/desc.tsx
 */

import React from 'react';
import { Grid, GridItem } from 'tdesign-mobile-react';

import './style/index.less';

const imgUrl = 'https://tdesign.gtimg.com/mobile/demos/example1.png';

export default function Desc() {
  return (
    <>
      <Grid column={3} className={'grid-demo'}>
        <GridItem text="标题文字" image={imgUrl} description="描述文字" />
        <GridItem text="标题文字" image={imgUrl} description="描述文字" />
        <GridItem text="最多六个文字" image={imgUrl} description="描述最多六字" />
      </Grid>
      <Grid column={2} className={'grid-demo'}>
        <GridItem text="标题文字" image={imgUrl} description="描述文字" />
        <GridItem text="标题文字" image={imgUrl} description="描述文字" />
      </Grid>
    </>
  );
}
