// skills/tdesign-mobile-vue/references/examples/grid/scroll.vue
<!--
  TDesign TDesign Mobile Vue 示例：grid - scroll
  覆盖组件：Grid
  来源：组件库源码 src/grid/demos/scroll.vue
-->

<template>
  <t-grid :column="0" class="grid-demo">
    <t-grid-item v-for="item in 10" :key="item" text="标题文字" :image="imgUrl" />
  </t-grid>
</template>

<script lang="ts" setup>
const imgUrl = 'https://tdesign.gtimg.com/mobile/demos/example1.png';
</script>
<style scoped lang="less">
.grid-demo {
  margin-bottom: 16px;
}
</style>

// skills/tdesign-mobile-react/references/examples/grid/scroll.tsx
/**
 * TDesign TDesign Mobile React 示例：grid - scroll
 * 覆盖组件：Grid
 * 来源：组件库源码 src/grid/_example/scroll.tsx
 */

import React from 'react';
import { Grid, GridItem } from 'tdesign-mobile-react';

import './style/index.less';

const imgUrl = 'https://tdesign.gtimg.com/mobile/demos/example1.png';

export default function Scroll() {
  return (
    <>
      <Grid column={0} className={'grid-demo'}>
        {Array.from({ length: 10 }, (_, index) => (
          <GridItem key={index} text="标题文字" image={imgUrl} />
        ))}
      </Grid>
    </>
  );
}
