// skills/tdesign-react/references/examples/textarea/maxlength.tsx
/**
 * TDesign TDesign React 示例：textarea - maxlength
 * 覆盖组件：Textarea
 * 来源：组件库源码 packages/components/textarea/_example/maxlength.tsx
 */

import React from 'react';
import { Space, Textarea } from 'tdesign-react';

export default function InputExample() {
  return (
    <Space direction="vertical" style={{ width: '100%' }}>
      <Textarea placeholder="请输入内容，超出限制无法输入" tips="这里可以放一些提示文字" maxlength={20} />
      <Textarea placeholder="请输入内容，超出限制可以输入" maxlength={20} allowInputOverMax />
      <Textarea placeholder="请输入内容，一个中文汉字表示两个字符长度，超出限制无法输入" maxcharacter={20} />
      <Textarea
        placeholder="请输入内容，一个中文汉字表示两个字符长度，超出限制可以输入"
        maxcharacter={20}
        allowInputOverMax
      />
      <Textarea
        placeholder="自定义计数元素"
        maxlength={20}
        count={(ctx) => {
          const isMaxReached = ctx.count >= ctx.maxLength;
          return (
            <div style={{ fontSize: '12px' }}>
              <span style={{ color: isMaxReached ? 'red' : 'gray' }}>{ctx.count}</span>/
              <span style={{ color: 'mediumblue' }}>{ctx.maxLength}</span>
            </div>
          );
        }}
      />
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/textarea/maxlength.vue
<!--
  TDesign TDesign Vue Next 示例：textarea - maxlength
  覆盖组件：Textarea
  来源：组件库源码 packages/components/textarea/_example/maxlength.vue
-->

<template>
  <t-space direction="vertical">
    <t-textarea
      v-model="value"
      tips="这里可以放一些提示文字"
      placeholder="请输入描述文案，文本长度最多20，maxlength=20"
      :maxlength="20"
    ></t-textarea>

    <t-textarea
      v-model="value2"
      placeholder="请输入描述文案，最多20字符（一个汉字占两个字符长度），maxcharacter=20"
      :maxcharacter="20"
    ></t-textarea>
  </t-space>
</template>
<script lang="ts" setup>
import { ref } from 'vue';

const value = ref('');
const value2 = ref('');
</script>
