// skills/tdesign-react/references/examples/guide/custom-popup.tsx
/**
 * TDesign TDesign React 示例：guide - custom-popup
 * 覆盖组件：Guide
 * 来源：组件库源码 packages/components/guide/_example/custom-popup.tsx
 */

import React, { useEffect } from 'react';
import { ArrowUpIcon } from 'tdesign-icons-react';
import { Button, Drawer, Guide, Input, Row } from 'tdesign-react';

import type { GuideProps, GuideStep } from 'tdesign-react';

const classStyles = `
<style>
.guide-container {
  max-width: 600px;
  padding: 40px;
}

.title-major {
  color: var(--td-text-color-primary);
  font-size: 36px;
  font-weight: 700;
  line-height: 44px;
}

.title-sub {
  margin-top: 8px;
  color: var(--td-text-color-secondary);
  font-size: 14px;
  font-weight: 400;
  line-height: 22px;
}

.field {
  margin-top: 50px;
}

.label {
  margin-bottom: 8px;
  color: var(--td-text-color-primary);
  font-size: 14px;
  font-weight: 400;
  line-height: 22px;
}

.action {
  display: inline-flex;
  margin-top: 50px;
}

.action button:first-child {
  margin-right: 10px;
}


.my-popup {
  width: 240px;
}

.pop-icon {
  margin-top: 10px;
  color: white;
  font-size: 30px;
  font-weight: bold;
}

.popup-desc {
  margin-top: 10px;
  color: rgba(255, 255, 255, 0.9);
  font-size: 12px;
  font-weight: 400;
  text-align: left;
  line-height: 20px;
}

.popup-action {
  margin-top: 10px;
  text-align: right;
}

.popup-action button {
  margin-left: 8px;
}
</style>
`;

function MyPopup(props: any) {
  useEffect(() => {
    // 添加示例代码所需样式
    document.head.insertAdjacentHTML('beforeend', classStyles);
  }, []);

  const { handlePrev, handleNext, handleSkip, handleFinish, current, total } = props;

  return (
    <div className="my-popup">
      <ArrowUpIcon className="pop-icon" />
      <p className="popup-desc">自定义的图形或说明文案，用来解释或指导该功能使用。</p>
      <div className="popup-action">
        <Button theme="default" size="small" onClick={handleSkip}>
          跳过
        </Button>
        {current !== 0 && (
          <Button theme="default" size="small" onClick={handlePrev}>
            上一步
          </Button>
        )}
        {current + 1 < total && (
          <Button theme="primary" size="small" onClick={handleNext}>
            下一步
          </Button>
        )}
        {current + 1 === total && (
          <Button theme="primary" size="small" onClick={handleFinish}>
            完成
          </Button>
        )}
      </div>
    </div>
  );
}

export default function CustomPopupGuide() {
  useEffect(() => {
    // 添加示例代码所需样式
    document.head.insertAdjacentHTML('beforeend', classStyles);
  }, []);

  const [visible, setVisible] = React.useState(false);
  const [current, setCurrent] = React.useState(-1);

  const handleClick = () => {
    setVisible(true);
    setTimeout(() => {
      setCurrent(0);
    }, 800);
  };

  const handleChange: GuideProps['onChange'] = (current: number, { e, total }) => {
    setCurrent(current);
    console.log(current, e, total);
  };

  const handlePrevStepClick: GuideProps['onPrevStepClick'] = ({ e, prev, current, total }) => {
    console.log(e, prev, current, total);
  };

  const handleNextStepClick: GuideProps['onNextStepClick'] = ({ e, next, current, total }) => {
    console.log(e, next, current, total);
  };

  const handleFinish: GuideProps['onFinish'] = ({ e, current, total }) => {
    setVisible(false);
    console.log(e, current, total);
  };

  const handleSkip: GuideProps['onSkip'] = ({ e, current, total }) => {
    console.log('skip');
    setVisible(false);
    console.log(e, current, total);
  };

  const steps: GuideStep[] = [
    {
      element: '.main-title-custom-popup',
      title: '新手引导标题',
      // description: '新手引导的说明文案',
      placement: 'bottom-right',
      content: <MyPopup />,
    },
    {
      element: '.label-field-1-custom-popup',
      title: '新手引导标题',
      // description: '新手引导的说明文案',
      placement: 'bottom',
      content: <MyPopup />,
    },
    {
      element: '.label-field-2-custom-popup',
      title: '新手引导标题',
      // description: '新手引导的说明文案',
      placement: 'bottom-left',
      content: <MyPopup />,
    },
  ];

  return (
    <Row justify="center">
      <Button onClick={handleClick}>新手引导</Button>
      <Drawer
        footer={<Button onClick={() => setVisible(false)}> 关闭抽屉 </Button>}
        visible={visible}
        header="演示新手引导"
        size="60%"
        showOverlay={false}
        destroyOnClose={true}
      >
        <div className="guide-container">
          <div className="main-title-custom-popup">
            <div className="title-major">Guide 用户引导</div>
            <div className="title-sub">按钮用于开启一个闭环的操作任务，如“删除”对象、“购买”商品等。</div>
          </div>
          <div className="field label-field-1-custom-popup">
            <div className="label">Label</div>
            <Input placeholder="请输入内容" />
          </div>
          <div className="field label-field-2-custom-popup">
            <div className="label">Label</div>
            <Input placeholder="请输入内容" />
          </div>
          <Row className="action">
            <Button>确定</Button>
            <Button theme="default" variant="base">
              取消
            </Button>
          </Row>
        </div>

        <Guide
          current={current}
          steps={steps}
          onChange={handleChange}
          onPrevStepClick={handlePrevStepClick}
          onNextStepClick={handleNextStepClick}
          onFinish={handleFinish}
          onSkip={handleSkip}
        />
      </Drawer>
    </Row>
  );
}

// skills/tdesign-vue2/references/examples/guide/custom-popup.vue
<!--
  TDesign TDesign Vue 2 示例：guide - custom-popup
  覆盖组件：Guide
  来源：组件库源码 src/guide/_example/custom-popup.vue
-->

<template>
  <t-row justify="center">
    <t-button @click="handleClick">新手引导</t-button>
    <t-drawer :visible.sync="visible" header="演示新手引导" size="60%" :show-overlay="false" destroy-on-close>
      <template #footer>
        <t-button @click="visible = false"> 关闭抽屉 </t-button>
      </template>
      <div class="guide-container">
        <div class="main-title-popup">
          <div class="title-major">Guide 用户引导</div>
          <div class="title-sub">按钮用于开启一个闭环的操作任务，如“删除”对象、“购买”商品等。</div>
        </div>
        <div class="field label-field-1">
          <div class="label">Label</div>
          <t-input placeholder="请输入内容" />
        </div>
        <div class="field label-field-2">
          <div class="label">Label</div>
          <t-input placeholder="请输入内容" />
        </div>
        <t-row class="action">
          <t-button>确定</t-button>
          <t-button theme="default" variant="base">取消</t-button>
        </t-row>
      </div>

      <t-guide
        :current.sync="current"
        :steps="steps"
        @change="handleChange"
        @prev-step-click="handlePrevStepClick"
        @next-step-click="handleNextStepClick"
        @finish="handleFinish"
        @skip="handleSkip"
      />
    </t-drawer>
  </t-row>
</template>

<script lang="jsx">
import MyPopup from './my-popup.vue';

export default {
  data() {
    return {
      visible: false,
      current: -1,
      steps: [
        {
          element: '.main-title-popup',
          title: '新手引导标题',
          description: '新手引导的说明文案',
          placement: 'bottom-right',
          content: MyPopup,
        },
        {
          element: '.label-field-1',
          title: '新手引导标题',
          description: '新手引导的说明文案',
          placement: 'bottom',
          content: MyPopup,
        },
        {
          element: '.label-field-2',
          title: '新手引导标题',
          description: '新手引导的说明文案',
          placement: 'bottom-left',
          content: MyPopup,
        },
      ],
    };
  },
  methods: {
    handleClick() {
      this.visible = true;
      setTimeout(() => {
        this.current = 0;
      }, 1000);
    },
    handleChange(current, { e, total }) {
      console.log(current, e, total);
    },

    handlePrevStepClick({
      e, prev, current, total,
    }) {
      console.log(e, prev, current, total);
    },

    handleNextStepClick({
      e, next, current, total,
    }) {
      console.log(e, next, current, total);
    },

    handleFinish({ e, current, total }) {
      this.visible = false;
      console.log(e, current, total);
    },

    handleSkip({ e, current, total }) {
      this.visible = false;
      console.log(e, current, total);
    },
  },
};
</script>

<style scoped>
.guide-container {
  max-width: 600px;
  padding: 40px;
}

.title-major {
  color: var(--td-text-color-primary);
  font-size: 36px;
  font-weight: 700;
  line-height: 44px;
}

.title-sub {
  margin-top: 8px;
  color: var(--td-text-color-secondary);
  font-size: 14px;
  font-weight: 400;
  line-height: 22px;
}

.field {
  margin-top: 50px;
}

.label {
  margin-bottom: 8px;
  color: var(--td-text-color-primary);
  font-size: 14px;
  font-weight: 400;
  line-height: 22px;
}

.action {
  display: inline-flex;
  margin-top: 50px;
}

.action button:first-child {
  margin-right: 10px;
}
</style>
