// skills/tdesign-mobile-react/references/examples/swiper/card.tsx
/**
 * TDesign TDesign Mobile React 示例：swiper - card
 * 覆盖组件：Swiper
 * 来源：组件库源码 src/swiper/_example/card.tsx
 */

import React from 'react';
import { Swiper } from 'tdesign-mobile-react';
import './style/index.less';

export default function Base() {
  const imageCdn = 'https://tdesign.gtimg.com/mobile/demos';
  const imageList = [
    `${imageCdn}/swiper1.png`,
    `${imageCdn}/swiper2.png`,
    `${imageCdn}/swiper1.png`,
    `${imageCdn}/swiper2.png`,
    `${imageCdn}/swiper1.png`,
  ];

  const swiperItems = () => (
    <>
      {imageList.map((item, index) => (
        <Swiper.SwiperItem key={index}>
          <img style={{ height: '192px' }} src={item} />
        </Swiper.SwiperItem>
      ))}
    </>
  );

  return (
    <>
      <div className="tdesign-demo-block-wrap">
        <Swiper
          type="card"
          height="192px"
          interval={3000}
          duration={500}
          autoplay={true}
          defaultCurrent={1}
          previousMargin="34px"
          nextMargin="34px"
          navigation={{ type: 'dots', placement: 'outside' }}
        >
          {swiperItems()}
        </Swiper>
      </div>
      <div className="tdesign-demo-block-wrap card-height">
        <Swiper
          type="card"
          height="192px"
          interval={3000}
          duration={500}
          autoplay={true}
          defaultCurrent={1}
          previousMargin="34px"
          nextMargin="34px"
          navigation={{ type: 'dots', placement: 'outside' }}
        >
          {swiperItems()}
        </Swiper>
      </div>
      <div className="tdesign-demo-block-wrap card-height card-prev-next">
        <Swiper
          type="card"
          height="192px"
          interval={3000}
          duration={500}
          autoplay={true}
          defaultCurrent={1}
          previousMargin="34px"
          nextMargin="34px"
          navigation={{ type: 'dots', placement: 'outside' }}
        >
          {swiperItems()}
        </Swiper>
      </div>
    </>
  );
}

// skills/tdesign-mobile-vue/references/examples/swiper/card.vue
<!--
  TDesign TDesign Mobile Vue 示例：swiper - card
  覆盖组件：Swiper
  来源：组件库源码 src/swiper/demos/card.vue
-->

<template>
  <t-swiper
    type="card"
    :navigation="{ type: 'dots' }"
    :previous-margin="12"
    :next-margin="12"
    :autoplay="false"
    @change="handleChange"
  >
    <t-swiper-item v-for="(item, index) in swiperList" :key="index">
      <img :src="item" class="img" />
    </t-swiper-item>
  </t-swiper>
</template>
<script lang="ts" setup>
const imageCdn = 'https://tdesign.gtimg.com/mobile/demos';
const swiperList = [
  `${imageCdn}/swiper1.png`,
  `${imageCdn}/swiper2.png`,
  `${imageCdn}/swiper1.png`,
  `${imageCdn}/swiper2.png`,
  `${imageCdn}/swiper1.png`,
];

const handleChange = (index: number, context: any) => {
  console.log('基础示例,页数变化到》》》', index, context);
};
</script>

<style>
img {
  display: block;
  width: 100%;
  height: 192px;
}
</style>
