// skills/tdesign-mobile-react/references/examples/swiper/current.tsx
/**
 * TDesign TDesign Mobile React 示例：swiper - current
 * 覆盖组件：Swiper
 * 来源：组件库源码 src/swiper/_example/current.tsx
 */

import React from 'react';
import { Button, Swiper } from 'tdesign-mobile-react';
import './style/index.less';

export default function Base() {
  const imageCdn = 'https://tdesign.gtimg.com/mobile/demos';
  const imageList = [
    `${imageCdn}/swiper1.png`,
    `${imageCdn}/swiper2.png`,
    `${imageCdn}/swiper1.png`,
    `${imageCdn}/swiper2.png`,
    `${imageCdn}/swiper1.png`,
  ];

  const [current, setCurrent] = React.useState(1);

  const swiperItems = () => (
    <>
      {imageList.map((item, index) => (
        <Swiper.SwiperItem key={index}>
          <img style={{ height: '100%' }} src={item} />
        </Swiper.SwiperItem>
      ))}
    </>
  );

  const onChange = (index: number) => {
    setCurrent(index);
  };

  const getNextIndex = (index: number) => (index + 1) % imageList.length;

  const onClickBtn = () => {
    setCurrent(getNextIndex(current));
  };

  return (
    <div className="tdesign-demo-block-wrap">
      <Swiper
        height="192px"
        interval={3000}
        duration={500}
        autoplay={false}
        current={current}
        navigation={{ type: 'dots' }}
        onChange={onChange}
      >
        {swiperItems()}
      </Swiper>
      <div className="tdesign-demo-block-row" style={{ marginTop: '10px' }}>
        <Button
          size="small"
          theme="primary"
          content={`跳转到第${getNextIndex(current) + 1}项`}
          onClick={onClickBtn}
        ></Button>
      </div>
    </div>
  );
}

// skills/tdesign-mobile-vue/references/examples/swiper/current.vue
<!--
  TDesign TDesign Mobile Vue 示例：swiper - current
  覆盖组件：Swiper
  来源：组件库源码 src/swiper/demos/current.vue
-->

<template>
  <div style="padding: 0 16px">
    <t-swiper :autoplay="true" :current="current" @click="handleClick" @change="handleChange">
      <t-swiper-item v-for="(item, index) in swiperList" :key="index" style="height: 192px">
        <img :src="item" class="img" />
      </t-swiper-item>
    </t-swiper>
    <div class="tdesign-demo-block-row">
      <t-button size="small" theme="primary" @click="changeCurrent">
        跳转到第 {{ current + 2 >= 6 ? 1 : current + 2 }} 项
      </t-button>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { ref } from 'vue';

const imageCdn = 'https://tdesign.gtimg.com/mobile/demos';
const swiperList = [
  `${imageCdn}/swiper1.png`,
  `${imageCdn}/swiper2.png`,
  `${imageCdn}/swiper1.png`,
  `${imageCdn}/swiper2.png`,
  `${imageCdn}/swiper1.png`,
];
const current = ref(0);

const handleChange = (index: number, context: any) => {
  console.log('基础示例,页数变化到》》》', index, context);
  current.value = index;
};

const handleClick = (value: number) => {
  console.log('click: ', value);
  current.value = value;
};

const changeCurrent = () => {
  current.value = current.value + 2 > 5 ? 0 : current.value + 1;
};
</script>

<style>
img {
  display: block;
  width: 100%;
  height: 192px;
}
</style>
