// skills/tdesign-react/references/examples/calendar/card.tsx
/**
 * TDesign TDesign React 示例：calendar - card
 * 覆盖组件：Calendar
 * 来源：组件库源码 packages/components/calendar/_example/card.tsx
 */

import React from 'react';
import { Button, Calendar, Select, Space, Switch } from 'tdesign-react';

type Theme = 'card' | 'full';

export default function CalendarExample() {
  const ref = React.useRef(null);
  const [theme, setTheme] = React.useState<Theme>('card');
  const [fillWithZero, setFillWithZero] = React.useState(false);
  const toCurrent = React.useCallback(() => {
    ref.current.toCurrent();
  }, [ref]);

  return (
    <Space direction="vertical" size="large">
      <Space align="center">
        <label>请选择风格：</label>
        <Select
          style={{
            width: '200px',
            display: 'inline-block',
            margin: '0 10px 0 0',
          }}
          value={theme}
          options={[
            { label: '卡片风格', value: 'card' },
            { label: '全屏风格', value: 'full' },
          ]}
          onChange={(value: Theme) => setTheme(value)}
        />
        <Button theme="primary" style={{ marginLeft: '12px' }} onClick={toCurrent}>
          回到今天
        </Button>
      </Space>
      <Space align="center">
        <label>日期补零：</label>
        <Switch size="large" value={fillWithZero} onChange={(val) => setFillWithZero(val)}></Switch>
      </Space>
      <Calendar ref={ref} theme={theme} isShowWeekendDefault={true} fillWithZero={fillWithZero} />
    </Space>
  );
}

// skills/tdesign-vue2/references/examples/calendar/card.vue
<!--
  TDesign TDesign Vue 2 示例：calendar - card
  覆盖组件：Calendar
  来源：组件库源码 src/calendar/_example/card.vue
-->

<template>
  <t-space direction="vertical" size="large">
    <t-space size="small" align="center">
      <label>请选择风格：</label>
      <t-select v-model="theme">
        <t-option v-for="item in options" :key="item.value" :value="item.value" :label="item.label" />
      </t-select>
      <t-button theme="primary" @click="toCurrent()"> 今天（当前高亮日期） </t-button>
    </t-space>
    <div>
      <label>日期补零：</label>
      <t-switch v-model="fillWithZero" size="large" />
    </div>
    <t-calendar ref="myCalendar" :theme="theme" :is-show-weekend-default="true" :fill-with-zero="fillWithZero" />
  </t-space>
</template>

<script>
export default {
  data() {
    return {
      theme: 'card',
      fillWithZero: true,
      options: [
        { value: 'full', label: '全屏风格' },
        { value: 'card', label: '卡片风格' },
      ],
    };
  },
  methods: {
    toCurrent() {
      if (this.$refs.myCalendar) {
        this.$refs.myCalendar.toCurrent();
      }
    },
  },
};
</script>

<style scoped>
.demo-select-base {
  width: 200px;
  display: inline-block;
  margin: 0 10px 0 0;
}
</style>
