// skills/tdesign-vue2/references/examples/date-picker/date-range.vue
<!--
  TDesign TDesign Vue 2 示例：date-picker - date-range
  覆盖组件：Date-picker
  来源：组件库源码 src/date-picker/_example/date-range.vue
-->

<template>
  <t-space direction="vertical">
    <t-date-range-picker allow-input clearable @pick="onPick" @change="onChange" />
    <t-date-range-picker enable-time-picker allow-input clearable @pick="onPick" @change="onChange" />
  </t-space>
</template>

<script>
export default {
  methods: {
    onPick(value, context) {
      console.log('onPick:', value, context);
    },
    onChange(value, context) {
      console.log('onChange:', value, context);
      console.log(
        'timestamp:',
        context.dayjsValue.map((d) => d.valueOf()),
      );
      console.log(
        'YYYYMMDD:',
        context.dayjsValue.map((d) => d.format('YYYYMMDD')),
      );
    },
  },
};
</script>

// skills/tdesign-react/references/examples/date-picker/date-range.tsx
/**
 * TDesign TDesign React 示例：date-picker - date-range
 * 覆盖组件：Date-picker
 * 来源：组件库源码 packages/components/date-picker/_example/date-range.tsx
 */

import React from 'react';
import { DateRangePicker, Space } from 'tdesign-react';

import type { DateRangePickerProps } from 'tdesign-react';

export default function YearDatePicker() {
  // 选中日期时的事件
  const onPick: DateRangePickerProps['onPick'] = (value, context) => {
    console.log('onPick:', value, context);
  };

  const onChange: DateRangePickerProps['onChange'] = (value, context) => {
    console.log('onChange:', value, context);
    console.log(
      'timestamp',
      context.dayjsValue.map((d) => d.valueOf()),
    );
    console.log(
      'YYYYMMDD',
      context.dayjsValue.map((d) => d.format('YYYYMMDD')),
    );
  };

  return (
    <Space direction="vertical">
      <DateRangePicker onPick={onPick} allowInput clearable onChange={onChange} />
      <DateRangePicker enableTimePicker allowInput clearable onPick={onPick} onChange={onChange} />
      {/* 可以通过 enableTimePicker 的 mode 属性控制时间选择器的显示方式 */}
      <DateRangePicker enableTimePicker={{ mode: 'switch' }} allowInput clearable onPick={onPick} onChange={onChange} />
    </Space>
  );
}
