// skills/tdesign-react/references/examples/notification/placement.tsx
/**
 * TDesign TDesign React 示例：notification - placement
 * 覆盖组件：Notification
 * 来源：组件库源码 packages/components/notification/_example/placement.tsx
 */

import React, { useState } from 'react';
import { Button, Input, NotificationPlugin, Space } from 'tdesign-react';

import type { InputValue, NotificationInfoOptions } from 'tdesign-react';

export default function NotificationExample() {
  const [offsetY, setOffsetY] = useState<InputValue>('0');
  const [offsetX, setOffsetX] = useState<InputValue>('0');

  const openNotification = (placement: NotificationInfoOptions['placement']) => {
    NotificationPlugin.info({
      title: '标题名称',
      content: '这是一条可以自动关闭的消息通知',
      placement,
      duration: 3000,
      offset: [offsetX, offsetY],
      closeBtn: true,
    });
  };

  return (
    <Space direction="vertical">
      <Space>
        <Input
          placeholder="请输入横向偏移量"
          value={offsetX}
          onChange={(v) => setOffsetX(v)}
          style={{ width: '130px', display: 'inline-block', margin: '0 20px 36px 0' }}
        />
        <Input
          placeholder="请输入纵向偏移量"
          value={offsetY}
          onChange={(v) => setOffsetY(v)}
          style={{ width: '130px', display: 'inline-block', margin: '0 20px 36px 0' }}
        />
      </Space>
      <Space>
        <Button onClick={() => openNotification('top-left')}>左上角</Button>
        <Button onClick={() => openNotification('top-right')}>右上角</Button>
      </Space>
      <Space>
        <Button onClick={() => openNotification('bottom-left')}>左下角</Button>
        <Button onClick={() => openNotification('bottom-right')}>右下角</Button>
      </Space>
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/message/placement.vue
<!--
  TDesign TDesign Vue Next 示例：message - placement
  覆盖组件：Message
  来源：组件库源码 packages/components/message/_example/placement.vue
-->

<template>
  <t-space direction="vertical" size="large">
    <t-space>
      <t-input v-model="offsetX" placeholder="请输入横向偏移量" />
      <t-input v-model="offsetY" placeholder="请输入纵向偏移量" />
    </t-space>
    <div class="tdesign-tooltip-placement">
      <t-button variant="outline" class="placement-center" @click="$message.success(msgList[0])">center</t-button>
      <t-button variant="outline" class="placement-top" @click="$message.info(msgList[1])">top</t-button>
      <t-button variant="outline" class="placement-left" @click="$message.warning(msgList[2])">left</t-button>
      <t-button variant="outline" class="placement-right" @click="$message.loading(msgList[3])">right</t-button>
      <t-button variant="outline" class="placement-bottom" @click="$message.warning(msgList[4])">bottom</t-button>
      <t-button variant="outline" class="placement-top-left" @click="$message.error(msgList[5])">top-left</t-button>
      <t-button variant="outline" class="placement-top-right" @click="$message.question(msgList[6])">
        top-right
      </t-button>
      <t-button variant="outline" class="placement-bottom-left" @click="$message.warning(msgList[7])">
        bottom-left
      </t-button>
      <t-button variant="outline" class="placement-bottom-right" @click="$message.warning(msgList[8])">
        bottom-right
      </t-button>
    </div>
  </t-space>
</template>

<script lang="ts" setup>
import { computed, ref } from 'vue';

const offsetX = ref('');
const offsetY = ref('');
const msgList = computed(() =>
  [
    {
      content: '用户表示操作顺利达成',
      placement: 'center',
    },
    {
      content: '用户表示普通操作信息提示',
      placement: 'top',
    },
    {
      content: '用户表示操作引起一定后果',
      placement: 'left',
    },
    {
      content: '用于表示操作正在生效的过程中',
      placement: 'right',
    },
    {
      content: '用于表示操作正在生效的过程中',
      placement: 'bottom',
    },
    {
      content: '用户表示操作引起严重的后果',
      placement: 'top-left',
    },
    {
      content: '用于帮助用户操作的信息提示',
      placement: 'top-right',
    },
    {
      content: '用于表示操作正在生效的过程中',
      placement: 'bottom-left',
    },
    {
      content: '用于表示操作正在生效的过程中',
      placement: 'bottom-right',
    },
  ].map((item) => ({
    ...item,
    offset: [offsetX.value, offsetY.value],
  })),
);
</script>

<style scoped>
.t-button {
  margin-right: 16px;
  margin-bottom: 16px;
}

.t-message-placement {
  margin: 0 auto;
  width: 500px;
  height: 260px;
  position: relative;
}
.placement-top {
  position: absolute;
  top: 0;
  left: 50%;
  transform: translateX(-50%);
}
.placement-top-left {
  position: absolute;
  top: 0;
  left: 0;
}
.placement-top-right {
  position: absolute;
  top: 0;
  right: 0;
}
.placement-bottom {
  position: absolute;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
}
.placement-bottom-left {
  position: absolute;
  bottom: 0;
  left: 0;
}
.placement-bottom-right {
  position: absolute;
  bottom: 0;
  right: 0;
}
.placement-left {
  position: absolute;
  left: 0;
  top: 50%;
  transform: translateY(-50%);
}
.placement-right {
  position: absolute;
  right: 0;
  top: 50%;
  transform: translateY(-50%);
}
.placement-center {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
</style>
