// skills/tdesign-vue-next/references/examples/loading/fullscreen.vue
<!--
  TDesign TDesign Vue Next 示例：loading - fullscreen
  覆盖组件：Loading
  来源：组件库源码 packages/components/loading/_example/fullscreen.vue
-->

<template>
  <t-space direction="vertical">
    <t-loading :loading="loading" text="加载中..." fullscreen />
    <!-- <t-loading :loading="loading" text="加载中..." attach="body" fullscreen /> -->

    <div>
      全局加载开关（开启加载1秒后自动归位）：
      <t-switch v-model="loading"></t-switch>
    </div>

    <!-- 绑定到任意元素 -->
    <!-- <div id="alice" class="loading-attach-demo__title">Hello, I'm Alice.</div> -->
    <!-- <t-loading :loading="loading" text="加载中..." attach="#alice" fullscreen /> -->
  </t-space>
</template>
<script lang="ts" setup>
import { ref, watch } from 'vue';

const loading = ref(false);
watch(
  () => loading.value,
  (v) => {
    if (!v) return;
    const timer = setTimeout(() => {
      loading.value = false;
      clearTimeout(timer);
    }, 1000);
  },
);
</script>

// skills/tdesign-react/references/examples/loading/fullscreen.tsx
/**
 * TDesign TDesign React 示例：loading - fullscreen
 * 覆盖组件：Loading
 * 来源：组件库源码 packages/components/loading/_example/fullscreen.tsx
 */

import React, { useState } from 'react';
import { Loading, Switch } from 'tdesign-react';

export default function LoadingFullscreen() {
  const [checked, setChecked] = useState(false);
  const [loading, setLoading] = useState(false);

  const onChange = (value) => {
    setChecked(value);
    setLoading(value);

    if (value)
      setTimeout(() => {
        setChecked(false);
        setLoading(false);
      }, 2000);
  };
  return (
    <>
      <Loading loading={loading} fullscreen preventScrollThrough={true} text="加载中"></Loading>
      Loading state:
      <Switch value={checked} onChange={onChange} />
    </>
  );
}
