// skills/tdesign-react/references/examples/timeline/loading.tsx
/**
 * TDesign TDesign React 示例：timeline - loading
 * 覆盖组件：Timeline
 * 来源：组件库源码 packages/components/timeline/_example/loading.tsx
 */

import React, { useState } from 'react';
import { Space, Switch, Timeline } from 'tdesign-react';

export default function LoadingTimeLine() {
  const [loading, setLoading] = useState(false);

  return (
    <Space direction="vertical">
      <Space>
        <h4>加载中</h4>
        <Switch value={loading} onChange={(v) => setLoading(v as boolean)}></Switch>
      </Space>
      <Timeline mode="same">
        <Timeline.Item label="2022-01-01">事件一</Timeline.Item>
        <Timeline.Item label="2022-02-01">事件二</Timeline.Item>
        <Timeline.Item label="2022-03-01">事件三</Timeline.Item>
        <Timeline.Item label="2022-04-01" loading={loading}>
          事件四
        </Timeline.Item>
      </Timeline>
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/timeline/loading.vue
<!--
  TDesign TDesign Vue Next 示例：timeline - loading
  覆盖组件：Timeline
  来源：组件库源码 packages/components/timeline/_example/loading.vue
-->

<template>
  <t-space direction="vertical">
    <t-space align="center">
      <h3>加载中</h3>
      <t-switch v-model="loading" />
    </t-space>
    <t-timeline mode="same">
      <t-timeline-item
        v-for="(item, index) in options"
        :key="index"
        :loading="loading"
        :label="item.label"
        dot-color="primary"
      >
        {{ item.content }}
      </t-timeline-item>
    </t-timeline>
  </t-space>
</template>
<script lang="ts" setup>
import { ref } from 'vue';

const loading = ref(false);
const options = [
  {
    label: '2022-01-01',
    content: '事件一',
  },
  {
    label: '2022-02-01',
    content: '事件二',
  },
  {
    label: '2022-03-01',
    content: '事件三',
  },
  {
    label: '2022-04-01',
    content: '事件四',
  },
];
</script>
