// skills/tdesign-mobile-react/references/examples/dropdown-menu/customized.tsx
/**
 * TDesign TDesign Mobile React 示例：dropdown-menu - customized
 * 覆盖组件：Dropdown-menu
 * 来源：组件库源码 src/dropdown-menu/_example/customized.tsx
 */

import { cloneDeep, noop } from 'lodash-es';
import React, { useRef, useState } from 'react';
import { Button, Checkbox, DropdownItem, DropdownMenu } from 'tdesign-mobile-react';
import CheckboxGroup from 'tdesign-mobile-react/checkbox/CheckboxGroup';
import './style/customized.less';

const chineseNumber = '一二三四五六七八九十'.split('');

const options1 = new Array(8).fill(null).map((_, i) => ({
  label: `类型${chineseNumber[i]}`,
  value: `type_${i + 1}`,
  disabled: false,
}));

const options2 = new Array(8).fill(null).map((_, i) => ({
  label: `角色${chineseNumber[i]}`,
  value: `role_${i + 1}`,
  disabled: false,
}));

const groups = [
  {
    label: '类型',
    options: [
      ...options1,
      {
        label: '禁用选项',
        value: 'disabled',
        disabled: true,
      },
    ],
  },
  {
    label: '角色',
    options: [
      ...options2,
      {
        label: '禁用选项',
        value: 'disabled',
        disabled: true,
      },
    ],
  },
];

export default function CustomizedDemo() {
  const [checkSelectGroup, setCheckSelectGroup] = useState<string[][]>([['type_1', 'type_2'], ['role_2']]);

  const ref = useRef({ collapseMenu: noop });
  return (
    <DropdownMenu ref={ref}>
      <DropdownItem
        footer={
          <div className="demo-dropdown-item_footer">
            <Button
              size="large"
              theme="light"
              onClick={() => {
                setCheckSelectGroup([[], []]);
              }}
            >
              重置
            </Button>
            <Button
              size="large"
              theme="primary"
              onClick={() => {
                ref.current.collapseMenu();
              }}
            >
              确定
            </Button>
          </div>
        }
        label="三列多选"
        multiple
        optionsColumns="1"
      >
        {groups.map((group, groupIndex) => (
          <>
            <div className="demo-dropdown-item_label" key={`dropdown-${groupIndex}`}>
              {group.label}
            </div>
            <CheckboxGroup
              className="t-dropdown-item__checkbox-group"
              style={{
                gridTemplateColumns: 'repeat(3, 1fr)',
              }}
              value={checkSelectGroup[groupIndex] || []}
              onChange={(value: string[]) => {
                const newValue = cloneDeep(checkSelectGroup);
                newValue[groupIndex] = value;
                setCheckSelectGroup(newValue);
              }}
            >
              {group.options.map((item, index) => (
                <Checkbox
                  className="t-dropdown-item__checkbox-item t-checkbox--tag"
                  key={`${item.value}-${index}`}
                  icon={false}
                  borderless
                  label={item.label}
                  value={item.value}
                  disabled={item.disabled}
                />
              ))}
            </CheckboxGroup>
          </>
        ))}
      </DropdownItem>
    </DropdownMenu>
  );
}

// skills/tdesign-mobile-vue/references/examples/dropdown-menu/customized.vue
<!--
  TDesign TDesign Mobile Vue 示例：dropdown-menu - customized
  覆盖组件：Dropdown-menu
  来源：组件库源码 src/dropdown-menu/demos/customized.vue
-->

<template>
  <t-dropdown-menu ref="parentRef">
    <t-dropdown-item v-model="val" label="三列多选" multiple options-columns="1">
      <div v-for="(group, i) in groups" :key="i">
        <div class="demo-dropdown-item_label">
          {{ group.label }}
        </div>
        <!-- 多选列表 -->
        <t-checkbox-group
          v-model="checkSelectGroup[i]"
          class="t-dropdown-item__checkbox-group"
          :style="`grid-template-columns: repeat(3, 1fr)`"
          @change="handleMultipleSelect($event, i)"
        >
          <template v-for="option in group.options" :key="option.value">
            <t-checkbox
              class="t-dropdown-item__checkbox-item t-checkbox--tag"
              :icon="false"
              borderless
              :value="option.value"
              :label="option.label"
              :disabled="option.disabled"
            />
          </template>
        </t-checkbox-group>
      </div>
      <template #footer>
        <div class="demo-dropdown-item_footer">
          <t-button size="large" theme="light" @click="resetSelect">重置</t-button>
          <t-button size="large" theme="primary" @click="confirmSelect">确定</t-button>
        </div>
      </template>
    </t-dropdown-item>
  </t-dropdown-menu>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

// 获取组件
const parentRef = ref<HTMLElement | null>(null);

let val = ref(['type_1', 'type_2', 'role_2']);

const chineseNumber = '一二三四五六七八九十'.split('');

const options1 = new Array(8).fill(null).map((_, i) => ({
  label: `类型${chineseNumber[i]}`,
  value: `type_${i + 1}`,
  disabled: false,
}));

const options2 = new Array(8).fill(null).map((_, i) => ({
  label: `角色${chineseNumber[i]}`,
  value: `role_${i + 1}`,
  disabled: false,
}));

const groups = [
  {
    label: '类型',
    options: [
      ...options1,
      {
        label: '禁用选项',
        value: 'disabled',
        disabled: true,
      },
    ],
  },
  {
    label: '角色',
    options: [
      ...options2,
      {
        label: '禁用选项',
        value: 'disabled',
        disabled: true,
      },
    ],
  },
];
const checkSelectGroup = ref([]);

let checkSelect: any = [];

function initCheckValue() {
  for (let i = 0; i < groups.length; i++) {
    checkSelect.push([]);
  }

  groups.forEach((item, index) => {
    val.value.forEach((e: any) => {
      item.options.forEach((opt) => {
        if (e === opt.value) {
          checkSelect[index].push(e);
        }
      });
    });
  });
  checkSelectGroup.value = checkSelect;
}

initCheckValue();

function handleMultipleSelect(e: any, i: number) {
  console.log(e);
  checkSelect[i] = e;
  let res: any = [];
  checkSelect.forEach((item: any) => {
    res = res.concat(item);
  });
  val.value = res;
}

// 重置
function resetSelect() {
  val = ref([]);
  checkSelect = [];
  initCheckValue();
}

// 确认
function confirmSelect() {
  // @ts-ignore
  parentRef.value.collapseMenu();
}
</script>
<style lang="less" scoped>
.demo-dropdown-item {
  &_label {
    padding: 16px 0 0 16px;
    font-size: 14px;
    color: var(--td-text-color-primary, rgba(0, 0, 0, 0.9));
  }
  &_footer {
    display: flex;
    width: 100%;

    .t-button {
      flex: 1;
    }
  }
}

.demo-dropdown-item_footer {
  --td-button-border-radius: 0;
}
</style>
