// skills/tdesign-vue2/references/examples/link/hover.vue
<!--
  TDesign TDesign Vue 2 示例：link - hover
  覆盖组件：Link
  来源：组件库源码 src/link/_example/hover.vue
-->

<template>
  <t-space direction="vertical">
    <t-space>
      <t-link theme="default" hover="underline"> 跳转链接 </t-link>
      <t-link theme="primary" hover="underline"> 跳转链接 </t-link>
      <t-link theme="danger" hover="underline"> 跳转链接 </t-link>
      <t-link theme="warning" hover="underline"> 跳转链接 </t-link>
      <t-link theme="success" hover="underline"> 跳转链接 </t-link>
    </t-space>
    <t-space>
      <t-link theme="default" hover="color"> 跳转链接 </t-link>
      <t-link theme="primary" hover="color"> 跳转链接 </t-link>
      <t-link theme="danger" hover="color"> 跳转链接 </t-link>
      <t-link theme="warning" hover="color"> 跳转链接 </t-link>
      <t-link theme="success" hover="color"> 跳转链接 </t-link>
    </t-space>
    <t-space>
      <t-link theme="default" hover="color" underline> 跳转链接 </t-link>
      <t-link theme="primary" hover="color" underline> 跳转链接 </t-link>
      <t-link theme="danger" hover="color" underline> 跳转链接 </t-link>
      <t-link theme="warning" hover="color" underline> 跳转链接 </t-link>
      <t-link theme="success" hover="color" underline> 跳转链接 </t-link>
    </t-space>
  </t-space>
</template>

// skills/tdesign-react/references/examples/link/hover.tsx
/**
 * TDesign TDesign React 示例：link - hover
 * 覆盖组件：Link
 * 来源：组件库源码 packages/components/link/_example/hover.tsx
 */

import React from 'react';
import { Link, Space } from 'tdesign-react';

export default function LinkExample() {
  return (
    <Space direction="vertical">
      <Space>
        <Link theme="default" hover="underline">
          跳转链接
        </Link>
        <Link theme="primary" hover="underline">
          跳转链接
        </Link>
        <Link theme="danger" hover="underline">
          跳转链接
        </Link>
        <Link theme="warning" hover="underline">
          跳转链接
        </Link>
        <Link theme="success" hover="underline">
          跳转链接
        </Link>
      </Space>
      <Space>
        <Link theme="default" hover="color">
          跳转链接
        </Link>
        <Link theme="primary" hover="color">
          跳转链接
        </Link>
        <Link theme="danger" hover="color">
          跳转链接
        </Link>
        <Link theme="warning" hover="color">
          跳转链接
        </Link>
        <Link theme="success" hover="color">
          跳转链接
        </Link>
      </Space>
      <Space>
        <Link theme="default" hover="color" underline>
          跳转链接
        </Link>
        <Link theme="primary" hover="color" underline>
          跳转链接
        </Link>
        <Link theme="danger" hover="color" underline>
          跳转链接
        </Link>
        <Link theme="warning" hover="color" underline>
          跳转链接
        </Link>
        <Link theme="success" hover="color" underline>
          跳转链接
        </Link>
      </Space>
    </Space>
  );
}
