// skills/tdesign-vue-next/references/examples/form/align.vue
<!--
  TDesign TDesign Vue Next 示例：form - align
  覆盖组件：Form
  来源：组件库源码 packages/components/form/_example/align.vue
-->

<template>
  <t-space direction="vertical" size="large">
    <t-radio-group v-model="formData.labelAlign" variant="default-filled">
      <t-radio-button value="left">左对齐</t-radio-button>
      <t-radio-button value="right">右对齐</t-radio-button>
      <t-radio-button value="top">顶部对齐</t-radio-button>
    </t-radio-group>

    <t-form :data="formData" :label-align="formData.labelAlign" :label-width="60">
      <t-form-item label="姓名" name="name">
        <t-input v-model="formData.name"></t-input>
      </t-form-item>
      <t-form-item label="密码" name="password">
        <t-input v-model="formData.password" type="password"></t-input>
      </t-form-item>
      <t-form-item>
        <t-button theme="primary" type="submit">登录</t-button>
      </t-form-item>
    </t-form>
  </t-space>
</template>
<script lang="ts" setup>
import { reactive } from 'vue';
import type { FormProps } from 'tdesign-vue-next';

const formData: FormProps['data'] = reactive({
  labelAlign: 'right',
  name: '',
  password: '',
});
</script>

// skills/tdesign-react/references/examples/form/align.tsx
/**
 * TDesign TDesign React 示例：form - align
 * 覆盖组件：Form
 * 来源：组件库源码 packages/components/form/_example/align.tsx
 */

import React, { useState } from 'react';
import { Form, Input, Radio, Space } from 'tdesign-react';

const { FormItem } = Form;

type LabelAlign = 'left' | 'right' | 'top';

export default function AlignForm() {
  const [labelAlign, setLabelAlign] = useState<LabelAlign>('right');
  return (
    <Space direction="vertical">
      <Radio.Group value={labelAlign} onChange={(value: LabelAlign) => setLabelAlign(value)} variant="default-filled">
        <Radio.Button value="left">左对齐</Radio.Button>
        <Radio.Button value="right">右对齐</Radio.Button>
        <Radio.Button value="top">顶部对齐</Radio.Button>
      </Radio.Group>
      <Form labelAlign={labelAlign} labelWidth={80}>
        <FormItem label="名字" name="name">
          <Input />
        </FormItem>
        <FormItem label="密码" name="password">
          <Input />
        </FormItem>
      </Form>
    </Space>
  );
}
