// skills/tdesign-vue-next/references/examples/calendar/slot-props-api.vue
<!--
  TDesign TDesign Vue Next 示例：calendar - slot-props-api
  覆盖组件：Calendar
  来源：组件库源码 packages/components/calendar/_example/slot-props-api.vue
-->

<template>
  <t-calendar :head="renderHead" :cell="renderCell" />
</template>

<script lang="tsx" setup>
import dayjs from 'dayjs';
import type { CalendarProps } from 'tdesign-vue-next';

const renderHead: CalendarProps['head'] = (h, params) => {
  let title = String(params.filterDate.getFullYear());
  if (params.mode === 'month') {
    title += `-${params.filterDate.getMonth() + 1}`;
  }
  title += ' 工作安排';
  return <div>{title}</div>;
};
const renderCell: CalendarProps['cell'] = (h, params) => {
  const dataList = [
    {
      value: 'error',
      label: '错误事件',
    },
    {
      value: 'warning',
      label: '警告事件',
    },
    {
      value: 'success',
      label: '正常事件',
    },
  ];
  return (
    <div class="calendar-slot-props-api-demo">
      {(params.mode === 'month'
        ? dayjs(params.formattedDate).date() === 15
        : dayjs(params.formattedDate).month() === 7) && (
        <span>
          <div class="calendar-slot-props-api-demo-slot-warrper">
            {dataList.map((item) => (
              <div class="item">
                <span class={item.value}></span>
                {item.label}
              </div>
            ))}
          </div>
          <div class="shadow" />
        </span>
      )}
      <div class="number">
        {params.mode === 'year' ? dayjs(params.formattedDate).month() : dayjs(params.formattedDate).date()}
      </div>
    </div>
  );
};
</script>
<style lang="less">
.calendar-slot-props-api-demo {
  width: 100%;
  height: 100%;
  position: relative;

  .shadow {
    position: absolute;
    width: 100%;
    height: 12px;
    bottom: 0;
    background: linear-gradient(180deg, rgba(255, 255, 255, 0) 0%, #ffffff 100%);
  }
  .number {
    font-weight: bold;
    position: absolute;
    top: 3px;
    right: 5px;
    font-size: 14px;
  }
  .item {
    position: relative;
    display: flex;
    align-items: center;
    color: var(--td-text-color-secondary);
    span {
      display: block;
      left: 1px;
      width: 5px;
      height: 5px;
      border-radius: 10px;
      margin-right: 4px;
    }
  }
  .error {
    background: var(--td-error-color);
  }
  .warning {
    background: var(--td-warning-color);
  }
  .success {
    background: var(--td-success-color);
  }
}
.calendar-slot-props-api-demo-slot-warrper {
  position: absolute;
  bottom: 2px;
  left: 5px;
}
</style>

// skills/tdesign-react/references/examples/calendar/slot-props-api.tsx
/**
 * TDesign TDesign React 示例：calendar - slot-props-api
 * 覆盖组件：Calendar
 * 来源：组件库源码 packages/components/calendar/_example/slot-props-api.tsx
 */

import React from 'react';
import dayjs from 'dayjs';
import { Calendar, Space, Tag } from 'tdesign-react';

import type { CalendarCell, ControllerOptions } from 'tdesign-react';

type TagTheme = 'default' | 'danger' | 'warning' | 'success' | 'primary';

interface DataList {
  label: string;
  value: TagTheme;
}

export default function CalendarExample() {
  const displayNum = React.useCallback((date: CalendarCell) => {
    if (date.mode === 'month') {
      return date.date.getDate();
    }
    return date.date.getMonth() + 1;
  }, []);

  const isShow = (data: CalendarCell) =>
    data.mode === 'month' ? dayjs(data.formattedDate).date() === 15 : dayjs(data.formattedDate).month() === 7;

  const dataList: DataList[] = [
    {
      value: 'danger',
      label: '错误事件',
    },
    {
      value: 'warning',
      label: '警告事件',
    },
    {
      value: 'success',
      label: '正常事件',
    },
  ];

  const renderHead = (params: ControllerOptions) => {
    let title = `${params.filterDate.getFullYear()}`;
    if (params.mode === 'month') {
      title += `-${params.filterDate.getMonth() + 1}`;
    }
    title += ' 工作安排';
    return <div>{title}</div>;
  };

  return (
    <Calendar
      head={renderHead}
      cell={(cellData) => (
        <>
          <div style={{ width: '100%' }}>
            <div>{displayNum(cellData)}</div>
            {isShow(cellData) && (
              <Space direction="vertical" size={2}>
                {dataList.map((item, index) => (
                  <Tag key={index} theme={item.value}>
                    {item.label}
                  </Tag>
                ))}
              </Space>
            )}
          </div>
        </>
      )}
    />
  );
}
