// skills/tdesign-react/references/examples/input/borderless.tsx
/**
 * TDesign TDesign React 示例：input - borderless
 * 覆盖组件：Input
 * 来源：组件库源码 packages/components/input/_example/borderless.tsx
 */

import React from 'react';
import { Input, Space } from 'tdesign-react';

export default function BorderlessInputExample() {
  return (
    <Space direction="vertical" style={{ width: 500 }}>
      <Input placeholder="please input" clearable />
      <Input placeholder="borderless input" borderless={true} clearable />
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/input/borderless.vue
<!--
  TDesign TDesign Vue Next 示例：input - borderless
  覆盖组件：Input
  来源：组件库源码 packages/components/input/_example/borderless.vue
-->

<template>
  <t-space direction="vertical" style="max-width: 500px">
    <t-input placeholder="please input" clearable> </t-input>

    <t-input placeholder="borderless Input" borderless clearable> </t-input>
  </t-space>
</template>
<script setup></script>
