// skills/tdesign-react/references/examples/input/format.tsx
/**
 * TDesign TDesign React 示例：input - format
 * 覆盖组件：Input
 * 来源：组件库源码 packages/components/input/_example/format.tsx
 */

import React, { useState } from 'react';
import { Input } from 'tdesign-react';

import type { InputProps } from 'tdesign-react';

export default function InputExample() {
  const [value, setValue] = useState('');
  function format(val: string) {
    const reg = /(\d)(?=(?:\d{3})+$)/g;
    const str = val.replace(reg, '$1,');
    return str;
  }

  const inputStatus: InputProps['status'] = isNaN(+value) ? 'error' : 'default';
  const tips = inputStatus ? '请输入数字' : '';

  return (
    <Input
      value={value}
      onChange={setValue}
      status={inputStatus}
      format={format}
      tips={tips}
      placeholder="请输入数字"
    />
  );
}

// skills/tdesign-vue-next/references/examples/input/format.vue
<!--
  TDesign TDesign Vue Next 示例：input - format
  覆盖组件：Input
  来源：组件库源码 packages/components/input/_example/format.vue
-->

<template>
  <t-input v-model="input" :status="inputStatus" :format="format" placeholder="请输入数字" :tips="tips" />
</template>
<script lang="ts" setup>
import { ref, computed } from 'vue';
import type { InputProps } from 'tdesign-vue-next';

const input = ref('');
const inputStatus = computed<InputProps['status']>(() => {
  if (isNaN(+input.value)) {
    return 'error';
  }
  return 'default';
});
const tips = computed<InputProps['tips']>(() => {
  if (inputStatus.value !== 'error') {
    return '';
  }
  return '请输入数字';
});
const format: InputProps['format'] = (val) => {
  const reg = /(\d)(?=(?:\d{3})+$)/g;
  const str = val.replace(reg, '$1,');
  return str;
};
</script>
