// skills/tdesign-mobile-react/references/examples/stepper/theme.tsx
/**
 * TDesign TDesign Mobile React 示例：stepper - theme
 * 覆盖组件：Stepper
 * 来源：组件库源码 src/stepper/_example/theme.tsx
 */

import React from 'react';
import { Stepper } from 'tdesign-mobile-react';

export default function theme() {
  return (
    <div className="stepper-example">
      <Stepper defaultValue={3} theme={'filled'}></Stepper>
      <Stepper defaultValue={3} theme={'outline'}></Stepper>
      <Stepper defaultValue={3}></Stepper>
    </div>
  );
}

// skills/tdesign-vue2/references/examples/button/theme.vue
<!--
  TDesign TDesign Vue 2 示例：button - theme
  覆盖组件：Button
  来源：组件库源码 src/button/_example/theme.vue
-->

<template>
  <t-space direction="vertical">
    <t-space>
      <t-button theme="default">填充按钮</t-button>
      <t-button variant="outline" theme="default">描边按钮</t-button>
      <t-button variant="dashed" theme="default">虚框按钮</t-button>
      <t-button variant="text" theme="default">文字按钮</t-button>
    </t-space>
    <t-space>
      <t-button theme="primary">填充按钮</t-button>
      <t-button variant="outline" theme="primary">描边按钮</t-button>
      <t-button variant="dashed" theme="primary">虚框按钮</t-button>
      <t-button variant="text" theme="primary">文字按钮</t-button>
    </t-space>
    <t-space>
      <t-button theme="danger">填充按钮</t-button>
      <t-button variant="outline" theme="danger">描边按钮</t-button>
      <t-button variant="dashed" theme="danger">虚框按钮</t-button>
      <t-button variant="text" theme="danger">文字按钮</t-button>
    </t-space>
    <t-space>
      <t-button theme="warning">填充按钮</t-button>
      <t-button variant="outline" theme="warning">描边按钮</t-button>
      <t-button variant="dashed" theme="warning">虚框按钮</t-button>
      <t-button variant="text" theme="warning">文字按钮</t-button>
    </t-space>
    <t-space>
      <t-button theme="success">填充按钮</t-button>
      <t-button variant="outline" theme="success">描边按钮</t-button>
      <t-button variant="dashed" theme="success">虚框按钮</t-button>
      <t-button variant="text" theme="success">文字按钮</t-button>
    </t-space>
  </t-space>
</template>
