// skills/tdesign-vue2/references/examples/slider/step.vue
<!--
  TDesign TDesign Vue 2 示例：slider - step
  覆盖组件：Slider
  来源：组件库源码 src/slider/_example/step.vue
-->

<template>
  <t-space direction="vertical" size="60px">
    <t-slider v-model="value1" :show-tooltip="true" :step="step" />
    <t-slider v-model="value2" range :show-tooltip="true" :step="step" />
  </t-space>
</template>
<script>
export default {
  data() {
    return {
      value1: 12,
      value2: [28, 80],
      step: 4,
    };
  },
};
</script>
<style>
.block {
  padding: 30px 24px;
}
</style>

// skills/tdesign-react/references/examples/slider/step.tsx
/**
 * TDesign TDesign React 示例：slider - step
 * 覆盖组件：Slider
 * 来源：组件库源码 packages/components/slider/_example/step.tsx
 */

import React, { useState } from 'react';
import { Slider, Space, Switch } from 'tdesign-react';

import type { SliderValue } from 'tdesign-react';

const StepSlider = () => {
  const [showStep, setShowStep] = useState<boolean>(false);
  const [value, setValue] = useState<SliderValue>(10);
  const [rangeValue, setRangeValue] = useState<SliderValue>([10, 80]);

  return (
    <>
      <Space style={{ marginBottom: 60 }}>
        <Switch value={showStep} onChange={(v) => setShowStep(v)} />
        显示步长刻度
      </Space>

      <Space direction="vertical" size={50} style={{ width: '100%' }}>
        <Slider value={value} step={4} showStep={showStep} onChange={setValue}></Slider>
        <Slider value={rangeValue} step={4} showStep={showStep} onChange={setRangeValue} range></Slider>
      </Space>
    </>
  );
};

export default StepSlider;
