// skills/tdesign-mobile-react/references/examples/rate/color.tsx
/**
 * TDesign TDesign Mobile React 示例：rate - color
 * 覆盖组件：Rate
 * 来源：组件库源码 src/rate/_example/color.tsx
 */

import React from 'react';
import { Cell, CellGroup, Rate } from 'tdesign-mobile-react';

export default function Color() {
  return (
    <CellGroup className="rate-demo__color">
      <Cell title="选中及未选中颜色" style={{ overflow: 'initial' }}>
        <Rate defaultValue={3} color={['#FFC51C', '#E8E8E8']} allowHalf={true} />
      </Cell>
      <Cell title="仅选中颜色" style={{ overflow: 'initial' }}>
        <Rate defaultValue={3} color="#00A870" allowHalf={true} />
      </Cell>
    </CellGroup>
  );
}

// skills/tdesign-mobile-vue/references/examples/switch/color.vue
<!--
  TDesign TDesign Mobile Vue 示例：switch - color
  覆盖组件：Switch
  来源：组件库源码 src/switch/demos/color.vue
-->

<template>
  <t-cell title="自定义颜色开关">
    <template #rightIcon>
      <t-switch :default-value="true" class="custom-color" />
    </template>
  </t-cell>
</template>

<style>
.custom-color {
  --td-switch-checked-color: #00a870;
}
</style>
