// skills/tdesign-mobile-vue/references/examples/drawer/footer.vue
<!--
  TDesign TDesign Mobile Vue 示例：drawer - footer
  覆盖组件：Drawer
  来源：组件库源码 src/drawer/demos/footer.vue
-->

<template>
  <t-drawer v-model:visible="visible" placement="left" :items="baseSidebar" @item-click="itemClick">
    <template #footer>
      <div class="button-host">
        <t-button variant="outline" size="large" block>操作</t-button>
      </div>
    </template>
  </t-drawer>
  <t-button block variant="outline" size="large" theme="primary" @click="visible = true">带底部插槽抽屉</t-button>
</template>
<script lang="ts" setup>
import { ref } from 'vue';
import { DrawerItem } from 'tdesign-mobile-vue';

const baseSidebar = ref([
  {
    title: '菜单一',
  },
  {
    title: '菜单二',
  },
  {
    title: '菜单三',
  },
  {
    title: '菜单四',
  },
  {
    title: '菜单五',
  },
  {
    title: '菜单六',
  },
]);
const visible = ref(false);
const itemClick = (index: number, item: DrawerItem, context: { e: MouseEvent }) => {
  console.log('itemclick: ', index, item, context);
};
</script>

<style scopde>
.button-host {
  margin: 0 16px;
  margin-top: auto;
}
</style>

// skills/tdesign-mobile-react/references/examples/drawer/footer.tsx
/**
 * TDesign TDesign Mobile React 示例：drawer - footer
 * 覆盖组件：Drawer
 * 来源：组件库源码 src/drawer/_example/footer.tsx
 */

import React, { useState } from 'react';
import { Drawer, Button } from 'tdesign-mobile-react';
import './style/index.less';

export default function Base() {
  const [openBase, setOpenBase] = useState(false);

  const onClose = (e) => {
    console.log(e, 'e');
    setOpenBase(false);
  };

  const baseSidebar = [
    {
      title: '菜单一',
    },
    {
      title: '菜单二',
    },
    {
      title: '菜单三',
    },
    {
      title: '菜单四',
    },
    {
      title: '菜单五',
    },
    {
      title: '菜单六',
    },
  ];

  const footer = (
    <div className="button-host">
      <Button variant="outline" size="large" block>
        操作
      </Button>
    </div>
  );

  return (
    <>
      <Button
        theme="primary"
        size="large"
        variant="outline"
        block
        onClick={() => {
          setOpenBase(!openBase);
        }}
      >
        带底部插槽
      </Button>
      <Drawer
        footer={footer}
        visible={openBase}
        items={baseSidebar}
        placement="left"
        closeOnOverlayClick
        onClose={onClose}
      />
    </>
  );
}
