// skills/tdesign-mobile-vue/references/examples/drawer/plugin.vue
<!--
  TDesign TDesign Mobile Vue 示例：drawer - plugin
  覆盖组件：Drawer
  来源：组件库源码 src/drawer/demos/plugin.vue
-->

<template>
  <t-button block variant="outline" size="large" theme="primary" @click="showDrawer">命令行调用</t-button>
</template>

<script lang="ts" setup>
import { DrawerPlugin } from 'tdesign-mobile-vue';

const showDrawer = () => {
  const instance = DrawerPlugin({
    items: new Array(20).fill({ title: '菜单' }).map((item, index: number) => ({ title: `标题 ${index + 1}` })),
    onItemClick(index: number) {
      console.log(index);
      instance.destroy();
    },
  });
  instance.show();
};
</script>

// skills/tdesign-mobile-react/references/examples/drawer/plugin.tsx
/**
 * TDesign TDesign Mobile React 示例：drawer - plugin
 * 覆盖组件：Drawer
 * 来源：组件库源码 src/drawer/_example/plugin.tsx
 */

import React from 'react';
import { Button, DrawerPlugin } from 'tdesign-mobile-react';
import './style/index.less';

export default function Base() {
  const baseSidebar = [
    {
      title: '菜单一',
    },
    {
      title: '菜单二',
    },
    {
      title: '菜单三',
    },
    {
      title: '菜单四',
    },
    {
      title: '菜单五',
    },
    {
      title: '菜单六',
    },
  ];

  const showDrawer = () => {
    const instance = DrawerPlugin({
      items: baseSidebar,
      onItemClick(index: number) {
        console.log(index);
        instance.destroy();
      },
    });
    instance.show();
  };

  return (
    <Button theme="primary" size="large" variant="outline" block onClick={showDrawer}>
      命令行调用
    </Button>
  );
}
