// skills/tdesign-react/references/examples/menu/single-side.tsx
/**
 * TDesign TDesign React 示例：menu - single-side
 * 覆盖组件：Menu
 * 来源：组件库源码 packages/components/menu/_example/single-side.tsx
 */

import React, { Fragment, useState } from 'react';
import { Menu } from 'tdesign-react';

import type { MenuValue } from 'tdesign-react';

const { MenuItem } = Menu;

function SingleSide() {
  const [active, setActive] = useState<MenuValue>('0');
  const [darkActive, setDarkActive] = useState<MenuValue>('1');

  return (
    <Fragment>
      <Menu
        value={active}
        onChange={(v) => setActive(v)}
        logo={<img src="https://tdesign.gtimg.com/site/baseLogo-light.png" height="28" alt="logo" />}
        style={{ marginRight: 20 }}
      >
        <MenuItem value={'0'}>
          <span>仪表盘</span>
        </MenuItem>
        <MenuItem value={'1'}>
          <span>资源列表</span>
        </MenuItem>
        <MenuItem value={'2'}>
          <span>视频区</span>
        </MenuItem>
        <MenuItem value={'3'} disabled>
          <span>根目录</span>
        </MenuItem>
        <MenuItem value={'4'}>
          <span>调度平台</span>
        </MenuItem>
        <MenuItem value={'5'}>
          <span>精准监控</span>
        </MenuItem>
        <MenuItem value={'6'}>
          <span>个人中心</span>
        </MenuItem>
      </Menu>
      {/* 暗黑模式 */}
      <Menu
        value={darkActive}
        theme="dark"
        onChange={(v) => setDarkActive(v)}
        logo={<img src="https://tdesign.gtimg.com/site/baseLogo-dark.png" height="28" alt="logo" />}
      >
        <MenuItem value={'0'}>
          <span>仪表盘</span>
        </MenuItem>
        <MenuItem value={'1'}>
          <span>资源列表</span>
        </MenuItem>
        <MenuItem value={'2'}>
          <span>视频区</span>
        </MenuItem>
        <MenuItem value={'3'} disabled>
          <span>根目录</span>
        </MenuItem>
        <MenuItem value={'4'}>
          <span>调度平台</span>
        </MenuItem>
        <MenuItem value={'5'}>
          <span>精准监控</span>
        </MenuItem>
        <MenuItem value={'6'}>
          <span>个人中心</span>
        </MenuItem>
      </Menu>
    </Fragment>
  );
}

export default SingleSide;

// skills/tdesign-vue2/references/examples/menu/single-side.vue
<!--
  TDesign TDesign Vue 2 示例：menu - single-side
  覆盖组件：Menu
  来源：组件库源码 src/menu/_example/single-side.vue
-->

<template>
  <div class="box">
    <t-menu theme="light" defaultValue="item1" @change="changeHandler" style="margin-right: 40px">
      <template #logo>
        <img height="28" src="https://tdesign.gtimg.com/site/baseLogo-light.png" alt="logo" />
      </template>
      <t-menu-item value="item1" href="/vue" target="_blank">仪表盘</t-menu-item>
      <t-menu-item value="item2">资源列表</t-menu-item>
      <t-menu-item value="item3">根目录</t-menu-item>
      <t-menu-item value="item4" :disabled="true">调度平台</t-menu-item>
      <t-menu-item value="item5">精准监控</t-menu-item>
      <t-menu-item value="item6">消息区</t-menu-item>
      <t-menu-item value="item7">个人中心</t-menu-item>
      <t-menu-item value="item8">视频区</t-menu-item>
      <t-menu-item value="item9">资源编辑</t-menu-item>
    </t-menu>

    <t-menu theme="light" defaultValue="dashboard" style="margin-right: 40px">
      <template #logo>
        <img height="28" src="https://tdesign.gtimg.com/site/baseLogo-light.png" alt="logo" />
      </template>
      <t-menu-item value="dashboard">
        <template #icon>
          <icon name="dashboard" />
        </template>
        仪表盘
      </t-menu-item>
      <t-menu-item value="resource">
        <template #icon>
          <icon name="server" />
        </template>
        资源列表
      </t-menu-item>
      <t-menu-item value="root">
        <template #icon>
          <icon name="root-list" />
        </template>
        根目录
      </t-menu-item>
      <t-menu-item value="control-platform">
        <template #icon>
          <icon name="control-platform" />
        </template>
        调度平台
      </t-menu-item>
      <t-menu-item value="precise-monitor">
        <template #icon>
          <icon name="precise-monitor" />
        </template>
        精准监控
      </t-menu-item>
      <t-menu-item value="mail">
        <template #icon>
          <icon name="mail" />
        </template>
        消息区
      </t-menu-item>
      <t-menu-item value="user-circle">
        <template #icon>
          <icon name="user-circle" />
        </template>
        个人中心
      </t-menu-item>
      <t-menu-item value="play-circle">
        <template #icon>
          <icon name="play-circle" />
        </template>
        视频区
      </t-menu-item>
      <t-menu-item value="edit1">
        <template #icon>
          <icon name="edit-1" />
        </template>
        资源编辑
      </t-menu-item>
    </t-menu>

    <t-menu theme="dark" defaultValue="dashboard">
      <img slot="logo" height="28" src="https://tdesign.gtimg.com/site/baseLogo-dark.png" alt="logo" />
      <t-menu-item value="dashboard">
        <template #icon>
          <icon name="dashboard" />
        </template>
        仪表盘
      </t-menu-item>
      <t-menu-item value="resource">
        <template #icon>
          <icon name="server" />
        </template>
        资源列表
      </t-menu-item>
      <t-menu-item value="root">
        <template #icon>
          <icon name="root-list" />
        </template>
        根目录
      </t-menu-item>
      <t-menu-item value="control-platform">
        <template #icon>
          <icon name="control-platform" />
        </template>
        调度平台
      </t-menu-item>
      <t-menu-item value="precise-monitor">
        <template #icon>
          <icon name="precise-monitor" />
        </template>
        精准监控
      </t-menu-item>
      <t-menu-item value="mail">
        <template #icon>
          <icon name="mail" />
        </template>
        消息区
      </t-menu-item>
      <t-menu-item value="user-circle">
        <template #icon>
          <icon name="user-circle" />
        </template>
        个人中心
      </t-menu-item>
      <t-menu-item value="play-circle">
        <template #icon>
          <icon name="play-circle" />
        </template>
        视频区
      </t-menu-item>
      <t-menu-item value="edit1">
        <template #icon>
          <icon name="edit-1" />
        </template>
        资源编辑
      </t-menu-item>
    </t-menu>
  </div>
</template>

<script>
import { Icon } from 'tdesign-icons-vue';

export default {
  components: {
    Icon,
  },
  methods: {
    changeHandler(active) {
      console.log('change', active);
    },
  },
};
</script>
