// skills/tdesign-react/references/examples/descriptions/column.tsx
/**
 * TDesign TDesign React 示例：descriptions - column
 * 覆盖组件：Descriptions
 * 来源：组件库源码 packages/components/descriptions/_example/column.tsx
 */

import React from 'react';
import { Descriptions, Radio, Space } from 'tdesign-react';

export default function Column() {
  const [column, setColumn] = React.useState(2);

  const columnOptions = [2, 3, 4];

  const items = [
    {
      label: 'Name',
      content: 'TDesign',
    },
    {
      label: 'Telephone Number',
      content: '139****0609',
    },
    {
      label: 'Area',
      content: 'China Tencent Headquarters',
    },
    {
      label: 'Address',
      content: 'Shenzhen Penguin Island D1 4A Mail Center',
    },
  ];
  return (
    <Space direction="vertical">
      <Radio.Group
        options={columnOptions}
        value={column}
        onChange={(val: number) => setColumn(val)}
        variant="default-filled"
      />
      <Descriptions items={items} title="Shipping address" bordered column={column} />
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/descriptions/column.vue
<!--
  TDesign TDesign Vue Next 示例：descriptions - column
  覆盖组件：Descriptions
  来源：组件库源码 packages/components/descriptions/_example/column.vue
-->

<template>
  <t-space direction="vertical">
    <t-radio-group v-model="column" :options="columnOptions"></t-radio-group>
    <t-descriptions bordered :column="column">
      <t-descriptions-item label="Name">TDesign</t-descriptions-item>
      <t-descriptions-item label="Telephone Number">139****0609</t-descriptions-item>
      <t-descriptions-item label="Area">China Tencent Headquarters</t-descriptions-item>
      <t-descriptions-item label="Address">Shenzhen Penguin Island D1 4A Mail Center</t-descriptions-item>
    </t-descriptions>
  </t-space>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import type { RadioGroupProps } from 'tdesign-vue-next';

const columnOptions: RadioGroupProps['options'] = [2, 3, 4];
const column = ref(2);
</script>
