// skills/tdesign-react/references/examples/config-provider/global.tsx
/**
 * TDesign TDesign React 示例：config-provider - global
 * 覆盖组件：Config-provider
 * 来源：组件库源码 packages/components/config-provider/_example/global.tsx
 */

/* eslint-disable react/no-unescaped-entities */
import React from 'react';
import { ConfigProvider, Space } from 'tdesign-react';
import enConfig from 'tdesign-react/es/locale/en_US';

import type { GlobalConfigProvider } from 'tdesign-react';

export default function GlobalDemo() {
  // 全局特性配置，引入英文语言配置包 enConfig
  const globalConfig: GlobalConfigProvider = {
    ...enConfig,
    // 可以在此处定义更多自定义配置，具体可配置内容参看 API 文档
    calendar: {},
    table: {},
    pagination: {},
    // 全局动画设置
    animation: { exclude: [] },
  };

  return (
    <ConfigProvider globalConfig={globalConfig}>
      <Space direction="vertical">
        <p>
          使用<code>ConfigProvider</code>包裹业务功能的最外层组件，点击下方图标查看示例代码
        </p>

        <p>
          英文语言包引入路径：<code>import enConfig from 'tdesign-react/es/locale/en_US';</code>
        </p>

        <p>
          中文语言包引入路径：<code>import zhConfig from 'tdesign-react/es/locale/zh_CN';</code>
        </p>

        <p>
          日文语言包引入路径：<code>import jpConfig from 'tdesign-react/es/locale/ja_JP';</code>
        </p>

        <p>
          韩文语言包引入路径：<code>import koConfig from 'tdesign-react/es/locale/ko_KR';</code>
        </p>
      </Space>
    </ConfigProvider>
  );
}

// skills/tdesign-vue2/references/examples/config-provider/global.vue
<!--
  TDesign TDesign Vue 2 示例：config-provider - global
  覆盖组件：Config-provider
  来源：组件库源码 src/config-provider/_example/global.vue
-->

<template>
  <t-config-provider :global-config="globalConfig">
    <t-space direction="vertical">
      <p>使用<code>t-config-provider</code>包裹业务功能的最外层组件，点击下方图标查看示例代码</p>
      <p>英文语言包引入路径：<code>import enConfig from 'tdesign-vue/es/locale/en_US';</code></p>
      <p>中文语言包引入路径：<code>import zhConfig from 'tdesign-vue/es/locale/zh_CN';</code></p>
      <p>日文语言包引入路径：<code>import jpConfig from 'tdesign-vue/es/locale/ja_JP';</code></p>
      <p>韩文语言包引入路径：<code>import koConfig from 'tdesign-vue/es/locale/ko_KR';</code></p>
    </t-space>
  </t-config-provider>
</template>

<script>
import { merge } from 'lodash-es';
import enConfig from 'tdesign-vue/es/locale/en_US';

export default {
  data() {
    return {
      // 全局特性配置，引入英文语言配置包 enConfig
      globalConfig: merge(enConfig, {
        // 可以在此处定义更多自定义配置，具体可配置内容参看 API 文档
        calendar: {},
        table: {},
        pagination: {},
      }),
    };
  },
};
</script>
