// skills/tdesign-mobile-vue/references/examples/toast/theme.vue
<!--
  TDesign TDesign Mobile Vue 示例：toast - theme
  覆盖组件：Toast
  来源：组件库源码 src/toast/demos/theme.vue
-->

<template>
  <div class="toast-demo">
    <t-button block size="large" theme="primary" variant="outline" @click="showSuccessToast()">成功提示</t-button>
    <t-button block size="large" theme="primary" variant="outline" @click="showWarningToast()">警告提示</t-button>
    <t-button block size="large" theme="primary" variant="outline" @click="showErrorToast()">错误提示</t-button>
  </div>
</template>

<script setup lang="ts">
import { Toast } from 'tdesign-mobile-vue';

const showSuccessToast = () => {
  Toast({
    className: 'toast-root--success',
    duration: 50000,
    theme: 'success',
    direction: 'column',
    message: '轻提示文字内容',
  });
};
const showWarningToast = () => {
  Toast({
    theme: 'warning',
    direction: 'column',
    message: '轻提示文字内容',
  });
};
const showErrorToast = () => {
  Toast({
    theme: 'error',
    direction: 'column',
    message: '轻提示文字内容',
  });
};
</script>

// skills/tdesign-mobile-react/references/examples/toast/theme.tsx
/**
 * TDesign TDesign Mobile React 示例：toast - theme
 * 覆盖组件：Toast
 * 来源：组件库源码 src/toast/_example/theme.tsx
 */

import React from 'react';
import { Toast, Button } from 'tdesign-mobile-react';
import TDemoBlock from '../../../site/mobile/components/DemoBlock';

export default function () {
  const successColumn = () => {
    Toast({ message: '轻提示文字内容', theme: 'success', direction: 'column' });
  };

  const warningColumn = () => {
    Toast({ message: '轻提示文字内容', theme: 'warning', direction: 'column' });
  };

  const errorColumn = () => {
    Toast({ message: '轻提示文字内容', theme: 'error', direction: 'column' });
  };

  return (
    <div className="toast-demo">
      <TDemoBlock summary="成功提示" padding>
        <Button block theme="primary" variant="outline" size="large" onClick={successColumn}>
          成功提示
        </Button>
      </TDemoBlock>

      <TDemoBlock summary="警告提示" padding>
        <Button block theme="primary" variant="outline" size="large" onClick={warningColumn}>
          警告提示
        </Button>
      </TDemoBlock>

      <TDemoBlock summary="失败提示" padding>
        <Button block theme="primary" variant="outline" size="large" onClick={errorColumn}>
          失败提示
        </Button>
      </TDemoBlock>
    </div>
  );
}
