// skills/tdesign-react/references/examples/tag/check-tag-group.tsx
/**
 * TDesign TDesign React 示例：tag - check-tag-group
 * 覆盖组件：Tag
 * 来源：组件库源码 packages/components/tag/_example/check-tag-group.tsx
 */

import React, { useState } from 'react';
import { Space, Tag } from 'tdesign-react';

import type { CheckTagGroupValue } from 'tdesign-react';

const { CheckTagGroup } = Tag;

const options = [
  { label: '标签1', value: 1 },
  { label: '标签2', value: 2 },
  { label: <span>标签3</span>, value: 3 },
  { label: '标签4', value: 4 },
  { label: '标签5', value: '5' },
  { label: '标签6', value: 6 },
];

const avatarStyle = {
  width: '16px',
  height: '16px',
  borderRadius: '2px',
  verticalAlign: '-4px',
  marginRight: '4px',
};

function CustomTag(option: { avatar: string; label: React.ReactNode; value: number | string }) {
  return (
    <div>
      <img src={option.avatar} style={avatarStyle} />
      <span>
        {option.label}({option.value})
      </span>
    </div>
  );
}

const AVATAR = 'https://tdesign.gtimg.com/site/avatar.jpg';
const options2 = [
  { label: 'TAG_A', value: 1, avatar: AVATAR },
  { label: 'TAG_B', value: 2, avatar: AVATAR },
  { label: 'TAG_C', value: 3, avatar: AVATAR },
  { label: 'TAG_D', value: 4, avatar: AVATAR },
  { label: 'TAG_E', value: '5', avatar: AVATAR },
  { label: 'TAG_F', value: 6, avatar: AVATAR },
].map((option) => ({ ...option, label: <CustomTag {...option} /> }));

const STYLE_B_UNCHECKED_PROPS = {
  theme: 'default',
  variant: 'outline',
} as const;

const STYLE_C_CHECKED_PROPS = {
  theme: 'primary',
  variant: 'outline',
} as const;

const CheckTagGroupDemo = () => {
  const [checkTagValue1, setCheckTagValue1] = useState<CheckTagGroupValue>([1]);
  const [checkTagValue2, setCheckTagValue2] = useState<CheckTagGroupValue>([2]);
  const [checkTagValue3, setCheckTagValue3] = useState<CheckTagGroupValue>([3]);
  const [checkTagValue4, setCheckTagValue4] = useState<CheckTagGroupValue>([4, 6]);

  return (
    <Space direction="vertical">
      <Space>
        <label>StyleA</label>
        <CheckTagGroup value={checkTagValue1} onChange={setCheckTagValue1} options={options} />
      </Space>

      <Space>
        <label>StyleB</label>
        <CheckTagGroup
          value={checkTagValue2}
          onChange={setCheckTagValue2}
          options={options}
          uncheckedProps={STYLE_B_UNCHECKED_PROPS}
        />
      </Space>

      <Space>
        <label>StyleC</label>
        <CheckTagGroup
          value={checkTagValue3}
          onChange={setCheckTagValue3}
          options={options}
          checkedProps={STYLE_C_CHECKED_PROPS}
          uncheckedProps={STYLE_B_UNCHECKED_PROPS}
        />
      </Space>

      <Space>
        <label>CustomContent</label>
        <CheckTagGroup
          value={checkTagValue4}
          onChange={setCheckTagValue4}
          options={options2}
          checkedProps={STYLE_C_CHECKED_PROPS}
          uncheckedProps={STYLE_B_UNCHECKED_PROPS}
        />
      </Space>
    </Space>
  );
};

export default CheckTagGroupDemo;

// skills/tdesign-vue-next/references/examples/tag/check-tag-group.vue
<!--
  TDesign TDesign Vue Next 示例：tag - check-tag-group
  覆盖组件：Tag
  来源：组件库源码 packages/components/tag/_example/check-tag-group.vue
-->

<template>
  <t-space direction="vertical">
    <t-space align="center">
      <label>StyleA</label>
      <t-check-tag-group v-model="checkTagValue1" :options="options" />
    </t-space>

    <t-space align="center">
      <label>StyleB</label>
      <t-check-tag-group
        v-model="checkTagValue2"
        :options="options"
        :unchecked-props="STYLE_B_UNCHECKED_PROPS"
        multiple
      />
    </t-space>

    <t-space align="center">
      <label>StyleC</label>
      <t-check-tag-group
        v-model="checkTagValue3"
        :options="options"
        :checked-props="STYLE_C_CHECKED_PROPS"
        :unchecked-props="STYLE_B_UNCHECKED_PROPS"
        multiple
      />
    </t-space>

    <t-space align="center">
      <label>CustomContent</label>
      <t-check-tag-group
        v-model="checkTagValue4"
        :options="options2"
        :checked-props="STYLE_C_CHECKED_PROPS"
        :unchecked-props="STYLE_B_UNCHECKED_PROPS"
        multiple
      >
        <template #option="{ label, value, avatar }">
          <div>
            <img :src="avatar" class="avatar" />
            <span>{{ label }}({{ value }})</span>
          </div>
        </template>
      </t-check-tag-group>
    </t-space>
  </t-space>
</template>

<script lang="tsx" setup>
import { ref } from 'vue';
import type { CheckTagGroupOption, CheckTagGroupProps } from 'tdesign-vue-next';

const STYLE_B_UNCHECKED_PROPS: CheckTagGroupProps['uncheckedProps'] = {
  theme: 'default',
  variant: 'outline',
};
const STYLE_C_CHECKED_PROPS: CheckTagGroupProps['checkedProps'] = {
  theme: 'primary',
  variant: 'outline',
};
const checkTagValue1 = ref([1]);
const checkTagValue2 = ref([2]);
const checkTagValue3 = ref([3]);
const checkTagValue4 = ref([4, 6]);
const options: CheckTagGroupProps['options'] = [
  {
    label: '标签1',
    value: 1,
  },
  {
    label: '标签2',
    value: 2,
  },
  {
    label: () => <span>标签3</span>,
    value: 3,
  },
  {
    label: '标签4',
    value: 4,
  },
  {
    label: '标签5',
    value: '5',
  },
  {
    label: '标签6',
    value: 6,
  },
];
const AVATAR = 'https://tdesign.gtimg.com/site/avatar.jpg';
const options2: (CheckTagGroupOption & {
  avatar: string;
})[] = [
  {
    label: 'TAG_A',
    value: 1,
    avatar: AVATAR,
  },
  {
    label: 'TAG_B',
    value: 2,
    avatar: AVATAR,
  },
  {
    label: 'TAG_C',
    value: 3,
    avatar: AVATAR,
  },
  {
    label: 'TAG_D',
    value: 4,
    avatar: AVATAR,
  },
  {
    label: 'TAG_E',
    value: '5',
    avatar: AVATAR,
  },
  {
    label: 'TAG_F',
    value: 6,
    avatar: AVATAR,
  },
];
</script>

<style lang="less" scoped>
.avatar {
  width: 16px;
  height: 16px;
  border-radius: 2px;
  vertical-align: -4px;
  margin-right: 4px;
}
</style>
