// skills/tdesign-react/references/examples/tag/delete.tsx
/**
 * TDesign TDesign React 示例：tag - delete
 * 覆盖组件：Tag
 * 来源：组件库源码 packages/components/tag/_example/delete.tsx
 */

import React, { useEffect, useRef, useState } from 'react';
import { AddIcon, DiscountIcon } from 'tdesign-icons-react';
import { Input, Space, Tag } from 'tdesign-react';

import type { InputRef } from 'tdesign-react';

export default function ClosableTagExample() {
  const [inputVisible, toggleInputVisible] = useState(false);
  const inputRef = useRef<InputRef>(null);
  const [tagList, setTagList] = useState([
    {
      name: '可删除标签',
      showClose: true,
    },
    {
      name: '可删除标签',
      icon: <DiscountIcon />,
      showClose: true,
    },
    {
      name: '可删除标签',
      showClose: true,
      disabled: true,
    },
  ]);

  useEffect(() => {
    if (inputVisible) {
      inputRef.current?.focus();
    }
  }, [inputVisible]);

  /**
   * @param {number} i
   */
  const deleteTag = (i: number) => {
    const newtagList = [...tagList];
    newtagList.splice(i, 1);
    setTagList(newtagList);
  };

  const handleClickAdd = () => {
    toggleInputVisible(true);
  };

  const handleInputEnter = (value: string) => {
    toggleInputVisible(false);
    if (value) setTagList((currentList) => currentList.concat([{ name: value, showClose: true }]));
  };

  return (
    <Space direction="vertical">
      <Space>
        {tagList.map((tag, i) => (
          <Tag
            key={i}
            closable
            onClose={() => {
              deleteTag(i);
            }}
            icon={tag.icon}
            disabled={tag.disabled}
            style={{ marginRight: 30 }}
          >
            {tag.name}
            {i}
          </Tag>
        ))}
      </Space>
      <div style={{ display: 'flex', cursor: 'pointer' }}>
        {inputVisible ? (
          <Input
            ref={inputRef}
            size="small"
            onBlur={handleInputEnter}
            onEnter={handleInputEnter}
            style={{ width: '94px' }}
          />
        ) : (
          <Tag onClick={handleClickAdd} icon={<AddIcon />}>
            可添加标签
          </Tag>
        )}
      </div>
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/tag/delete.vue
<!--
  TDesign TDesign Vue Next 示例：tag - delete
  覆盖组件：Tag
  来源：组件库源码 packages/components/tag/_example/delete.vue
-->

<template>
  <t-space direction="vertical">
    <t-space class="tag-block">
      <t-tag theme="primary" closable>标签一</t-tag>
      <t-tag theme="success" closable>标签二</t-tag>
      <t-tag theme="warning" closable>标签三</t-tag>
      <t-tag theme="danger" closable>标签四</t-tag>
    </t-space>
    <t-space class="tag-block light">
      <t-tag theme="primary" variant="light" closable>标签一</t-tag>
      <t-tag theme="success" variant="light" closable>标签二</t-tag>
      <t-tag theme="warning" variant="light" closable>标签三</t-tag>
      <t-tag theme="danger" variant="light" closable>标签四</t-tag>
    </t-space>
    <t-space class="tag-block">
      <t-tag variant="outline" theme="primary" closable>标签一</t-tag>
      <t-tag variant="outline" theme="success" closable>标签二</t-tag>
      <t-tag variant="outline" theme="warning" closable>标签三</t-tag>
      <t-tag variant="outline" theme="danger" closable>标签四</t-tag>
    </t-space>
    <t-space class="tag-block">
      <t-tag
        v-for="(tag, index) in tags"
        :key="index"
        :theme="tag.type"
        :closable="tag.showClose"
        :icon="tag.icon"
        :disabled="!!tag.disabled"
        :max-width="tag.maxWidth"
        @click="handleClick"
        @close="handleClose(index)"
      >
        {{ tag.name }}
      </t-tag>
    </t-space>
    <t-space class="tag-block editable">
      <t-tag v-if="!inputVisible" @click="handleClickAdd">
        <template #icon>
          <add-icon />
        </template>
        添加标签
      </t-tag>
      <t-input v-else ref="input" size="small" style="width: 94px" @blur="handleInputEnter" @enter="handleInputEnter" />
    </t-space>
  </t-space>
</template>
<script lang="tsx" setup>
import { nextTick, ref } from 'vue';
import { AddIcon } from 'tdesign-icons-vue-next';
import type { TagProps, InputProps } from 'tdesign-vue-next';

const inputVisible = ref(false);
const tags = ref([
  {
    name: '可删除标签可删除标签',
    type: 'default',
    showClose: true,
    maxWidth: 100,
  },
  {
    name: '可删除标签可删除标签',
    type: 'default',
    icon: () => <t-icon name="discount" />,
    showClose: true,
    maxWidth: 100,
  },
  {
    name: '可删除标签',
    type: 'default',
    showClose: true,
    disabled: true,
  },
]);
const input = ref('');
const handleClose = (index: number) => {
  console.log(index);
  tags.value.splice(index, 1);
};
const handleClick: TagProps['onClick'] = (event) => {
  console.log(event);
};
const handleInputEnter: InputProps['onEnter'] = (val) => {
  if (val && !tags.value.some((item) => item.name === val)) {
    tags.value.push({
      name: val,
      type: 'default',
      showClose: true,
    });
  }
  inputVisible.value = false;
};
const handleClickAdd: TagProps['onClick'] = () => {
  inputVisible.value = true;
  nextTick(() => {
    input.value.focus();
  });
};
</script>
