// skills/tdesign-vue2/references/examples/tag-input/auto-width.vue
<!--
  TDesign TDesign Vue 2 示例：tag-input - auto-width
  覆盖组件：Tag-input
  来源：组件库源码 src/tag-input/_example/auto-width.vue
-->

<template>
  <t-tag-input v-model="tags" auto-width clearable />
</template>
<script>
export default {
  data() {
    return {
      tags: ['Vue', 'React'],
    };
  },
};
</script>

// skills/tdesign-react/references/examples/tag-input/auto-width.tsx
/**
 * TDesign TDesign React 示例：tag-input - auto-width
 * 覆盖组件：Tag-input
 * 来源：组件库源码 packages/components/tag-input/_example/auto-width.tsx
 */

import React, { useState } from 'react';
import { TagInput } from 'tdesign-react';

const TagInputAutoWidth = () => {
  const [tags, setTags] = useState(['Vue', 'React']);

  const onChange = (val: string[]) => {
    setTags(val);
  };
  return <TagInput value={tags} onChange={onChange} autoWidth clearable />;
};

TagInputAutoWidth.displayName = 'TagInputAutoWidth';

export default TagInputAutoWidth;
