// skills/tdesign-react/references/examples/select/custom-options.tsx
/**
 * TDesign TDesign React 示例：select - custom-options
 * 覆盖组件：Select
 * 来源：组件库源码 packages/components/select/_example/custom-options.tsx
 */

import React, { useState } from 'react';
import { Select } from 'tdesign-react';

const { Option } = Select;

const options = [
  { label: '用户一', value: '1', description: '这是一段用户描述信息，可自定义内容' },
  { label: '用户二', value: '2', description: '这是一段用户描述信息，可自定义内容' },
  { label: '用户三', value: '3', description: '这是一段用户描述信息，可自定义内容' },
  { label: '用户四', value: '4', description: '这是一段用户描述信息，可自定义内容' },
  { label: '用户五', value: '5', description: '这是一段用户描述信息，可自定义内容' },
  { label: '用户六', value: '6', description: '这是一段用户描述信息，可自定义内容' },
  { label: '用户七', value: '7', description: '这是一段用户描述信息，可自定义内容' },
  { label: '用户八', value: '8', description: '这是一段用户描述信息，可自定义内容' },
  { label: '用户九', value: '9', description: '这是一段用户描述信息，可自定义内容' },
];

const avatarUrl = 'https://tdesign.gtimg.com/site/avatar.jpg';

export default function CustomOptions() {
  const [value, setValue] = useState('1');
  const onChange = (value: string) => {
    setValue(value);
  };

  return (
    <Select value={value} onChange={onChange} style={{ width: '300px' }} clearable>
      {options.map((option, idx) => (
        <Option style={{ height: '60px' }} key={idx} value={option.value} label={option.label}>
          <div style={{ display: 'flex' }}>
            <img
              src={avatarUrl}
              style={{
                maxWidth: '40px',
                borderRadius: '50%',
              }}
            />
            <div style={{ marginLeft: '16px' }}>
              <div>{option.label}</div>
              <div
                style={{
                  fontSize: '13px',
                  color: 'var(--td-gray-color-9)',
                }}
              >
                {option.description}
              </div>
            </div>
          </div>
        </Option>
      ))}
    </Select>
  );
}

// skills/tdesign-vue-next/references/examples/select/custom-options.vue
<!--
  TDesign TDesign Vue Next 示例：select - custom-options
  覆盖组件：Select
  来源：组件库源码 packages/components/select/_example/custom-options.vue
-->

<template>
  <t-space direction="vertical">
    <!-- 方式一：使用 options 自定义下拉选项内容 -->
    <t-select
      v-model="value1"
      :options="optionsData"
      :popup-props="{ overlayClassName: 'tdesign-demo-select__overlay-option' }"
      placeholder="请选择"
    />

    <!-- 方式二：使用插槽自定义下拉选项内容 -->
    <t-select
      v-model="value2"
      placeholder="请选择"
      :popup-props="{ overlayClassName: 'tdesign-demo-select__overlay-option' }"
    >
      <t-option v-for="item in options" :key="item.value" :value="item.value" :label="item.label">
        <div class="tdesign-demo__user-option">
          <img src="https://tdesign.gtimg.com/site/avatar.jpg" />
          <div class="tdesign-demo__user-option-info">
            <div>{{ item.label }}</div>
            <div class="tdesign-demo__user-option-desc">{{ item.description }}</div>
          </div>
        </div>
      </t-option>
    </t-select>
  </t-space>
</template>
<script lang="tsx" setup>
import { ref, computed } from 'vue';
import type { SelectProps } from 'tdesign-vue-next';

const options = [
  {
    label: '用户一',
    value: '1',
    description: '这是一段用户描述信息，可自定义内容',
  },
  {
    label: '用户二',
    value: '2',
    description: '这是一段用户描述信息，可自定义内容',
  },
  {
    label: '用户三',
    value: '3',
    description: '这是一段用户描述信息，可自定义内容',
  },
  {
    label: '用户四',
    value: '4',
    description: '这是一段用户描述信息，可自定义内容',
  },
  {
    label: '用户五',
    value: '5',
    description: '这是一段用户描述信息，可自定义内容',
  },
  {
    label: '用户六',
    value: '6',
    description: '这是一段用户描述信息，可自定义内容',
  },
  {
    label: '用户七',
    value: '7',
    description: '这是一段用户描述信息，可自定义内容',
  },
  {
    label: '用户八',
    value: '8',
    description: '这是一段用户描述信息，可自定义内容',
  },
  {
    label: '用户九',
    value: '9',
    description: '这是一段用户描述信息，可自定义内容',
  },
];
const value1 = ref('');
const value2 = ref('');
const optionRender = (option: { label: string; value: string; description: string }) => (
  <div class="tdesign-demo__user-option">
    <img src="https://tdesign.gtimg.com/site/avatar.jpg" />
    <div class="tdesign-demo__user-option-info">
      <div>{option.label}</div>
      <div class="tdesign-demo__user-option-desc">{option.description}</div>
    </div>
  </div>
);
const optionsData = computed<SelectProps['options']>(() =>
  options.map((item) => ({
    ...item,
    // options 自定义下拉选项关键代码
    content: () => optionRender(item),
  })),
);
</script>
<style>
.tdesign-demo__user-option {
  display: flex;
}

.tdesign-demo__user-option > img {
  max-width: 40px;
  max-height: 40px;
  border-radius: 50%;
}

.tdesign-demo__user-option-desc {
  font-size: 14px;
  color: var(--td-text-color-secondary);
}

.tdesign-demo__user-option-info {
  margin-left: 16px;
}

.tdesign-demo-select__overlay-option .t-select-option {
  height: 100%;
  padding: 8px;
}
</style>
