// skills/tdesign-react/references/examples/select/popup-props.tsx
/**
 * TDesign TDesign React 示例：select - popup-props
 * 覆盖组件：Select
 * 来源：组件库源码 packages/components/select/_example/popup-props.tsx
 */

import React, { useState } from 'react';
import { Select, Space } from 'tdesign-react';

const SelectPopupProps = () => {
  const [value, setValue] = useState('1');
  const onChange = (value: string) => {
    setValue(value);
  };
  return (
    <Space>
      <Select
        value={value}
        onChange={onChange}
        style={{ width: '300px', display: 'inline-block' }}
        options={[
          {
            label: '固定300px宽度',
            value: '1',
          },
          {
            label: '选项内容超长超长超长超长超长超长超长超长超长超长超长的选项',
            value: '2',
          },
        ]}
      ></Select>
      <Select
        value={value}
        onChange={onChange}
        style={{ width: '300px' }}
        popupProps={{
          overlayInnerStyle: { width: '300px' },
          overlayStyle: { fontWeight: 'normal' },
          overlayClassName: 'select-custom-overlay-class',
          overlayInnerClassName: 'select-custom-overlay-inner-class',
        }}
        options={[
          {
            label: '下拉框强制和输入框同宽',
            value: '1',
          },
          {
            label: '选项内容超长超长超长超长超长超长超长超长超长超长超长的选项',
            value: '2',
          },
        ]}
      ></Select>
    </Space>
  );
};

export default SelectPopupProps;

// skills/tdesign-vue-next/references/examples/select/popup-props.vue
<!--
  TDesign TDesign Vue Next 示例：select - popup-props
  覆盖组件：Select
  来源：组件库源码 packages/components/select/_example/popup-props.vue
-->

<template>
  <t-space>
    <t-select
      v-model="value"
      placeholder="-请选择-"
      :options="options"
      :popup-props="popupProps"
      style="width: 200px; display: inline-block"
    />
    <t-select
      v-model="value"
      placeholder="-请选择-"
      :options="options"
      :popup-props="popupProps2"
      style="width: 200px; display: inline-block; margin-left: 20px"
    />
  </t-space>
</template>
<script lang="ts" setup>
import { ref } from 'vue';
import type { SelectProps } from 'tdesign-vue-next';

const options: SelectProps['options'] = [
  {
    label: '已选择的选项',
    value: '1',
  },
  {
    label: '短的选项二',
    value: '2',
  },
  {
    label: '很长很长很很长很长很长的选项三',
    value: '3',
  },
];
const value = ref('1');
const popupProps: SelectProps['popupProps'] = {
  overlayInnerStyle: {
    width: '200px',
  },
};
const popupProps2: SelectProps['popupProps'] = {
  overlayInnerStyle: (trigger) => ({
    width: `${trigger.offsetWidth}px`,
  }),
};
</script>
