// skills/tdesign-react/references/examples/select/remote-search.tsx
/**
 * TDesign TDesign React 示例：select - remote-search
 * 覆盖组件：Select
 * 来源：组件库源码 packages/components/select/_example/remote-search.tsx
 */

import React, { useEffect, useState } from 'react';
import { Select, Space } from 'tdesign-react';

const OPTIONS = Array.from({ length: 20 }).map((_, i) => ({
  value: `t${i + 1}`,
  label: `Tencent_${i + 1}`,
}));

const RemoteSearchSelect = () => {
  const [singleLoading, setSingleLoading] = useState(false);
  const [singleOptions, setSingleOptions] = useState([]);
  const [singleValue, setSingleValue] = useState('');

  const [multipleLoading, setMultipleLoading] = useState(false);
  const [multipleOptions, setMultipleOptions] = useState([]);
  const [multipleValue, setMultipleValue] = useState([]);

  useEffect(() => {
    setSingleLoading(true);
    setMultipleLoading(true);

    setTimeout(() => {
      setSingleOptions(OPTIONS);
      setSingleLoading(false);
      setSingleValue(OPTIONS[0].value);
      setMultipleOptions(OPTIONS);
      setMultipleLoading(false);
      setMultipleValue([OPTIONS[0].value, OPTIONS[1].value]);
    }, 500);
  }, []);

  const handleSingle = (search: string) => {
    setSingleLoading(true);
    setTimeout(() => {
      const filtered = OPTIONS.filter((item) => item.label.includes(search));
      setSingleOptions(filtered);
      setSingleLoading(false);
    }, 500);
  };

  const handleMultiple = (search: string) => {
    setMultipleLoading(true);
    setTimeout(() => {
      const filtered = OPTIONS.filter((item) => item.label.includes(search));
      setMultipleOptions(filtered);
      setMultipleLoading(false);
    }, 500);
  };

  return (
    <Space direction="vertical">
      <Select
        filterable
        options={singleOptions}
        value={singleValue}
        loading={singleLoading}
        onChange={setSingleValue}
        onSearch={handleSingle}
      />
      <Select
        multiple
        filterable
        options={multipleOptions}
        value={multipleValue}
        loading={multipleLoading}
        onChange={setMultipleValue}
        onSearch={handleMultiple}
        style={{ width: '400px' }}
      />
    </Space>
  );
};

export default RemoteSearchSelect;

// skills/tdesign-vue-next/references/examples/select/remote-search.vue
<!--
  TDesign TDesign Vue Next 示例：select - remote-search
  覆盖组件：Select
  来源：组件库源码 packages/components/select/_example/remote-search.vue
-->

<template>
  <t-space direction="vertical" :style="{ width: '350px' }">
    <t-select
      v-model="singleValue"
      filterable
      placeholder="请选择"
      :loading="singleLoading"
      :options="singleOptions"
      @search="remoteMethodSingle"
    />

    <t-select
      v-model="multipleValue"
      multiple
      remote
      filterable
      :loading="multipleLoading"
      @search="remoteMethodMultiple"
    >
      <t-option v-for="{ label, value } in multipleOptions" :key="value" :value="value" :label="label"> </t-option>
    </t-select>
  </t-space>
</template>
<script lang="ts" setup>
import { ref, onMounted } from 'vue';

interface Option {
  value: string;
  label: string;
}

// 模拟远程全部数据
const wholeOptions: Option[] = Array.from({ length: 20 }).map((_, i) => ({
  value: `test${i + 1}`,
  label: `腾讯_test${i + 1}`,
}));

// --- 单选选择器的状态 ---
const singleLoading = ref(false);
const singleOptions = ref<Option[]>([]);
const singleValue = ref('test1');

// --- 多选选择器的状态 ---
const multipleLoading = ref(false);
const multipleOptions = ref<Option[]>([]);
const multipleValue = ref(['test1', 'test8']);

// 初始值
const initMultipleValue = () => {
  singleLoading.value = true;
  multipleLoading.value = true;

  setTimeout(() => {
    singleOptions.value = wholeOptions;
    singleLoading.value = false;

    multipleOptions.value = wholeOptions;
    multipleLoading.value = false;
  }, 500);
};

// 单选选择器的远程搜索方法
const remoteMethodSingle = (search: string) => {
  singleLoading.value = true;
  setTimeout(() => {
    singleOptions.value = wholeOptions.slice(5, 15).filter((item) => item.label.includes(search));
    singleLoading.value = false;
  }, 500);
};

// 多选选择器的远程搜索方法
const remoteMethodMultiple = (search: string) => {
  multipleLoading.value = true;
  setTimeout(() => {
    multipleOptions.value = wholeOptions.slice(5, 15).filter((item) => item.label.includes(search));
    multipleLoading.value = false;
  }, 500);
};

onMounted(() => {
  initMultipleValue();
});
</script>
