// skills/tdesign-vue-next/references/examples/cascader/check-strictly.vue
<!--
  TDesign TDesign Vue Next 示例：cascader - check-strictly
  覆盖组件：Cascader
  来源：组件库源码 packages/components/cascader/_example/check-strictly.vue
-->

<template>
  <t-space direction="vertical">
    <t-cascader v-model="value1" :options="options" check-strictly />
    <t-cascader v-model="value2" :options="options" check-strictly multiple />
  </t-space>
</template>

<script lang="tsx" setup>
import { ref } from 'vue';
import type { CascaderProps } from 'tdesign-vue-next';

const options: CascaderProps['options'] = [
  {
    value: '1',
    label: '1',
    children: [
      {
        value: '1.1',
        label: '1.1',
        children: [
          {
            value: '1.1.1',
            label: '1.1.1',
            children: [
              {
                value: '1.1.1.1',
                label: '1.1.1.1',
              },
              {
                value: '1.1.1.2',
                label: '1.1.1.2',
              },
            ],
          },
          {
            value: '1.1.2',
            label: '1.1.2',
            children: [
              {
                value: '1.1.2.1',
                label: '1.1.2.1',
              },
              {
                value: '1.1.2.2',
                label: '1.1.2.2',
              },
            ],
          },
        ],
      },
      {
        value: '1.2',
        label: '1.2',
        children: [
          {
            value: '1.2.1',
            label: '1.2.1',
            children: [
              {
                value: '1.2.1.1',
                label: '1.2.1.1',
              },
              {
                value: '1.2.1.2',
                label: '1.2.1.2',
              },
            ],
          },
          {
            value: '1.2.2',
            label: '1.2.2',
            children: [
              {
                value: '1.2.2.1',
                label: '1.2.2.1',
              },
              {
                value: '1.2.2.2',
                label: '1.2.2.2',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    value: '2',
    label: '2',
    children: [
      {
        value: '2.1',
        label: '2.1',
      },
      {
        value: '2.2',
        label: '2.2',
      },
    ],
  },
];
const value1 = ref('1.2.2');
const value2 = ref(['1.1.2.1', '2']);
</script>

// skills/tdesign-react/references/examples/cascader/check-strictly.tsx
/**
 * TDesign TDesign React 示例：cascader - check-strictly
 * 覆盖组件：Cascader
 * 来源：组件库源码 packages/components/cascader/_example/check-strictly.tsx
 */

import React, { useState } from 'react';
import { Cascader, Space } from 'tdesign-react';

import type { CascaderProps, CascaderValue } from 'tdesign-react';

export default function Example() {
  const [value1, setValue1] = useState<CascaderValue>('1.2.2');
  const [value2, setValue2] = useState<CascaderValue>(['1.1.2.1', '2']);
  const options = [
    {
      value: '1',
      label: '1',
      children: [
        {
          value: '1.1',
          label: '1.1',
          children: [
            {
              value: '1.1.1',
              label: '1.1.1',
              children: [
                {
                  value: '1.1.1.1',
                  label: '1.1.1.1',
                },
                {
                  value: '1.1.1.2',
                  label: '1.1.1.2',
                },
              ],
            },
            {
              value: '1.1.2',
              label: '1.1.2',
              children: [
                {
                  value: '1.1.2.1',
                  label: '1.1.2.1',
                },
                {
                  value: '1.1.2.2',
                  label: '1.1.2.2',
                },
              ],
            },
          ],
        },
        {
          value: '1.2',
          label: '1.2',
          children: [
            {
              value: '1.2.1',
              label: '1.2.1',
              children: [
                {
                  value: '1.2.1.1',
                  label: '1.2.1.1',
                },
                {
                  value: '1.2.1.2',
                  label: '1.2.1.2',
                },
              ],
            },
            {
              value: '1.2.2',
              label: '1.2.2',
              children: [
                {
                  value: '1.2.2.1',
                  label: '1.2.2.1',
                },
                {
                  value: '1.2.2.2',
                  label: '1.2.2.2',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      value: '2',
      label: '2',
      children: [
        {
          value: '2.1',
          label: '2.1',
        },
        {
          value: '2.2',
          label: '2.2',
        },
      ],
    },
  ];

  const onChange1: CascaderProps['onChange'] = (value) => {
    setValue1(value);
  };
  const onChange2: CascaderProps['onChange'] = (value) => {
    setValue2(value);
  };

  return (
    <Space direction="vertical">
      <Cascader options={options} value={value1} onChange={onChange1} checkStrictly />
      <Cascader options={options} value={value2} onChange={onChange2} checkStrictly multiple />
    </Space>
  );
}
