// skills/tdesign-vue-next/references/examples/input-number/disabled.vue
<!--
  TDesign TDesign Vue Next 示例：input-number - disabled
  覆盖组件：Input-number
  来源：组件库源码 packages/components/input-number/_example/disabled.vue
-->

<template>
  <t-input-number v-model="value" :max="15" :min="-2" :disabled="true" />
</template>

<script lang="ts" setup>
import { ref } from 'vue';

const value = ref(3);
</script>

// skills/tdesign-react/references/examples/cascader/disabled.tsx
/**
 * TDesign TDesign React 示例：cascader - disabled
 * 覆盖组件：Cascader
 * 来源：组件库源码 packages/components/cascader/_example/disabled.tsx
 */

import React, { useState } from 'react';
import { Cascader, Space } from 'tdesign-react';

export default function Example() {
  const value1 = '1.1';
  const value2 = ['1.1'];
  const [options] = useState([
    {
      label: '选项一',
      value: '1',
      children: [
        {
          label: '子选项一',
          value: '1.1',
        },
        {
          label: '子选项二',
          value: '1.2',
        },
        {
          label: '子选项三',
          value: '1.3',
        },
      ],
    },
    {
      label: '选项二',
      value: '2',
      children: [
        {
          label: '子选项一',
          value: '2.1',
        },
        {
          label: '子选项二',
          value: '2.2',
        },
      ],
    },
  ]);

  return (
    <Space direction="vertical">
      <Cascader options={options} value={value1} disabled />
      <Cascader options={options} value={value2} disabled multiple />
    </Space>
  );
}
