// skills/tdesign-mobile-vue/references/examples/button/group.vue
<!--
  TDesign TDesign Mobile Vue 示例：button - group
  覆盖组件：Button
  来源：组件库源码 src/button/demos/group.vue
-->

<template>
  <div class="row">
    <t-button size="large" theme="light">填充按钮</t-button>
    <t-button size="large" theme="primary">填充按钮</t-button>
  </div>
</template>

<style scoped>
.row {
  margin: 0 16px;
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16px;
}
</style>

// skills/tdesign-mobile-react/references/examples/button/group.tsx
/**
 * TDesign TDesign Mobile React 示例：button - group
 * 覆盖组件：Button
 * 来源：组件库源码 src/button/_example/group.tsx
 */

import React from 'react';
import { Button } from 'tdesign-mobile-react';

export default function () {
  return (
    <div className="row section-group">
      <Button size="large" theme="light">
        填充按钮
      </Button>
      <Button size="large" theme="primary">
        填充按钮
      </Button>
    </div>
  );
}
