// skills/tdesign-react/references/examples/sticky-tool/compact.tsx
/**
 * TDesign TDesign React 示例：sticky-tool - compact
 * 覆盖组件：Sticky-tool
 * 来源：组件库源码 packages/components/sticky-tool/_example/compact.tsx
 */

import React from 'react';
import { AddIcon, ChatIcon, QrcodeIcon } from 'tdesign-icons-react';
import { Space, StickyTool } from 'tdesign-react';

import type { StickyToolProps } from 'tdesign-react';

const { StickyItem } = StickyTool;

export default function Compact() {
  const handleClick: StickyToolProps['onClick'] = (context) => {
    console.log('click', context);
  };
  const handleHover: StickyToolProps['onHover'] = (context) => {
    console.log('hover', context);
  };

  return (
    <Space>
      <StickyTool
        style={{ position: 'relative', overflow: 'hidden' }}
        type="compact"
        offset={[-500, -24]}
        onClick={handleClick}
        onHover={handleHover}
      >
        <StickyItem icon={<ChatIcon />} popup="chat"></StickyItem>
        <StickyItem icon={<AddIcon />} popup="add"></StickyItem>
        <StickyItem
          icon={<QrcodeIcon />}
          popup={<img alt="TDesign Logo" width="120" height="120" src="https://tdesign.gtimg.com/site/site.jpg" />}
          popupProps={{ overlayInnerStyle: { padding: '4px', height: '128px' } }}
        ></StickyItem>
      </StickyTool>
    </Space>
  );
}

// skills/tdesign-vue2/references/examples/sticky-tool/compact.vue
<!--
  TDesign TDesign Vue 2 示例：sticky-tool - compact
  覆盖组件：Sticky-tool
  来源：组件库源码 src/sticky-tool/_example/compact.vue
-->

<template>
  <t-space>
    <t-sticky-tool
      :style="{ position: 'relative', overflow: 'hidden' }"
      type="compact"
      :offset="[-500, -24]"
      @click="handleClick"
      @hover="handleHover"
    >
      <t-sticky-item :icon="renderChatIcon" popup="chat"> </t-sticky-item>
      <t-sticky-item :icon="renderAddIcon" popup="add"> </t-sticky-item>
      <t-sticky-item
        :icon="renderQrIcon"
        :popup="renderPopup"
        :popup-props="{ overlayInnerStyle: { padding: '4px', height: '128px' } }"
      >
      </t-sticky-item>
    </t-sticky-tool>
  </t-space>
</template>

<script lang="jsx">
import { ChatIcon, AddIcon, QrcodeIcon } from 'tdesign-icons-vue';

export default {
  methods: {
    renderChatIcon() {
      return <ChatIcon />;
    },
    renderAddIcon() {
      return <AddIcon />;
    },
    renderQrIcon() {
      return <QrcodeIcon />;
    },
    renderPopup() {
      return <img alt="TDesign Logo" width="120" height="120" src="https://tdesign.gtimg.com/site/site.jpg" />;
    },
    handleClick(context) {
      console.log('click', context);
    },
    handleHover(context) {
      console.log('hover', context);
    },
  },
};
</script>
