// skills/tdesign-react/references/examples/watermark/layout.tsx
/**
 * TDesign TDesign React 示例：watermark - layout
 * 覆盖组件：Watermark
 * 来源：组件库源码 packages/components/watermark/_example/layout.tsx
 */

import React from 'react';
import { Watermark } from 'tdesign-react';

export default function LayoutWatermark() {
  return (
    <>
      <h3>横平竖直的水印</h3>
      <Watermark watermarkContent={{ text: '文字水印' }} width={120} height={60} y={120} x={80}>
        <div style={{ height: 300 }}></div>
      </Watermark>

      <h3>错位的水印</h3>
      <Watermark watermarkContent={{ text: '文字水印' }} width={120} height={60} y={120} x={80} layout="hexagonal">
        <div style={{ height: 300 }}></div>
      </Watermark>
    </>
  );
}

// skills/tdesign-vue2/references/examples/watermark/layout.vue
<!--
  TDesign TDesign Vue 2 示例：watermark - layout
  覆盖组件：Watermark
  来源：组件库源码 src/watermark/_example/layout.vue
-->

<template>
  <div>
    <h3>横平竖直的水印</h3>
    <t-watermark
      :watermark-content="{
        text: '文字水印',
      }"
      :width="120"
      :height="60"
      :y="120"
      :x="80"
    >
      <div style="height: 300px" />
    </t-watermark>

    <h3>错位的水印</h3>
    <t-watermark
      :watermark-content="{
        text: '文字水印',
      }"
      :width="120"
      :height="60"
      :y="120"
      :x="80"
      layout="hexagonal"
    >
      <div style="height: 300px" />
    </t-watermark>
  </div>
</template>
