// skills/tdesign-react/references/examples/empty/status.tsx
/**
 * TDesign TDesign React 示例：empty - status
 * 覆盖组件：Empty
 * 来源：组件库源码 packages/components/empty/_example/status.tsx
 */

import React from 'react';
import { Col, Empty, Row } from 'tdesign-react';

export default function StatusExample() {
  return (
    <Row gutter={40}>
      <Col>
        <Empty type="empty" />
      </Col>
      <Col>
        <Empty type="maintenance" />
      </Col>
      <Col>
        <Empty type="network-error" />
      </Col>
      <Col>
        <Empty type="success" />
      </Col>
      <Col>
        <Empty type="fail" />
      </Col>
    </Row>
  );
}

// skills/tdesign-vue-next/references/examples/rate/status.vue
<!--
  TDesign TDesign Vue Next 示例：rate - status
  覆盖组件：Rate
  来源：组件库源码 packages/components/rate/_example/status.vue
-->

<template>
  <t-space direction="vertical">
    <h3>未评分状态</h3>
    <t-rate />
    <h3>满分状态</h3>
    <t-rate :default-value="5" />
    <h3>半星状态</h3>
    <t-rate :default-value="4.5" allow-half />
  </t-space>
</template>
