// skills/tdesign-mobile-react/references/examples/skeleton/animation.tsx
/**
 * TDesign TDesign Mobile React 示例：skeleton - animation
 * 覆盖组件：Skeleton
 * 来源：组件库源码 src/skeleton/_example/animation.tsx
 */

import React from 'react';
import { Skeleton } from 'tdesign-mobile-react';

const animations = [
  {
    title: '渐变加载效果',
    value: 'gradient',
    loading: true,
  },
  {
    title: '闪烁加载效果',
    value: 'flashed',
    loading: true,
  },
] as const;

export default function AnimationSkeleton() {
  return (
    <div>
      {animations.map((animation, index) => (
        <div key={index}>
          <div className="demo-section__desc">{animation.title}</div>
          <div className="demo-section__content">
            <Skeleton theme="paragraph" animation={animation.value} loading={animation.loading} />
          </div>
        </div>
      ))}
    </div>
  );
}

// skills/tdesign-mobile-vue/references/examples/skeleton/animation.vue
<!--
  TDesign TDesign Mobile Vue 示例：skeleton - animation
  覆盖组件：Skeleton
  来源：组件库源码 src/skeleton/demos/animation.vue
-->

<template>
  <div v-for="(animationItem, index) in animationList" :key="index">
    <div class="demo-section__desc">{{ animationItem.title }}</div>
    <div class="demo-section__content">
      <t-skeleton theme="paragraph" :animation="animationItem.value" :loading="animationItem.loading"></t-skeleton>
    </div>
  </div>
</template>
<script lang="ts" setup>
const animationList = [
  {
    title: '渐变加载效果',
    value: 'gradient',
    loading: true,
  },
  {
    title: '闪烁加载效果',
    value: 'flashed',
    loading: true,
  },
];
</script>
<style lang="less" scoped>
.demo-section__desc {
  font-size: 14px;
  color: var(--td-text-color-disabled, rgba(0, 0, 0, 0.4));
  margin-top: 8px;
  line-height: 22px;
}

.demo-section__content {
  margin-top: 16px;
  margin-bottom: 24px;
}
</style>
