// skills/tdesign-vue2/references/examples/list/operation.vue
<!--
  TDesign TDesign Vue 2 示例：list - operation
  覆盖组件：List
  来源：组件库源码 src/list/_example/operation.vue
-->

<template>
  <t-space direction="vertical">
    <t-list :split="true">
      <t-list-item>
        <t-list-item-meta :image="imageUrl" title="列表标题" description="列表内容列表内容"></t-list-item-meta>
        <template #action>
          <span>
            <t-link theme="primary" hover="color" style="margin-left: 16px">操作1</t-link>
            <t-link theme="primary" hover="color" style="margin-left: 16px">操作2</t-link>
            <t-link theme="primary" hover="color" style="margin-left: 16px">操作3</t-link>
          </span>
        </template>
      </t-list-item>
      <t-list-item>
        <t-list-item-meta :image="imageUrl" title="列表标题" description="列表内容列表内容"></t-list-item-meta>
        <template #action>
          <span>
            <t-link theme="primary" hover="color" style="margin-left: 16px">操作1</t-link>
            <t-link theme="primary" hover="color" style="margin-left: 16px">操作2</t-link>
            <t-link theme="primary" hover="color" style="margin-left: 16px">操作3</t-link>
          </span>
        </template>
      </t-list-item>
    </t-list>

    <t-list :split="true">
      <t-list-item>
        <t-list-item-meta :image="imageUrl" title="列表标题" description="列表内容列表内容"></t-list-item-meta>
        <template #action>
          <t-button variant="text" shape="square"><edit-icon /></t-button>
          <t-button variant="text" shape="square"><download-icon /></t-button>
        </template>
      </t-list-item>
      <t-list-item>
        <t-list-item-meta :image="imageUrl" title="列表标题" description="列表内容列表内容"></t-list-item-meta>
        <template #action>
          <t-button variant="text" shape="square"><edit-icon /></t-button>
          <t-button variant="text" shape="square"><download-icon /></t-button>
        </template>
      </t-list-item>
    </t-list>
  </t-space>
</template>

<script>
import { EditIcon, DownloadIcon } from 'tdesign-icons-vue';

export default {
  components: { EditIcon, DownloadIcon },
  data() {
    return {
      imageUrl: 'https://tdesign.gtimg.com/site/avatar.jpg',
    };
  },
};
</script>

// skills/tdesign-react/references/examples/list/operation.tsx
/**
 * TDesign TDesign React 示例：list - operation
 * 覆盖组件：List
 * 来源：组件库源码 packages/components/list/_example/operation.tsx
 */

import React from 'react';
import { DownloadIcon, EditIcon } from 'tdesign-icons-react';
import { Button, Link, List, Space } from 'tdesign-react';

const { ListItem, ListItemMeta } = List;

const avatarUrl = 'https://tdesign.gtimg.com/site/avatar.jpg';

export default function BasicList() {
  return (
    <Space direction="vertical" style={{ width: '100%' }}>
      <List>
        <ListItem
          action={
            <Space>
              <Link theme="primary" hover="color">
                操作1
              </Link>
              <Link theme="primary" hover="color">
                操作2
              </Link>
              <Link theme="primary" hover="color">
                操作3
              </Link>
            </Space>
          }
        >
          <ListItemMeta image={avatarUrl} title="列表主内容" description="列表内容列表内容" />
        </ListItem>
        <ListItem
          action={
            <Space>
              <Link theme="primary" hover="color">
                操作1
              </Link>
              <Link theme="primary" hover="color">
                操作2
              </Link>
              <Link theme="primary" hover="color">
                操作3
              </Link>
            </Space>
          }
        >
          <ListItemMeta image={avatarUrl} title="列表主内容" description="列表内容列表内容" />
        </ListItem>
      </List>

      <List split>
        <ListItem
          action={
            <Space>
              <Button variant="text" shape="square">
                <EditIcon />
              </Button>
              <Button variant="text" shape="square">
                <DownloadIcon />
              </Button>
            </Space>
          }
        >
          <ListItemMeta image={avatarUrl} title="列表主内容" description="列表内容列表内容" />
        </ListItem>
        <ListItem
          action={
            <Space>
              <Button variant="text" shape="square">
                <EditIcon />
              </Button>
              <Button variant="text" shape="square">
                <DownloadIcon />
              </Button>
            </Space>
          }
        >
          <ListItemMeta image={avatarUrl} title="列表主内容" description="列表内容列表内容" />
        </ListItem>
      </List>
    </Space>
  );
}
