// skills/tdesign-react/references/examples/link/size.tsx
/**
 * TDesign TDesign React 示例：link - size
 * 覆盖组件：Link
 * 来源：组件库源码 packages/components/link/_example/size.tsx
 */

import React from 'react';
import { JumpIcon } from 'tdesign-icons-react';
import { Link, Space } from 'tdesign-react';

export default function LinkExample() {
  return (
    <Space direction="vertical">
      <Space>
        <Link theme="default" size="small">
          跳转链接
        </Link>
        <Link theme="primary" size="small">
          跳转链接
        </Link>
        <Link theme="danger" size="small">
          跳转链接
        </Link>
        <Link theme="warning" size="small" disabled>
          跳转链接
        </Link>
        <Link theme="success" size="small" suffixIcon={<JumpIcon />}>
          跳转链接
        </Link>
      </Space>
      <Space>
        <Link theme="default" size="medium">
          跳转链接
        </Link>
        <Link theme="primary" size="medium">
          跳转链接
        </Link>
        <Link theme="danger" size="medium">
          跳转链接
        </Link>
        <Link theme="warning" size="medium" disabled>
          跳转链接
        </Link>
        <Link theme="success" size="medium" suffixIcon={<JumpIcon />}>
          跳转链接
        </Link>
      </Space>
      <Space>
        <Link theme="default" size="large">
          跳转链接
        </Link>
        <Link theme="primary" size="large">
          跳转链接
        </Link>
        <Link theme="danger" size="large">
          跳转链接
        </Link>
        <Link theme="warning" size="large" disabled>
          跳转链接
        </Link>
        <Link theme="success" size="large" suffixIcon={<JumpIcon />}>
          跳转链接
        </Link>
      </Space>
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/back-top/size.vue
<!--
  TDesign TDesign Vue Next 示例：back-top - size
  覆盖组件：Back-top
  来源：组件库源码 packages/components/back-top/_example/size.vue
-->

<template>
  <t-space style="position: relative" direction="vertical">
    <t-space>
      <t-back-top
        style="position: relative"
        :visible-height="0"
        size="medium"
        :offset="[0, 0]"
        theme="light"
      ></t-back-top>
      <t-back-top
        style="position: relative"
        :visible-height="0"
        size="medium"
        :offset="[0, 0]"
        theme="primary"
      ></t-back-top>
      <t-back-top
        style="position: relative"
        :visible-height="0"
        size="medium"
        :offset="[0, 0]"
        theme="dark"
      ></t-back-top>
    </t-space>
    <t-space>
      <t-back-top
        style="position: relative"
        :visible-height="0"
        size="small"
        :offset="[0, 0]"
        theme="light"
      ></t-back-top>
      <t-back-top
        style="position: relative"
        :visible-height="0"
        size="small"
        :offset="[0, 0]"
        theme="primary"
      ></t-back-top>
      <t-back-top
        style="position: relative"
        :visible-height="0"
        size="small"
        :offset="[0, 0]"
        theme="dark"
      ></t-back-top>
    </t-space>
  </t-space>
</template>
