// skills/tdesign-mobile-vue/references/examples/checkbox/card.vue
<!--
  TDesign TDesign Mobile Vue 示例：checkbox - card
  覆盖组件：Checkbox
  来源：组件库源码 src/checkbox/demos/card.vue
-->

<template>
  <t-checkbox-group class="theme-card" :default-value="['1', '2']">
    <t-checkbox value="1" label="多选" />
    <t-checkbox value="2" label="多选" />
    <t-checkbox value="3" label="多选标题多行多选标题多行多选标题多行多选标题多行多选标题多行多选标题" />
  </t-checkbox-group>
</template>
<style lang="less" scoped>
.theme-card {
  border-radius: 12px;
  margin: 0 16px;
  overflow: hidden;
}
</style>

// skills/tdesign-mobile-react/references/examples/checkbox/card.tsx
/**
 * TDesign TDesign Mobile React 示例：checkbox - card
 * 覆盖组件：Checkbox
 * 来源：组件库源码 src/checkbox/_example/card.tsx
 */

import React from 'react';
import { Checkbox } from 'tdesign-mobile-react';

export default function () {
  return (
    <Checkbox.Group className="theme-card" defaultValue={['1', '2']}>
      <Checkbox label="多选" value="1" />
      <Checkbox label="多选" value="2" />
      <Checkbox label="多选标题多行多选标题多行多选标题多行多选标题多行多选标题多行多选标题" value="3" />
    </Checkbox.Group>
  );
}
