// skills/tdesign-mobile-vue/references/examples/checkbox/right.vue
<!--
  TDesign TDesign Mobile Vue 示例：checkbox - right
  覆盖组件：Checkbox
  来源：组件库源码 src/checkbox/demos/right.vue
-->

<template>
  <t-checkbox value="1" label="多选" default-checked />
  <view class="box" style="height: 16px" />
  <t-checkbox value="2" label="多选" placement="right" default-checked />
</template>

// skills/tdesign-mobile-react/references/examples/checkbox/right.tsx
/**
 * TDesign TDesign Mobile React 示例：checkbox - right
 * 覆盖组件：Checkbox
 * 来源：组件库源码 src/checkbox/_example/right.tsx
 */

import React from 'react';
import { Checkbox } from 'tdesign-mobile-react';

export default function () {
  return (
    <>
      <Checkbox label="多选" value="checkbox1" />
      <Checkbox label="多选" placement="right" value="checkbox2" defaultChecked />
    </>
  );
}
