// skills/tdesign-vue-next/references/examples/qrcode/customSize.vue
<!--
  TDesign TDesign Vue Next 示例：qrcode - customSize
  覆盖组件：Qrcode
  来源：组件库源码 packages/components/qrcode/_example/customSize.vue
-->

<template>
  <t-space direction="vertical">
    <t-space>
      <t-button :disabled="size <= minSize" @click="size -= 10">
        <template #icon>
          <MinusIcon />
        </template>
        Smaller
      </t-button>
      <t-button :disabled="size >= maxSize" @click="size += 10">
        <template #icon>
          <AddIcon />
        </template>
        Larger
      </t-button>
    </t-space>
    <t-qrcode
      level="H"
      :size="size"
      :icon-size="size / 4"
      value="https://tdesign.tencent.com/"
      icon="https://tdesign.gtimg.com/site/tdesign-logo.png"
    />
  </t-space>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { MinusIcon, AddIcon } from 'tdesign-icons-vue-next';
import type { QRCodeProps } from 'tdesign-vue-next';

const minSize = 40;
const maxSize = 300;

const size = ref<QRCodeProps['size']>(160);
</script>

// skills/tdesign-react/references/examples/qrcode/customSize.tsx
/**
 * TDesign TDesign React 示例：qrcode - customSize
 * 覆盖组件：Qrcode
 * 来源：组件库源码 packages/components/qrcode/_example/customSize.tsx
 */

import React, { useState } from 'react';
import { AddIcon, MinusIcon } from 'tdesign-icons-react';
import { Button, QRCode, Space } from 'tdesign-react';

const MIN_SIZE = 48;
const MAX_SIZE = 300;

export default function QRCodeExample() {
  const [size, setSize] = useState<number>(160);

  const increase = () => {
    setSize((prevSize) => {
      const newSize = prevSize + 10;
      if (newSize >= MAX_SIZE) {
        return MAX_SIZE;
      }
      return newSize;
    });
  };

  const decline = () => {
    setSize((prevSize) => {
      const newSize = prevSize - 10;
      if (newSize <= MIN_SIZE) {
        return MIN_SIZE;
      }
      return newSize;
    });
  };

  return (
    <>
      <Space style={{ marginBottom: 16, userSelect: 'none' }}>
        <Button onClick={decline} disabled={size <= MIN_SIZE} icon={<MinusIcon />}>
          Smaller
        </Button>
        <Button onClick={increase} disabled={size >= MAX_SIZE} icon={<AddIcon />}>
          Larger
        </Button>
      </Space>
      <p style={{ minHeight: '160px' }}>
        <QRCode
          level="H"
          size={size}
          iconSize={size / 4}
          value="https://tdesign.tencent.com/"
          icon="https://tdesign.gtimg.com/site/tdesign-logo.png"
        />
      </p>
    </>
  );
}
