// skills/tdesign-vue-next/references/examples/qrcode/level.vue
<!--
  TDesign TDesign Vue Next 示例：qrcode - level
  覆盖组件：Qrcode
  来源：组件库源码 packages/components/qrcode/_example/level.vue
-->

<template>
  <t-space direction="vertical">
    <t-radio-group v-model="level" variant="default-filled">
      <t-radio-button value="L">L</t-radio-button>
      <t-radio-button value="M">M</t-radio-button>
      <t-radio-button value="Q">Q</t-radio-button>
      <t-radio-button value="H">H</t-radio-button>
    </t-radio-group>
    <t-qrcode :level="level" value="https://tdesign.gtimg.com/site/tdesign-logo.png" />
  </t-space>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import type { QRCodeProps } from 'tdesign-vue-next';

const level = ref<QRCodeProps['level']>('M');
</script>

// skills/tdesign-react/references/examples/qrcode/level.tsx
/**
 * TDesign TDesign React 示例：qrcode - level
 * 覆盖组件：Qrcode
 * 来源：组件库源码 packages/components/qrcode/_example/level.tsx
 */

import React, { useState } from 'react';
import { QRCode, Radio, Space } from 'tdesign-react';

import type { QrCodeProps } from 'tdesign-react';

export default function QRCodeExample() {
  const [level, setLevel] = useState<QrCodeProps['level']>('L');
  const onChange = (value: QrCodeProps['level']) => {
    setLevel(value);
  };

  return (
    <Space direction="vertical">
      <Radio.Group value={level} variant="default-filled" onChange={onChange}>
        <Radio.Button value="L">L</Radio.Button>
        <Radio.Button value="M">M</Radio.Button>
        <Radio.Button value="Q">Q</Radio.Button>
        <Radio.Button value="H">H</Radio.Button>
      </Radio.Group>

      <QRCode style={{ marginBottom: 16 }} level={level} value={'https://tdesign.gtimg.com/site/tdesign-logo.png'} />
    </Space>
  );
}
