// skills/tdesign-mobile-vue/references/examples/link/prefix.vue
<!--
  TDesign TDesign Mobile Vue 示例：link - prefix
  覆盖组件：Link
  来源：组件库源码 src/link/demos/prefix.vue
-->

<template>
  <div class="tdesign-mobile-link-demo">
    <t-link hover theme="primary">
      <template #prefixIcon>
        <link-icon />
      </template>
      跳转链接
    </t-link>
    <t-link>
      <template #prefixIcon>
        <link-icon />
      </template>
      跳转链接
    </t-link>
  </div>
</template>
<script lang="ts" setup>
import { LinkIcon } from 'tdesign-icons-vue-next';
</script>

<style scoped>
.tdesign-mobile-link-demo {
  height: 48px;
  background-color: var(--bg-color-demo, #fff);
  display: flex;
  justify-content: space-evenly;
  margin-bottom: 6.4vw;
  align-items: center;
}
</style>

// skills/tdesign-mobile-react/references/examples/link/prefix.tsx
/**
 * TDesign TDesign Mobile React 示例：link - prefix
 * 覆盖组件：Link
 * 来源：组件库源码 src/link/_example/prefix.tsx
 */

import React from 'react';
import { LinkIcon } from 'tdesign-icons-react';
import { Link } from 'tdesign-mobile-react';

export default function Prefix() {
  return (
    <div className="demo-content">
      <Link size="small" theme="primary" hover prefixIcon={<LinkIcon />}>
        跳转链接
      </Link>
      <Link size="small" hover prefixIcon={<LinkIcon />}>
        跳转链接
      </Link>
    </div>
  );
}
