// skills/tdesign-vue2/references/examples/transfer/empty.vue
<!--
  TDesign TDesign Vue 2 示例：transfer - empty
  覆盖组件：Transfer
  来源：组件库源码 src/transfer/_example/empty.vue
-->

<template>
  <t-space direction="vertical">
    <p style="margin: 10px 0">默认暂无数据</p>
    <t-transfer :data="list" />
    <p style="margin: 10px">自定义空状态</p>
    <t-transfer :data="list" empty="No Data" />
  </t-space>
</template>
<script>
const initialList = [];
export default {
  data() {
    return {
      list: initialList,
    };
  },
};
</script>

// skills/tdesign-react/references/examples/tree/empty.tsx
/**
 * TDesign TDesign React 示例：tree - empty
 * 覆盖组件：Tree
 * 来源：组件库源码 packages/components/tree/_example/empty.tsx
 */

import React from 'react';
import { Space, Tree } from 'tdesign-react';

import type { TreeProps } from 'tdesign-react';

export default () => {
  const empty: TreeProps['empty'] = <div>😊 空数据（ empty props ）</div>;

  return (
    <Space direction="vertical">
      <Tree data={[]} />

      <Tree data={[]} empty="😊 空数据（string）" />

      <Tree data={[]} empty={empty} />
    </Space>
  );
};
