// skills/tdesign-vue-next/references/examples/tree/expand-all.vue
<!--
  TDesign TDesign Vue Next 示例：tree - expand-all
  覆盖组件：Tree
  来源：组件库源码 packages/components/tree/_example/expand-all.vue
-->

<template>
  <t-space direction="vertical">
    <t-space>
      <span>切换数据:</span>
      <t-switch @change="toggleData" />
    </t-space>
    <t-space>
      <span>展开动画:</span>
      <t-switch v-model="transition" />
    </t-space>
    <t-tree :data="items" :label="label" expand-all :transition="transition" />
  </t-space>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import type { TreeProps, SwitchProps } from 'tdesign-vue-next';

const data1 = [
  {
    value: 't1',
    children: [
      {
        value: 't1.1',
        children: [
          {
            value: 't1.1.1',
          },
          {
            value: 't1.1.2',
          },
        ],
      },
      {
        value: 't1.2',
        children: [
          {
            value: '1.2.1',
          },
          {
            value: '1.2.2',
          },
        ],
      },
    ],
  },
  {
    value: 't2',
    children: [
      {
        value: 't2.1',
      },
      {
        value: 't2.2',
      },
    ],
  },
];
const data2 = [
  {
    value: 'd1',
    children: [
      {
        value: 'd1.1',
        label: 'd1.1 custom label',
        children: [
          {
            value: 'd1.1.1',
          },
        ],
      },
      {
        value: 'd1.2',
        children: [
          {
            value: 'd1.2.1',
          },
          {
            value: 'd1.2.2',
          },
        ],
      },
    ],
  },
  {
    value: 'd2',
    children: [
      {
        value: 'd2.1',
      },
      {
        value: 'd2.2',
      },
    ],
  },
];
const transition = ref(true);
const items = ref<TreeProps['data']>(data1);
const toggleData: SwitchProps['onChange'] = () => {
  const tmpItems = items.value[0].value === 't1' ? data2 : data1;
  items.value = tmpItems;
};
const label: TreeProps['label'] = (h, node) => {
  return node.label || String(node.value);
};
</script>

// skills/tdesign-react/references/examples/tree/expand-all.tsx
/**
 * TDesign TDesign React 示例：tree - expand-all
 * 覆盖组件：Tree
 * 来源：组件库源码 packages/components/tree/_example/expand-all.tsx
 */

import React, { useState } from 'react';
import { Form, Space, Switch, Tree } from 'tdesign-react';

const data1 = [
  {
    label: '1',
    children: [
      {
        label: '1.1',
        children: [
          {
            label: '1.1.1',
          },
          {
            label: '1.1.2',
          },
        ],
      },
      {
        label: '1.2',
        children: [
          {
            label: '1.2.1',
          },
          {
            label: '1.2.2',
          },
        ],
      },
    ],
  },
  {
    label: '2',
    children: [
      {
        label: '2.1',
      },
      {
        label: '2.2',
      },
    ],
  },
];

const data2 = [
  {
    label: '1',
  },
  {
    label: '2',
  },
  {
    label: '3',
    children: [
      {
        label: '3.1',
      },
      {
        label: '3.2',
      },
    ],
  },
];

export default () => {
  const [items, setItems] = useState<typeof data1 | typeof data2>(data1);
  const [hover, setHover] = useState(true);
  const [transition, setTransition] = useState(true);

  const handleItemsChange = () => {
    setItems((v) => (v === data1 ? data2 : data1));
  };

  return (
    <Space direction="vertical">
      <Form labelWidth={150}>
        <Form.FormItem label="切换数据">
          <Switch onChange={handleItemsChange} />
        </Form.FormItem>
        <Form.FormItem label="提供 hover 状态" initialData={hover}>
          <Switch<boolean> onChange={setHover} />
        </Form.FormItem>
        <Form.FormItem label="展开动画" initialData={transition}>
          <Switch<boolean> onChange={setTransition} />
        </Form.FormItem>
      </Form>
      <Tree data={items} expandAll hover={hover} transition={transition} />
    </Space>
  );
};
