// skills/tdesign-vue2/references/examples/swiper/placement.vue
<!--
  TDesign TDesign Vue 2 示例：swiper - placement
  覆盖组件：Swiper
  来源：组件库源码 src/swiper/_example/placement.vue
-->

<template>
  <div class="tdesign-demo-block--swiper">
    <t-swiper :navigation="{ placement: 'outside' }">
      <t-swiper-item>
        <div class="demo-item">1</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">2</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">3</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">4</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">5</div>
      </t-swiper-item>
      <t-swiper-item>
        <div class="demo-item">6</div>
      </t-swiper-item>
    </t-swiper>
  </div>
</template>

// skills/tdesign-mobile-react/references/examples/collapse/placement.tsx
/**
 * TDesign TDesign Mobile React 示例：collapse - placement
 * 覆盖组件：Collapse
 * 来源：组件库源码 src/collapse/_example/placement.tsx
 */

import React from 'react';
import { Collapse, CollapsePanel } from 'tdesign-mobile-react';

export default function () {
  return (
    <Collapse>
      <CollapsePanel value="0" placement="top" header="折叠面板标题">
        <div className="content">
          此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容可自定义内容
        </div>
      </CollapsePanel>
    </Collapse>
  );
}
