// skills/tdesign-react/references/examples/config-provider/calendar.tsx
/**
 * TDesign TDesign React 示例：config-provider - calendar
 * 覆盖组件：Config-provider
 * 来源：组件库源码 packages/components/config-provider/_example/calendar.tsx
 */

import React from 'react';
import { Calendar, ConfigProvider } from 'tdesign-react';
import enConfig from 'tdesign-react/es/locale/en_US';

import type { GlobalConfigProvider } from 'tdesign-react';

const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export default function configDemo() {
  // 全局特性配置，可以引入英文默认配置 enConfig，还可以在默认配置的基础上进行自定义配置
  const globalConfig: GlobalConfigProvider = {
    ...enConfig,
    calendar: {
      yearSelection: '{year}',
      // 1 表示周一；7 表示周日
      firstDayOfWeek: 7,
      monthSelection: ({ month }) => MONTHS[month - 1],
      yearRadio: 'Year',
      monthRadio: 'Month',
      hideWeekend: 'Hide Weekend',
      showWeekend: 'Show Weekend',
      today: 'Today',
      thisMonth: 'This Month',
      week: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].join(),
      cellMonth: MONTHS.join(),
      fillWithZero: false,
      controllerConfig: {
        year: {
          visible: true,
          selectProps: {
            size: 'small',
          },
        },
        month: {
          visible: true,
          selectProps: {
            size: 'small',
          },
        },
        mode: {
          visible: true,
          radioGroupProps: {
            size: 'small',
          },
        },
        weekend: {
          visible: true,
          showWeekendButtonProps: {
            size: 'small',
          },
          hideWeekendButtonProps: {
            size: 'small',
          },
        },
        current: {
          visible: true,
          currentDayButtonProps: {
            theme: 'warning',
            size: 'small',
          },
          currentMonthButtonProps: {
            theme: 'success',
            size: 'small',
          },
        },
      },
    },
  };

  return (
    <ConfigProvider globalConfig={globalConfig}>
      <Calendar />
    </ConfigProvider>
  );
}

// skills/tdesign-vue-next/references/examples/config-provider/calendar.vue
<!--
  TDesign TDesign Vue Next 示例：config-provider - calendar
  覆盖组件：Config-provider
  来源：组件库源码 packages/components/config-provider/_example/calendar.vue
-->

<template>
  <t-config-provider :global-config="globalConfig">
    <t-calendar />
  </t-config-provider>
</template>

<script lang="ts" setup>
import { merge } from 'lodash-es';
import enConfig from 'tdesign-vue-next/es/locale/en_US';
import type { GlobalConfigProvider } from 'tdesign-vue-next';

const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

// 全局特性配置，可以引入英文默认配置 enConfig，还可以在默认配置的基础上进行自定义配置
const empty: GlobalConfigProvider = {};
const customConfig: GlobalConfigProvider = {
  calendar: {
    yearSelection: '{year}',
    // 1 表示周一；7 表示周日
    firstDayOfWeek: 7,
    monthSelection: ({ month }) => MONTHS[month - 1],
    yearRadio: 'Year',
    monthRadio: 'Month',
    hideWeekend: 'Hide Weekend',
    showWeekend: 'Show Weekend',
    today: 'Today',
    thisMonth: 'This Month',
    week: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].join(),
    cellMonth: MONTHS.join(),
    fillWithZero: false,
    controllerConfig: {
      year: {
        visible: true,
        selectProps: {
          size: 'small',
        },
      },
      month: {
        visible: true,
        selectProps: {
          size: 'small',
        },
      },
      mode: {
        visible: true,
        radioGroupProps: {
          size: 'small',
        },
      },
      weekend: {
        visible: true,
        showWeekendButtonProps: {
          size: 'small',
        },
        hideWeekendButtonProps: {
          size: 'small',
        },
      },
      current: {
        visible: true,
        currentDayButtonProps: {
          theme: 'warning',
          size: 'small',
        },
        currentMonthButtonProps: {
          theme: 'success',
          size: 'small',
        },
      },
    },
  },
};
const globalConfig = merge(empty, enConfig, customConfig);
</script>
