// skills/tdesign-react/references/examples/config-provider/pagination.tsx
/**
 * TDesign TDesign React 示例：config-provider - pagination
 * 覆盖组件：Config-provider
 * 来源：组件库源码 packages/components/config-provider/_example/pagination.tsx
 */

import React, { useEffect, useState } from 'react';
import { ConfigProvider, Pagination } from 'tdesign-react';
import enConfig from 'tdesign-react/es/locale/en_US';

import type { GlobalConfigProvider } from 'tdesign-react';
import type { JumperProps } from '../type';

const GlobalJumper: React.FC<JumperProps> = ({ current, pageCount, onChange }) => {
  const [jumpValue, setJumpValue] = useState<number>(current);

  useEffect(() => {
    setJumpValue(current);
  }, [current]);

  return (
    <>
      <div className="t-pagination__jump">
        <input
          className="t-input__inner"
          type="text"
          style={{ width: 10 }}
          value={jumpValue}
          onChange={(e) => setJumpValue(Number(e.target.value))}
        />
        <span> / {pageCount} 页 </span>
        <button onClick={() => onChange(jumpValue)}> 跳转 </button>
      </div>
    </>
  );
};

export default function configDemo() {
  // 全局特性配置，可以引入英文默认配置 enConfig，还可以在默认配置的基础上进行自定义配置
  const globalConfig: GlobalConfigProvider = {
    ...enConfig,
    pagination: {
      itemsPerPage: '{size} / page',
      jumpTo: 'jump to',
      total: 'Total {count} items',
      jumper: GlobalJumper,
    },
  };

  return (
    <ConfigProvider globalConfig={globalConfig}>
      <Pagination total={36} showJumper maxPageBtn={5} />
    </ConfigProvider>
  );
}

// skills/tdesign-vue-next/references/examples/config-provider/pagination.vue
<!--
  TDesign TDesign Vue Next 示例：config-provider - pagination
  覆盖组件：Config-provider
  来源：组件库源码 packages/components/config-provider/_example/pagination.vue
-->

<template>
  <t-config-provider :global-config="globalConfig">
    <div class="tdesign-demo-item--locale-provider-base">
      <t-pagination v-model="current" :total="36" show-jumper :max-page-btn="5" />
    </div>
  </t-config-provider>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import type { GlobalConfigProvider } from 'tdesign-vue-next';

const current = ref(1);
const globalConfig: GlobalConfigProvider = {
  pagination: {
    itemsPerPage: '{size} / page',
    jumpTo: 'jump to',
    page: '',
    total: 'Total {count} items',
  },
};
</script>
