// skills/tdesign-vue2/references/examples/breadcrumb/options.vue
<!--
  TDesign TDesign Vue 2 示例：breadcrumb - options
  覆盖组件：Breadcrumb
  来源：组件库源码 src/breadcrumb/_example/options.vue
-->

<template>
  <t-breadcrumb :options="options"> </t-breadcrumb>
</template>

<script>
export default {
  name: 'options',
  data() {
    return {
      options: [{ content: '页面1' }, { content: '页面2' }, { content: '页面3', href: '//tdesign.tencent.com/' }],
    };
  },
};
</script>

// skills/tdesign-react/references/examples/breadcrumb/options.tsx
/**
 * TDesign TDesign React 示例：breadcrumb - options
 * 覆盖组件：Breadcrumb
 * 来源：组件库源码 packages/components/breadcrumb/_example/options.tsx
 */

import React from 'react';
import { Breadcrumb } from 'tdesign-react';

export default function BreadcrumbExample() {
  const options = [{ content: '页面1' }, { content: '页面2' }, { content: '页面3', href: 'https://github.com/' }];
  return <Breadcrumb options={options} />;
}
