// skills/tdesign-vue-next/references/examples/alert/title.vue
<!--
  TDesign TDesign Vue Next 示例：alert - title
  覆盖组件：Alert
  来源：组件库源码 packages/components/alert/_example/title.vue
-->

<template>
  <t-space style="width: 100%">
    <t-alert theme="info" title="这是一条普通的消息提示" message="这是与普通的消息提示相关的文字辅助说明" close-btn>
      <template #operation>
        <span @click="handleOperation">相关操作</span>
      </template>
    </t-alert>
  </t-space>
</template>
<script lang="tsx" setup>
const handleOperation = () => {
  alert('operation clicked');
};
</script>

// skills/tdesign-react/references/examples/alert/title.tsx
/**
 * TDesign TDesign React 示例：alert - title
 * 覆盖组件：Alert
 * 来源：组件库源码 packages/components/alert/_example/title.tsx
 */

import React from 'react';
import { Alert } from 'tdesign-react';

export default function AlertDescription() {
  const operation = <span>相关操作</span>;
  return (
    <Alert
      message="这是一条普通的消息提示描述，这是一条普通的消息提示描述"
      title="这是一条普通的消息提示"
      operation={operation}
      closeBtn
    />
  );
}
