// skills/tdesign-react/references/examples/alert/close.tsx
/**
 * TDesign TDesign React 示例：alert - close
 * 覆盖组件：Alert
 * 来源：组件库源码 packages/components/alert/_example/close.tsx
 */

import React from 'react';
import { Alert, Space, Tag } from 'tdesign-react';

export default function AlertClose() {
  // eslint-disable-next-line no-alert
  const beforeClose = () => window.confirm('确认关闭吗？');

  const handleClosed = () => {
    console.log('关闭');
  };

  const warningClose = () => 'FunctionPropClose';

  return (
    <Space direction="vertical">
      <Alert theme="success" message="这是一条成功的消息提示" closeBtn />
      <Alert theme="info" message="这是一条普通的消息提示" closeBtn="知道了" onClose={beforeClose} />
      <Alert
        theme="warning"
        message="这是一条警示消息"
        closeBtn={warningClose()}
        onClose={beforeClose}
        onClosed={handleClosed}
      />
      <Alert
        theme="error"
        message="高危操作/出错信息提示"
        closeBtn={
          <Tag variant="outline" theme="danger">
            关闭
          </Tag>
        }
      />
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/alert/close.vue
<!--
  TDesign TDesign Vue Next 示例：alert - close
  覆盖组件：Alert
  来源：组件库源码 packages/components/alert/_example/close.vue
-->

<template>
  <t-space style="width: 100%" direction="vertical">
    <t-alert theme="success" message="这是一条成功的消息提示" :close-btn="true" />
    <t-alert theme="info" message="这是一条普通的消息提示" close-btn="知道了" @close="beforeClose" />
    <t-alert
      theme="warning"
      message="这是一条警示信息"
      :close-btn="warningClose"
      @close="beforeClose"
      @closed="handleClosed"
    />
    <t-alert theme="error" message="高危操作/出错信息提示">
      <template #close-btn>
        <t-tag variant="outline" theme="danger">关闭</t-tag>
      </template>
    </t-alert>
  </t-space>
</template>

<script lang="tsx" setup>
import type { AlertProps } from 'tdesign-vue-next';

const beforeClose: AlertProps['onClose'] = () => window.confirm('确认关闭吗？');

const handleClosed: AlertProps['onClosed'] = () => {
  console.log('关闭');
};

const warningClose: AlertProps['closeBtn'] = () => 'FunctionPropClose';
</script>
