// skills/tdesign-mobile-react/references/examples/search/other.tsx
/**
 * TDesign TDesign Mobile React 示例：search - other
 * 覆盖组件：Search
 * 来源：组件库源码 src/search/_example/other.tsx
 */

import React from 'react';
import { Search } from 'tdesign-mobile-react';

export default function Other() {
  const onChange = (val: string) => {
    console.log('change: ', val);
  };
  return (
    <div className="search-example">
      <Search placeholder="搜索预设文案" onChange={onChange} />
    </div>
  );
}

// skills/tdesign-mobile-vue/references/examples/search/other.vue
<!--
  TDesign TDesign Mobile Vue 示例：search - other
  覆盖组件：Search
  来源：组件库源码 src/search/demos/other.vue
-->

<template>
  <div class="example-search">
    <t-search placeholder="搜索预设文案" center @change="onChange"></t-search>
  </div>
</template>

<script lang="ts" setup>
const onChange = (val: string) => {
  console.log('change: ', val);
};
</script>
