// skills/tdesign-react/references/examples/select-input/borderless-multiple.tsx
/**
 * TDesign TDesign React 示例：select-input - borderless-multiple
 * 覆盖组件：Select-input
 * 来源：组件库源码 packages/components/select-input/_example/borderless-multiple.tsx
 */

import React, { useEffect, useState } from 'react';
import { ChevronDownIcon } from 'tdesign-icons-react';
import { Checkbox, SelectInput } from 'tdesign-react';

import type { CheckboxGroupProps, CheckboxOptionObj, TagInputChangeContext, TagInputValue } from 'tdesign-react';

const classStyles = `
<style>
.tdesign-demo__panel-options-borderless-multiple {
  width: 100%;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.tdesign-demo__panel-options-borderless-multiple .t-checkbox {
  display: flex;
  border-radius: 3px;
  line-height: 22px;
  cursor: pointer;
  padding: 3px 8px;
  color: var(--td-text-color-primary);
  transition: background-color 0.2s linear;
  white-space: nowrap;
  word-wrap: normal;
  overflow: hidden;
  text-overflow: ellipsis;
  margin: 0;
}

.tdesign-demo__panel-options-borderless-multiple .t-checkbox:hover {
  background-color: var(--td-bg-color-container-hover);
}
</style>
`;

const OPTIONS: CheckboxOptionObj[] = [
  // 全选
  { label: 'Check All', checkAll: true },
  { label: 'tdesign-vue', value: 1 },
  { label: 'tdesign-react', value: 2 },
  { label: 'tdesign-miniprogram', value: 3 },
  { label: 'tdesign-angular', value: 4 },
  { label: 'tdesign-mobile-vue', value: 5 },
  { label: 'tdesign-mobile-react', value: 6 },
];

export default function SelectInputMultiple() {
  const [options, setOptions] = useState([...OPTIONS]);
  const [value, setValue] = useState<CheckboxOptionObj[]>([
    { label: 'Vue', value: 1 },
    { label: 'React', value: 2 },
    { label: 'Miniprogram', value: 3 },
  ]);

  const getCheckboxValue = () => {
    const arr = [];
    const list = value;
    // 此处不使用 forEach，减少函数迭代
    for (let i = 0, len = list.length; i < len; i++) {
      list[i].value && arr.push(list[i].value);
    }
    return arr;
  };

  const checkboxValue = getCheckboxValue();

  // 直接 checkboxgroup 组件渲染输出下拉选项，自定义处理可以避免顺序和 tagChange 冲突
  const onCheckedChange: CheckboxGroupProps['onChange'] = (val, { current, type }) => {
    // current 不存在，则表示操作全选
    if (!current) {
      const newValue = type === 'check' ? options.slice(1) : [];
      setValue(newValue);
      return;
    }
    // 普通操作
    if (type === 'check') {
      const option = options.find((t) => t.value === current);
      setValue(value.concat(option));
    } else {
      const newValue = value.filter((v) => v.value !== current);
      setValue(newValue);
    }
  };

  // 可以根据触发来源，自由定制标签变化时的筛选器行为
  const onTagChange = (currentTags: TagInputValue, context: TagInputChangeContext) => {
    const { trigger, index, item } = context;
    if (trigger === 'clear') {
      setValue([]);
    }
    if (['tag-remove', 'backspace'].includes(trigger)) {
      const newValue = [...value];
      newValue.splice(index, 1);
      setValue(newValue);
    }
    // 如果允许创建新条目
    if (trigger === 'enter') {
      const current = { label: item, value: item };
      const newValue = [...value];
      setValue(newValue.concat(current));
      setOptions(options.concat(current));
    }
  };

  useEffect(() => {
    // 添加示例代码所需样式
    document.head.insertAdjacentHTML('beforeend', classStyles);
  }, []);

  return (
    <div style={{ width: '60%' }}>
      <SelectInput
        allowInput
        borderless
        clearable
        multiple
        value={value}
        minCollapsedNum={1}
        placeholder="select frameworks"
        suffixIcon={<ChevronDownIcon />}
        onTagChange={onTagChange}
        panel={
          <Checkbox.Group
            value={checkboxValue}
            options={options}
            className="tdesign-demo__panel-options-borderless-multiple"
            onChange={onCheckedChange}
          />
        }
      />
    </div>
  );
}

// skills/tdesign-vue-next/references/examples/select-input/borderless-multiple.vue
<!--
  TDesign TDesign Vue Next 示例：select-input - borderless-multiple
  覆盖组件：Select-input
  来源：组件库源码 packages/components/select-input/_example/borderless-multiple.vue
-->

<template>
  <div class="tdesign-demo__select-input-borderless-multiple" style="width: 100%">
    <t-select-input
      :value="value"
      :min-collapsed-num="1"
      :popup-props="{ overlayInnerStyle: { padding: '6px' } }"
      borderless
      allow-input
      placeholder="select frameworks"
      clearable
      multiple
      style="width: 250px"
      @tag-change="onTagChange"
    >
      <template #panel>
        <t-checkbox-group
          :value="checkboxValue"
          :options="options"
          class="tdesign-demo__panel-options-borderless-multiple"
          @change="onCheckedChange"
        />
      </template>
    </t-select-input>
  </div>
</template>
<script lang="ts" setup>
import { computed, ref } from 'vue';
import type { CheckboxGroupProps, SelectInputProps } from 'tdesign-vue-next';

interface CustomOptionInfo {
  label: string;
  value?: number;
  checkAll?: boolean;
}
const OPTIONS: CustomOptionInfo[] = [
  // 全选
  {
    label: 'all frameworks',
    checkAll: true,
  },
  {
    label: 'tdesign-vue',
    value: 1,
  },
  {
    label: 'tdesign-react',
    value: 2,
  },
  {
    label: 'tdesign-miniprogram',
    value: 3,
  },
  {
    label: 'tdesign-angular',
    value: 4,
  },
  {
    label: 'tdesign-mobile-vue',
    value: 5,
  },
  {
    label: 'tdesign-mobile-react',
    value: 6,
  },
];
const options = ref<CustomOptionInfo[]>([...OPTIONS]);
const value = ref<CustomOptionInfo[]>([
  {
    label: 'Vue',
    value: 1,
  },
  {
    label: 'React',
    value: 2,
  },
  {
    label: 'Miniprogram',
    value: 3,
  },
]);
const checkboxValue = computed<CheckboxGroupProps['value']>(() => {
  const arr = [];
  const list = value.value;
  // 此处不使用 forEach，减少函数迭代
  for (let i = 0, len = list.length; i < len; i++) {
    list[i].value && arr.push(list[i].value);
  }
  return arr;
});

// 直接 checkboxgroup 组件渲染输出下拉选项
const onCheckedChange: CheckboxGroupProps['onChange'] = (val, { current, type }) => {
  // current 不存在，则表示操作全选
  if (!current) {
    value.value =
      type === 'check'
        ? options.value.slice(1).map((option) => ({
            ...option,
            value: option?.value || 0,
          }))
        : [];
    return;
  }
  // 普通操作
  if (type === 'check') {
    const option = options.value.find((t) => t.value === current);
    value.value.push(option);
  } else {
    value.value = value.value.filter((v) => v.value !== current);
  }
};

// 可以根据触发来源，自由定制标签变化时的筛选器行为
const onTagChange: SelectInputProps['onTagChange'] = (currentTags, context) => {
  console.log(currentTags, context);
  const { trigger, index, item } = context;
  if (trigger === 'clear') {
    value.value = [];
  }
  if (['tag-remove', 'backspace'].includes(trigger)) {
    value.value.splice(index, 1);
  }
  // 如果允许创建新条目
  if (trigger === 'enter') {
    const current = {
      label: item.toString(),
      value: Number(item) || index,
    };
    value.value.push(current);
    options.value = options.value.concat(current);
  }
};
</script>
<style lang="less">
.tdesign-demo__panel-options-borderless-multiple {
  width: 100%;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.tdesign-demo__panel-options-borderless-multiple .t-checkbox {
  display: flex;
  border-radius: 3px;
  line-height: 22px;
  cursor: pointer;
  padding: 3px 8px;
  color: var(--td-text-color-primary);
  transition: background-color 0.2s linear;
  white-space: nowrap;
  word-wrap: normal;
  overflow: hidden;
  text-overflow: ellipsis;
  margin: 0;
}

.tdesign-demo__panel-options-borderless-multiple .t-checkbox:hover {
  background-color: var(--td-bg-color-container-hover);
}
</style>
