// skills/tdesign-vue-next/references/examples/select/noborder.vue
<!--
  TDesign TDesign Vue Next 示例：select - noborder
  覆盖组件：Select
  来源：组件库源码 packages/components/select/_example/noborder.vue
-->

<template>
  <t-select
    v-model="value"
    :borderless="true"
    style="width: 200px"
    placeholder="-请选择-"
    clearable
    auto-width
    :options="options"
  />
</template>
<script lang="ts" setup>
import { ref } from 'vue';
import type { SelectProps } from 'tdesign-vue-next';

const options: SelectProps['options'] = [
  {
    label: '已选择的选项',
    value: '1',
  },
  {
    label: '短的选项二',
    value: '2',
  },
  {
    label: '很长很长很长的选项三',
    value: '3',
  },
];
const value = ref('1');
</script>

// skills/tdesign-react/references/examples/select/noborder.tsx
/**
 * TDesign TDesign React 示例：select - noborder
 * 覆盖组件：Select
 * 来源：组件库源码 packages/components/select/_example/noborder.tsx
 */

import React, { useState } from 'react';
import { Select } from 'tdesign-react';

const SelectNoborder = () => {
  const [value, setValue] = useState('1');
  const onChange = (value: string) => {
    setValue(value);
  };
  return (
    <Select
      value={value}
      onChange={onChange}
      borderless
      clearable={true}
      style={{ width: '40%' }}
      options={[
        {
          label: '已选择的选项',
          value: '1',
        },
        {
          label: '短的选项二',
          value: '2',
        },
        {
          label: '选项内容过长的选择器选项',
          value: '3',
        },
      ]}
    ></Select>
  );
};

export default SelectNoborder;
