// skills/tdesign-vue-next/references/examples/breadcrumb/options.vue
<!--
  TDesign TDesign Vue Next 示例：breadcrumb - options
  覆盖组件：Breadcrumb
  来源：组件库源码 packages/components/breadcrumb/_example/options.vue
-->

<template>
  <t-breadcrumb :options="options" />
</template>

<script lang="tsx" setup>
import type { BreadcrumbProps } from 'tdesign-vue-next';

const options: BreadcrumbProps['options'] = [
  {
    content: '页面1',
  },
  {
    content: '页面2',
  },
  {
    content: '页面3',
    href: 'https://www.tencent.com',
  },
];
</script>

// skills/tdesign-react/references/examples/select/options.tsx
/**
 * TDesign TDesign React 示例：select - options
 * 覆盖组件：Select
 * 来源：组件库源码 packages/components/select/_example/options.tsx
 */

import React, { useState } from 'react';
import { Select } from 'tdesign-react';

const SelectWithOptions = () => {
  const [value, setValue] = useState('apple');
  const onChange = (value: string) => {
    setValue(value);
  };
  const options = [
    {
      label: 'Apple',
      value: 'apple',
    },
    {
      label: 'Banana',
      value: 'banana',
    },
    {
      label: 'Orange',
      value: 'orange',
    },
  ];
  return <Select value={value} onChange={onChange} style={{ width: '40%' }} options={options} filterable />;
};

export default SelectWithOptions;
