// skills/tdesign-vue2/references/examples/upload/request-method.vue
<!--
  TDesign TDesign Vue 2 示例：upload - request-method
  覆盖组件：Upload
  来源：组件库源码 src/upload/_example/request-method.vue
-->

<template>
  <div class="tdesign-demo-block-column-large">
    <div>
      <t-radio-group variant="default-filled" v-model="uploadMethod">
        <t-radio-button value="requestSuccessMethod">上传成功示例</t-radio-button>
        <t-radio-button value="requestFailMethod">上传失败示例</t-radio-button>
      </t-radio-group>
    </div>

    <t-upload
      ref="uploadRef"
      v-model="files"
      :requestMethod="requestMethod"
      tips="自定义上传方法需要返回成功或失败信息"
    ></t-upload>
  </div>
</template>
<script>
/* eslint-disable no-param-reassign */
export default {
  data() {
    return {
      files: [],
      uploadMethod: 'requestSuccessMethod',
    };
  },
  computed: {
    requestMethod() {
      return {
        requestSuccessMethod: this.requestSuccessMethod,
        requestFailMethod: this.requestFailMethod,
      }[this.uploadMethod];
    },
  },
  watch: {
    // 切换上传示例时，重置 files 数据
    uploadMethod() {
      this.files = [];
    },
  },
  methods: {
    // file 为等待上传的文件信息，用于提供给上传接口。file.raw 表示原始文件
    requestSuccessMethod(file /** UploadFile */) {
      console.log(file, file.raw);
      return new Promise((resolve) => {
        // 控制上传进度
        let percent = 0;
        const percentTimer = setInterval(() => {
          if (percent + 10 < 99) {
            percent += 10;
            this.$refs.uploadRef.uploadFilePercent({ file, percent });
          } else {
            clearInterval(percentTimer);
          }
        }, 100);

        const timer = setTimeout(() => {
          // resolve 参数为关键代码
          resolve({ status: 'success', response: { url: 'https://tdesign.gtimg.com/site/avatar.jpg' } });

          clearTimeout(timer);
          clearInterval(percentTimer);
        }, 800);
      });
    },
    requestFailMethod(file /** UploadFile */) {
      console.log(file);
      return new Promise((resolve) => {
        // resolve 参数为关键代码
        resolve({ status: 'fail', error: '上传失败，请检查文件是否符合规范' });
      });
    },
  },
};
</script>

// skills/tdesign-react/references/examples/upload/request-method.tsx
/**
 * TDesign TDesign React 示例：upload - request-method
 * 覆盖组件：Upload
 * 来源：组件库源码 packages/components/upload/_example/request-method.tsx
 */

import React, { useCallback, useRef, useState } from 'react';
import { MessagePlugin, Radio, Space, Upload } from 'tdesign-react';

import type { UploadProps } from 'tdesign-react';

type RequestMethodReturn = Awaited<ReturnType<UploadProps['requestMethod']>>;

const RequestMethod = () => {
  const [files, setFiles] = useState([]);
  const [uploadMethod, setUploadMethod] = useState('requestSuccessMethod');
  const uploadRef = useRef(null);

  // customize upload `file`, if success, return url
  const requestSuccessMethod: UploadProps['requestMethod'] = useCallback(
    (file) =>
      new Promise<RequestMethodReturn>((resolve) => {
        // 上传进度控制示例
        let percent = 0;
        const percentTimer = setInterval(() => {
          if (percent + 10 < 99) {
            percent += 10;
            uploadRef.current.uploadFilePercent({ file, percent });
          } else {
            clearInterval(percentTimer);
          }
        }, 100);

        //  mock upload progress
        let timer = setTimeout(() => {
          // resolve 参数为关键代码
          resolve({
            status: 'success' as const,
            response: { url: 'https://tdesign.gtimg.com/site/avatar.jpg' },
          });
          clearTimeout(timer);
          timer = null;
        }, 1000);
      }),
    [],
  );

  // customize upload `file`, if fail, return error message
  const requestFailMethod: UploadProps['requestMethod'] = useCallback(
    () =>
      new Promise<RequestMethodReturn>((resolve) => {
        const errorResult = {
          status: 'fail' as const,

          // `errorResult.error` is equal to `errorResult.response.error`
          // error: 'for some reason, upload fail',

          // this is request response, response.url is required for file or image preview
          response: { url: '', error: 'for some reason, upload fail' },
        };
        resolve(errorResult);
      }),
    [],
  );

  const onChangeUploadMethod = useCallback((value: string) => {
    setUploadMethod(value);
    setFiles([]);
  }, []);

  const onSuccess = () => {
    MessagePlugin.success('上传成功');
  };

  const onFail = () => {
    MessagePlugin.error('上传失败');
  };

  return (
    <Space direction="vertical" size="large">
      <Radio.Group variant="default-filled" value={uploadMethod} onChange={onChangeUploadMethod}>
        <Radio.Button value="requestSuccessMethod">上传成功示例</Radio.Button>
        <Radio.Button value="requestFailMethod">上传失败示例</Radio.Button>
      </Radio.Group>

      <Upload
        ref={uploadRef}
        files={files}
        onChange={setFiles}
        requestMethod={uploadMethod === 'requestSuccessMethod' ? requestSuccessMethod : requestFailMethod}
        placeholder="自定义上传方法需要返回成功或失败信息"
        onSuccess={onSuccess}
        onFail={onFail}
      />
    </Space>
  );
};

export default RequestMethod;
