// skills/tdesign-mobile-react/references/examples/pull-down-refresh/timeout.tsx
/**
 * TDesign TDesign Mobile React 示例：pull-down-refresh - timeout
 * 覆盖组件：Pull-down-refresh
 * 来源：组件库源码 src/pull-down-refresh/_example/timeout.tsx
 */

import React, { useState } from 'react';
import { PullDownRefresh, Toast } from 'tdesign-mobile-react';

export default function Demo() {
  const [count, setCount] = useState(0);
  return (
    <div>
      <PullDownRefresh
        refreshTimeout={1000}
        onTimeout={() => {
          Toast({ message: '已超时' });
        }}
        onRefresh={() =>
          new Promise((resolve) => {
            setCount(count + 1);
            setTimeout(() => {
              resolve(1);
            }, 2000);
          })
        }
      >
        <div className="pull-down-refresh-content">已下拉{count}次</div>
      </PullDownRefresh>
    </div>
  );
}

// skills/tdesign-mobile-vue/references/examples/pull-down-refresh/timeout.vue
<!--
  TDesign TDesign Mobile Vue 示例：pull-down-refresh - timeout
  覆盖组件：Pull-down-refresh
  来源：组件库源码 src/pull-down-refresh/demos/timeout.vue
-->

<template>
  <div class="tdesign-mobile-demo">
    <tdesign-demo-block title="" summary="">
      <t-pull-down-refresh
        v-model="refreshing"
        :refresh-timeout="1000"
        @timeout="handleTimeout"
        @refresh="handleRefresh"
        >下拉刷新</t-pull-down-refresh
      >
    </tdesign-demo-block>
  </div>
</template>

<script lang="ts">
import { ref, defineComponent } from 'vue';
import { Toast } from 'tdesign-mobile-vue';

export default defineComponent({
  setup(props, context) {
    const refreshing = ref(false);
    const handleRefresh = (value: any) => {
      refreshing.value = true;
      setTimeout(() => {
        refreshing.value = false;
      }, 1000);
    };
    const handleTimeout = () => {
      Toast('已超时');
    };
    return {
      refreshing,
      handleRefresh,
      handleTimeout,
    };
  },
  data() {
    return {};
  },
  methods: {},
});
</script>

<style lang="less" scoped></style>
