// skills/tdesign-react/references/examples/qrcode/customColor.tsx
/**
 * TDesign TDesign React 示例：qrcode - customColor
 * 覆盖组件：Qrcode
 * 来源：组件库源码 packages/components/qrcode/_example/customColor.tsx
 */

import React from 'react';
import { QRCode, Space } from 'tdesign-react';

export default function QRCodeExample() {
  return (
    <Space>
      <QRCode type="canvas" value={'https://tdesign.tencent.com/'} color="#0052D9" bgColor="#fff" />
      <QRCode type="svg" value={'https://tdesign.tencent.com/'} bgColor="#D9E1FF" color="#0052D9" />
    </Space>
  );
}

// skills/tdesign-vue2/references/examples/qrcode/customColor.vue
<!--
  TDesign TDesign Vue 2 示例：qrcode - customColor
  覆盖组件：Qrcode
  来源：组件库源码 src/qrcode/_example/customColor.vue
-->

<template>
  <t-space>
    <t-qrcode value="https://tdesign.tencent.com/" color="#0052D9" bg-color="#fff" />
    <t-qrcode value="https://tdesign.tencent.com/" color="#0052D9" bg-color="#D9E1FF" />
  </t-space>
</template>
