// skills/tdesign-vue-next/references/examples/tree-select/prefixsuffix.vue
<!--
  TDesign TDesign Vue Next 示例：tree-select - prefixsuffix
  覆盖组件：Tree-select
  来源：组件库源码 packages/components/tree-select/_example/prefixsuffix.vue
-->

<template>
  <t-tree-select
    v-model="value"
    :data="options"
    clearable
    placeholder="请选择"
    :popup-visible="popupVisible"
    :prefix-icon="getPrefixIcon"
    :suffix="getSuffix"
    @popup-visible-change="onVisibleChange"
  >
    <!-- 也可以通过插槽方式传递，示例有效勿删 -->
    <!-- <template #prefixIcon>
      <Icon name="happy" />
    </template>
    <template #suffix>foobar suffix</template> -->
  </t-tree-select>
</template>
<script lang="tsx" setup>
import { ref } from 'vue';
import { Icon } from 'tdesign-icons-vue-next';
import type { PopupTriggerEvent, PopupTriggerSource, TreeNodeModel, TreeSelectProps } from 'tdesign-vue-next';

interface TreeSelectPopupVisibleContext<T> {
  e?: PopupTriggerEvent | Event;
  node?: TreeNodeModel<T>;
  trigger?: PopupTriggerSource | 'clear';
}
interface Option {
  label: string;
  value: string;
  disabled?: boolean;
  children?: Option[];
}
const options: TreeSelectProps['data'] = [
  {
    label: '广东省',
    value: 'guangdong',
    children: [
      {
        label: '广州市',
        value: 'guangzhou',
      },
      {
        label: '深圳市',
        value: 'shenzhen',
      },
    ],
  },
  {
    label: '江苏省',
    value: 'jiangsu',
    disabled: true,
    children: [
      {
        label: '南京市',
        value: 'nanjing',
      },
      {
        label: '苏州市',
        value: 'suzhou',
      },
    ],
  },
];
const value = ref('');
const popupVisible = ref(false);
const onVisibleChange = (visible: boolean, context: TreeSelectPopupVisibleContext<Option>) => {
  console.log(visible, context);
  if (context.trigger || context.node?.label !== '广州市') {
    popupVisible.value = visible;
  }
};

// props传递prefixIcon、suffix，请注意属性名拼写不同，区分箭头图标的suffixIcon
const getPrefixIcon: TreeSelectProps['prefixIcon'] = () => <Icon name="center-focus-strong" />;
const getSuffix: TreeSelectProps['suffix'] = () => (
  <div style="color: var(--td-text-color-secondary)">
    <span>后缀内容</span>
    <Icon name="happy" />
  </div>
);
</script>

// skills/tdesign-react/references/examples/tree-select/prefixsuffix.tsx
/**
 * TDesign TDesign React 示例：tree-select - prefixsuffix
 * 覆盖组件：Tree-select
 * 来源：组件库源码 packages/components/tree-select/_example/prefixsuffix.tsx
 */

import React from 'react';
import { CaretDownSmallIcon, UserIcon } from 'tdesign-icons-react';
import { TreeSelect } from 'tdesign-react';

import type { TreeSelectProps } from 'tdesign-react';

const options: TreeSelectProps['data'] = [
  {
    label: '广东省',
    value: 'guangdong',
    children: [
      {
        label: '广州市',
        value: 'guangzhou',
      },
      {
        label: '深圳市',
        value: 'shenzhen',
        children: [
          {
            label: '南山区海天二路33号腾讯滨海大厦',
            value: 'Tencent',
          },
        ],
      },
    ],
  },
  {
    label: '江苏省',
    value: 'jiangsu',
    disabled: true,
    children: [
      {
        label: '南京市',
        value: 'nanjing',
      },
      {
        label: '苏州市',
        value: 'suzhou',
      },
    ],
  },
];

export default function Example() {
  return (
    <TreeSelect
      data={options}
      clearable
      placeholder="请输入"
      prefixIcon={<UserIcon />}
      suffixIcon={<CaretDownSmallIcon />}
      style={{ width: 300 }}
    />
  );
}
