// skills/tdesign-react/references/examples/qrcode/customStatusRender.tsx
/**
 * TDesign TDesign React 示例：qrcode - customStatusRender
 * 覆盖组件：Qrcode
 * 来源：组件库源码 packages/components/qrcode/_example/customStatusRender.tsx
 */

import React from 'react';
import { CheckCircleFilledIcon, CloseCircleFilledIcon, RefreshIcon } from 'tdesign-icons-react';
import { Loading, QRCode, Space } from 'tdesign-react';

import type { QrCodeProps } from 'tdesign-react';

const value = 'https://tdesign.tencent.com/';

const customStatusRender: QrCodeProps['statusRender'] = (info) => {
  switch (info.status) {
    case 'expired':
      return (
        <div style={{ display: 'flex', alignItems: 'center', flexDirection: 'column' }}>
          <p style={{ display: 'flex', alignItems: 'center', columnGap: '8px' }}>
            <CloseCircleFilledIcon style={{ color: 'red' }} size={16} />
            <span>二维码过期</span>
          </p>
          <p
            style={{
              display: 'flex',
              alignItems: 'center',
              columnGap: '8px',
              color: '#0052d9',
              cursor: 'pointer',
              lineHeight: '32px',
            }}
          >
            <RefreshIcon size={16} />
            <span>点击刷新</span>
          </p>
        </div>
      );
    case 'loading':
      return (
        <Space direction="vertical">
          <Loading size="32px" />
          <p>加载中...</p>
        </Space>
      );
    case 'scanned':
      return (
        <div style={{ display: 'flex', alignItems: 'center', columnGap: '8px' }}>
          <CheckCircleFilledIcon style={{ color: '#2ba471' }} size={16} />
          <span>已扫描</span>
        </div>
      );
    default:
      return null;
  }
};

export default function QRCodeExample() {
  return (
    <Space>
      <QRCode value={value} status="loading" statusRender={customStatusRender} />
      <QRCode
        value={value}
        status="expired"
        onRefresh={() => console.log('refresh')}
        statusRender={customStatusRender}
      />
      <QRCode value={value} status="scanned" statusRender={customStatusRender} />
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/qrcode/customStatusRender.vue
<!--
  TDesign TDesign Vue Next 示例：qrcode - customStatusRender
  覆盖组件：Qrcode
  来源：组件库源码 packages/components/qrcode/_example/customStatusRender.vue
-->

<template>
  <t-space>
    <!-- 自定义状态-使用Function -->
    <t-qrcode value="https://tdesign.tencent.com/" status="loading" :status-render="renderStatus" />
    <!-- 自定义状态-使用插槽 -->
    <t-qrcode value="https://tdesign.tencent.com/" status="expired">
      <template #status-render="{ status }">
        <div v-if="status === 'expired'" class="tdesign-demo-qrcode__status-render">
          <p class="tdesign-demo-qrcode__status-render-title">
            <CloseCircleFilledIcon size="16" />
            <span>二维码过期</span>
          </p>
          <p class="tdesign-demo-qrcode__status-render-action" @click="handleRefresh">
            <RefreshIcon size="16" />
            <span>点击刷新</span>
          </p>
        </div>
      </template>
    </t-qrcode>
    <!-- 默认状态 -->
    <t-qrcode value="https://tdesign.tencent.com/" status="scanned" />
  </t-space>
</template>

<script lang="tsx" setup>
import { CloseCircleFilledIcon, RefreshIcon } from 'tdesign-icons-vue-next';
import type { QRCodeProps } from 'tdesign-vue-next';

const renderStatus: QRCodeProps['statusRender'] = (_h, { status }) => {
  return (
    status === 'loading' && (
      <t-space direction="vertical" size="4px">
        <t-loading size="32px" />
        <p>加载中...</p>
      </t-space>
    )
  );
};

const handleRefresh: QRCodeProps['onRefresh'] = () => {
  console.log('Click Refresh');
};
</script>

<style>
.tdesign-demo-qrcode__status-render {
  display: flex;
  align-items: center;
  flex-direction: column;
}

.tdesign-demo-qrcode__status-render-title {
  display: flex;
  align-items: center;
  gap: 8px;
}

.tdesign-demo-qrcode__status-render-title .t-icon {
  color: var(--td-error-color);
}

.tdesign-demo-qrcode__status-render-action {
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--td-brand-color);
  cursor: pointer;
  line-height: 32px;
}
</style>
