// skills/tdesign-react/references/examples/button/ghost.tsx
/**
 * TDesign TDesign React 示例：button - ghost
 * 覆盖组件：Button
 * 来源：组件库源码 packages/components/button/_example/ghost.tsx
 */

import React from 'react';
import { Button, Space } from 'tdesign-react';

export default function ButtonExample() {
  return (
    <Space direction="vertical">
      <Space>
        <Button variant="outline" ghost>
          幽灵按钮
        </Button>
        <Button variant="dashed" ghost>
          幽灵按钮
        </Button>
        <Button variant="text" ghost>
          幽灵按钮
        </Button>
      </Space>
      <Space>
        <Button variant="outline" theme="primary" ghost>
          幽灵按钮
        </Button>
        <Button variant="dashed" theme="primary" ghost>
          幽灵按钮
        </Button>
        <Button variant="text" theme="primary" ghost>
          幽灵按钮
        </Button>
      </Space>
      <Space>
        <Button variant="outline" theme="success" ghost>
          幽灵按钮
        </Button>
        <Button variant="dashed" theme="success" ghost>
          幽灵按钮
        </Button>
        <Button variant="text" theme="success" ghost>
          幽灵按钮
        </Button>
      </Space>
      <Space>
        <Button variant="outline" theme="warning" ghost>
          幽灵按钮
        </Button>
        <Button variant="dashed" theme="warning" ghost>
          幽灵按钮
        </Button>
        <Button variant="text" theme="warning" ghost>
          幽灵按钮
        </Button>
      </Space>
      <Space>
        <Button variant="outline" theme="danger" ghost>
          幽灵按钮
        </Button>
        <Button variant="dashed" theme="danger" ghost>
          幽灵按钮
        </Button>
        <Button variant="text" theme="danger" ghost>
          幽灵按钮
        </Button>
      </Space>
    </Space>
  );
}

// skills/tdesign-vue-next/references/examples/button/ghost.vue
<!--
  TDesign TDesign Vue Next 示例：button - ghost
  覆盖组件：Button
  来源：组件库源码 packages/components/button/_example/ghost.vue
-->

<template>
  <t-space direction="vertical">
    <t-space>
      <t-button variant="outline" ghost>幽灵按钮</t-button>
      <t-button variant="dashed" ghost>幽灵按钮</t-button>
      <t-button variant="text" ghost>幽灵按钮</t-button>
    </t-space>
    <t-space>
      <t-button variant="outline" theme="primary" ghost>幽灵按钮</t-button>
      <t-button variant="dashed" theme="primary" ghost>幽灵按钮</t-button>
      <t-button variant="text" theme="primary" ghost>幽灵按钮</t-button>
    </t-space>
    <t-space>
      <t-button variant="outline" theme="success" ghost>幽灵按钮</t-button>
      <t-button variant="dashed" theme="success" ghost>幽灵按钮</t-button>
      <t-button variant="text" theme="success" ghost>幽灵按钮</t-button>
    </t-space>
    <t-space>
      <t-button variant="outline" theme="warning" ghost>幽灵按钮</t-button>
      <t-button variant="dashed" theme="warning" ghost>幽灵按钮</t-button>
      <t-button variant="text" theme="warning" ghost>幽灵按钮</t-button>
    </t-space>
    <t-space>
      <t-button variant="outline" theme="danger" ghost>幽灵按钮</t-button>
      <t-button variant="dashed" theme="danger" ghost>幽灵按钮</t-button>
      <t-button variant="text" theme="danger" ghost>幽灵按钮</t-button>
    </t-space>
  </t-space>
</template>
