// skills/tdesign-mobile-react/references/examples/avatar/size.tsx
/**
 * TDesign TDesign Mobile React 示例：avatar - size
 * 覆盖组件：Avatar
 * 来源：组件库源码 src/avatar/_example/size.tsx
 */

import React from 'react';
import { Avatar } from 'tdesign-mobile-react';
import { UserIcon } from 'tdesign-icons-react';

export default function SizeAvatar() {
  return (
    <div className="tdesign-demo-avatar">
      <div className="avatar-demo">
        <Avatar
          className="avatar-example--large"
          shape="circle"
          size="large"
          image="https://tdesign.gtimg.com/mobile/demos/avatar1.png"
          alt="实例图片"
        />
        <Avatar className="avatar-example--large external-class-content" shape="circle" size="large">
          A
        </Avatar>
        <Avatar className="avatar-example--large" shape="circle" size="large" icon={<UserIcon />} />
      </div>
      <div className="avatar-demo">
        <Avatar
          className="avatar-example--medium"
          shape="circle"
          size="medium"
          image="https://tdesign.gtimg.com/mobile/demos/avatar1.png"
          alt="实例图片"
        />
        <Avatar className="avatar-example--medium external-class-content" shape="circle" size="medium">
          A
        </Avatar>
        <Avatar className="avatar-example--medium" shape="circle" size="medium" icon={<UserIcon />} />
      </div>
      <div className="avatar-demo">
        <Avatar
          className="avatar-example--small"
          shape="circle"
          size="small"
          image="https://tdesign.gtimg.com/mobile/demos/avatar1.png"
          alt="实例图片"
        />
        <Avatar className="avatar-example--small external-class-content" shape="circle" size="small">
          A
        </Avatar>
        <Avatar className="avatar-example--small" shape="circle" size="small" icon={<UserIcon />} />
      </div>
    </div>
  );
}

// skills/tdesign-mobile-vue/references/examples/badge/size.vue
<!--
  TDesign TDesign Mobile Vue 示例：badge - size
  覆盖组件：Badge
  来源：组件库源码 src/badge/demos/size.vue
-->

<template>
  <div>
    <div class="summary">Large</div>
    <div class="block">
      <t-avatar :icon="IconUser" size="large" :badge-props="{ count: 8, size: 'large', offset: [7, 7] }" />
    </div>

    <div class="summary">Medium</div>
    <div class="block">
      <t-avatar :icon="IconUser" :badge-props="{ count: 8, offset: [5, 5] }" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { UserIcon } from 'tdesign-icons-vue-next';
import { h } from 'vue';

const IconUser = () => h(UserIcon, { size: '24px' });
</script>

<style>
.block {
  padding: 16px 16px 24px;
}
</style>
